@startmindmap

* 战略决策阶段（二）

** 企业产品战略
*** 产品战略概述
**** 产品的概念与产品的整体概念
*****_:
「产品」的概念：
1.传统观点：从生产角度理解，把产品看成一种有形实体，
是生产者生产的具有某种特定物质形状和用途的物体
2.现代观点：从生产和营销角度理解，是生产者生产出来
提供给市场，引起顾客注意，促使其购买，满足某种欲望
或需要的实体

「产品的整体」概念：
五个层次
1.核心产品：指向顾客提供的产品基本效用或利益
2.形式产品：产品借以实现的形式，如外包装
3.期望产品：期望产品具有的属性，如冰箱的省电属性
4.延伸产品：附加服务，如提供信贷、免费送货、安装
5.潜在产品：指现有产品包括所有附加产品在内，可能发展
成未来最终产品的潜在状态的产品
;
*****_:
「产品要素」：指构成产品的元素及其素质，包括「有形要素」
和「无形要素」
有形要素：产品数量、品种、品质、花色、款式、造型
无形要素：安装、调试、培训、咨询、维修、送货、信誉
;
**** 产品战略的概念和作用
*****_:
「产品战略」：指企业生产某种产品或生产某些不同的产品，
去满足「目标市场」顾客的需要，并「实现企业总体经营战略」
所确定的目标而做出的阐远兴谋划和方略。
作用：在企业职能战略体系处于核心地位，作用有
1.正确的产品战略有助于提高企业经营战略决策水平
2.正确的产品战略有利于增强企业生命力
3.正确的产品战略有利于提高企业和社会的经济效益
;
**** 产品战略的选择方法
*****_:
1.产品寿命周期法
2.产品组合优化法
;
*** 产品寿命周期与产品战略
**** 产品寿命周期含义
*****_:
「产品寿命周期」：指产品从投入开发到投入生产，投放市场
开始，经过成长、发展、成熟到衰退，被另一种新产品所淘汰
为止的整个过程。
;
**** 产品寿命周期阶段划分
*****_:
广义产品寿命周期包括七个阶段：产品设想期、产品设计期、
产品试制期、产品投入期、产品成长期、产品成熟期、产品
衰落期
狭义是广义后四个阶段：投入、成长、成熟、衰落
;
**** 不同寿命周期阶段的战略
*****_:
1.投入期：“以新领先”、“新品完善”、“新品形象”
2.成长期：新产品生产扩大化、新品品牌
3.成熟期：改进或改革产品、优质低价、产品差异化
4.衰退期：集中战略、收益战略、逐步减产、最后淘汰
;
*** 产品优化战略
**** 含义
*****_:
「产品组合优化战略」是指依据产品组合的方法，对企业生产
经营的全部产品及其组合进行分析评估，以此做出产品优化的
规划与谋略
「产品组合」是一个企业生产或经营的全部产品线、产品项目
的组合方式，它包括四个变数：广度、长度、深度、密度
;
**** 方法与战略
*****_:
常用的产品组合优化方法是「产品项目平衡管理技术」（PPM）
步骤如下：
1.确定产品的市场新引力和企业实力各个具体因素的评分标准
2.按照各项因素的评分标准对每个产品评分，分别计算每种产品
「市场吸引力」和「企业实力」总分
3.依据产品的市场吸引力总分和企业实力总分高低划分大、中、
小三等
4.按照每种产品市场吸引力和企业实力大中小情况，填入产品
系列分布象限图
5.依据象限图所在位置，采取不同战略
  「市场吸引力」=引力；「企业实力」=实力
  1象限：引力大实力小，「问题」产品。应选择投资，积极发展
  2象限：引力中实力小，「风险」产品。维持现状，努力获利
  3象限：引力小实力小，「滞销」产品。回收投资，淘汰
  4象限：引力大实力中，「亚名牌」产品。增加投资，大力发展
  5象限：引力中实力中，「维持」产品。维持现状
  6象限：引力小实力中，「滞销」产品。撤退，淘汰
  7象限：引力大实力大，「名牌」产品。积极投资，提高占有率
  8象限：引力中实力大，「高盈利」产品。改进提高或尽力获利
  9象限：引力小实力大，「微利、无后劲」产品。减产淘汰
;
**** 产品结构优化战略
*****_:
「产品结构」指社会产品各个组成部分所占比重和相互关系总和。
反应社会生产性质和发展水平、资源利用状况及满足社会需要程度
宏观：一个国家或地区各类产品在国民经济中构成情况
微观：一个企业生产各种不同类型产品的比例关系
「产品结构优化」指在满足社会需要和国家要求的基础上，在
各种相关因素约束条件下，寻求企业不同产品最佳组合
;
**** 产品结构优化战略的类型
*****_:
1.产品方向结构优化战略
2.产品用途结构的优化战略
3.产品技术结构的优化战略
4.产品档次结构的优化战略
5.产品材质结构的优化战略
6.产品序列结构的优化战略
;
*** 产品开发战略
**** 概念
*****_:
「产品开发战略」指考虑在现有市场上通过改良现有产品
或开发新产品来扩大销售量的战略
;
**** 产品开发战略的层次
*****_:
1.产品战略愿景：“瓜种”
2.产品平台：“瓜的主藤”
3.产品线：“瓜的支藤”
4.产品开发项目：“瓜”
;
**** 产品开发战略的类型选择
*****_:
1.按产品开发的新颖程度分类：全新型、换代型、改进型
2.按产品开发新的范围和水平分类：地区级、国家级、
国际区域级、世界级
3.按产品开发方向分类：功能化、规格化、精密度、节能化、
特色化、差异化
4.按产品开发主体主动性进行分类：领先型、追随型
;
**** 产品开发战略的影响因素
*****_:
1.技术可行性
2.成本投入能力
3.经营网络能力
4.市场的可行性
;
*** 产品质量战略
**** 概述
*****_:
「产品质量」是指产品的使用价值，满足用户和消费者在
生产、工作、生活上一定需要的性质。特征包括：
产品性能、产品寿命、产品可靠型、安全性、经济性
「产品质量战略」是指企业设计和生产顾客所需的质量
特性，达到顾客所要求的质量水平，满足需要，所作出
的谋划与方略。其作用包括：
1.是企业产品结构优化战略的一个重要内容
2.是推动企业技术进步战略的一个重要方面
3.推动着企业智力开发战略
4.带动着企业生产战略
5.有利于推动企业的影响战略
;
**** 产品质量战略类型选择
*****_:
1.产品质量特性组合战略：根据顾客对产品「内在质量」
和「外部质量」不同要求，组合不同的战略
2.产品性能战略
3.产品质量标准战略
4.市场动态质量战略
5.质量目标战略
;
**** 产品质量战略的影响因素
*****_:
1.产品性能
2.产品特征
3.产品可靠性
4.产品一致性
5.产品耐用性
6.产品可修复性
7.产品的外观
8.产品质量的被感知性
;
*** 产品战略决策的考虑因素
**** 产品未来的发展前途
**** 产品收益性
**** 产品竞争性
**** 资源条件
**** 技术条件
**** 商品化程度
**** 销售可能性
**** 国家法律法规与政策要求

** 企业技术创新战略

** 企业人力资源战略

** 企业财务战略

** 企业文化战略

@endmindmap