@startmindmap

* 绪论

** <&star>概念&研究内容
*** 概念与学科性质
****_:
「<&globe>组织行为学」
1.研究对象是「人的心理和行为的规律性」
2.研究范围是「特定组织」中人的心理和行为规律
3.研究目的是「提高预测、引导及控制人的行为的能力」，以提升工作绩效及员工满意度。
;
****_:
「学科性质」：
1.跨学科性：管理学、心理学、社会学、文化人类学
2.系统性：个体、群体、组织 -> 形成系统相互联系
3.权变性：人是复杂的，不同的人和不同的情景表现各不相同
4.实用性：可应用于管理，为管理者提供指导
5.科学性：现象和数据支持，经过验证
;
*** 研究内容
****_:
1.「<&globe>个体」心理与行为研究
2.「<&globe>群体」心理与行为研究
3.「<&globe>组织」行为研究
4.「<&globe>领导」行为研究
;

** 产生&发展
*** 学科基础
****_:
组织行为学是「应用型」行为科学，在多学科基础上建立的，包括：
心理学、社会学、社会心理学、人类学、政治学
;
*** 产生
****_:
1.个体行为：早期「<&people>泰勒的《科学管理原理》」出版，标志管理学成为独立科学
2.个体心理：工业心理学创始人<&people>闵斯特伯格出版《心理学与工业效率》一书，正式把心理学应用到工业管理
3.群体心理：工业社会心理学，<&people>梅奥主持“霍桑实验”，发现工作群体的重要性，提出人际关系学说
4.管理心理：管理占据核心地位，应当将“管理”凸显出来
5.组织行为：「<&people>莱维特」在《心理学年鉴》中提到「“组织心理学”」概念
6.组织行为产生
;
*** 发展
****_:
1.20世纪初到20世纪30年代，<&people>泰勒、<&people>韦伯和<&people>法约尔为代表，把组织看成「封闭的理性模式」（经济人）
  1）泰勒开创了科学管理先河，被誉为「科学管理之父」
  2）法约尔被称为「管理过程之父」
  3）韦伯被称为「组织管理之父」
2.20世纪30年代至20世纪60年代，以<&people>梅奥、<&people>麦格雷戈等代表，把组织看成「封闭的社会性模式」（社会人）
3.20世纪60年代至20世纪70年代，以<&people>费德勒为代表，把组织看成「开放的模式」（外界环境），由封闭转向
  开放是一大进步
4.20世纪70年代至今，综合前三阶段所长，把组织看成「开放的社会性模式」，把组织行为学研究转变到社
会文化的深层次上（美国学习日本）
;

** <&star>研究过程&研究方法
*** 研究过程
****_:
组织行为学「研究三个步骤」：
1.归纳综合
2.演绎推论
3.检验
;
****_:
美国管理学家<&people>西拉季和<&people>华莱士把组织行为学研究「细分为六个步骤」：
1.弄清要研究的问题
2.查阅与某种行为问题有关的理论和信息资料
3.形成假设
4.选择正确的设计步骤和方法开展研究工作
5.识记观察、测试和实验
6.解释研究结论
;
*** 研究方法
****_:
1.「<&flag>观察法」：借助人的「感官」和各种测量仪器对研究对象「观察」、「观测」，
将工作过程、行为等进行分析与归纳总结并记录，包括「参与观察法」，
「非参与观察法」
  优点：a.简便易行；b.材料真实；c.全面和深入
  缺点：a.花费时间；b.难以量化；c.被观察者被监视难以接受
2.「<&flag>调查法」：为了达到设想目的，制定计划就一些问题对个人或群体「访问或发放调查」
要求被调查者回答，收集所需各种资料数据，分析推测行为与心理倾向，分为
「访谈法」和「问卷法」
  1）访谈法：又称「面谈法」，应用最广泛，可以「标准化」或「非标准化」
    优点：a.可以对员工工作态度和动机较深层次了解；b.运用面广，简单迅速；
          c.易了解直接观察法不容易发现的地方；d.有助于员工沟通
    缺点：a.要求访谈者专业；b.费事费力成本高；c.无法避免主观因素、暗示、
          诱导信息失真
  2）问卷法：根据研究课题目的，预先设置问题，编制问卷，对人心理行为进行
  调查，分析得出结论，分为「开放式」和「封闭式」
    优点：a.范围广；b.样本大；c.可以量化，计算机数据处理
    缺点：a.问卷设计花费时间；b.问卷需要测试；c.被调查者可能不积极配合，
          影响质量
3.「<&flag>个案分析法」：研究者通过对个体、群体或组织整体情况「较长时间连续」调查，
全面收集资料，从而研究其心理发展「全过程」，得出结论
4.「<&flag>实验法」：人为控制环境下精确操纵自变量从而考察因变量如何因其变化，进而
研究变量关系的方法，分为「实验室实验」和「现场实验」
5.「<&flag>心理测验法」：采用标准化心理测量量表或精密仪器测量被试者，以「信度」和
「效度」表明结果的可靠性和有效性
6.「<&flag>情景模拟法」：根据被试者承担或将要承担的工作任务，研究人员设计一套与岗位
实际情景相似的「测试场景」，将被试者放置与模拟工作环境中，观察被试者才能行为，
具有针对性、客观性、预测性、动态性。信度和效度比较高
;

@endmindmap