@startmindmap

* 组织

** 组织

*** 概述
**** 识记
*****_:
概念：组织是人们为了实现共同的目标而
组成的有机整体（静态组织，动态组织）
;
*****_:
特征：
1. 具有明确的目标：没有目标的不是组织是群体
2. 拥有资源：人、财、物、信息、时间
3. 具有一定的权责结构：权责分明、对等
;
*****_:
分类：
1. 组织规模：小、中、大型组织
2. 组织性质：政治、经济、文化、群众、宗教
3. 组织目标：营利性、非营利性、公共组织
4. 组织特性：机械式、有机式
5. 有意建立和自发形成：正式与非正式组织
6. 组织形态：实体组织与虚拟组织
;
**** 领会
*****_:
作用：
1. 使工作任务清晰化：梳理、分类、归并、清晰、明了
2. 使资源分配统筹化：统筹分配优先资源
3. 使工作内容专业化：达到熟练、经验丰富、效率高
4. 使工作衔接无缝化：分工协作，相互配合
;
*****_:
目标：
1. 实现组织的效率与效益：组织的根本目标
2. 积聚组织成员的士气：上下级融洽，平级相互配合，良好工作氛围
3. 使组织持续发展：根据内外环境变化不断调整、变革、重组，实现持续发展
;

*** 设计
**** 识记
*****_:
组织设计的含义：组织设计就是根据组织目标对组织结构和活动进行筹划和考虑，内容为：
1. 根据任务和目标的要求，进行职能与职务的分析，设计组织结构
2. 进行部门设计和层次设计，划分各机构间的上下左右关系、职责权限和分工协作范围
3. 建立机构间的工作流程和沟通渠道
4. 制定一定的政策方针和措施使机构有序运转
;
*****_:
管理层次：指从最高管理人员到最低工作人员中间所拥有的级数，层次多少视具体情况而定
;
*****_:
管理「幅度」与「层次」的关系：
组织规模一定的条件下，~成反比 
管理幅度越大，管理层次越少；
管理幅度越小，管理层次越多。
这样就形成了「垂直结构」和「扁平结构」
;
*****_:
垂直结构与扁平结构：
1. 垂直结构：即多层次结构，最高层与作业层之间存在较多的管理层次，而每个管理层次的管理幅度小
    优点：可以严密监督控制；能体现上级意图；组织稳定性高
    缺点：妨碍下属主动性发挥；增加管理费用；信息传递渠道长；管理效率低
2. 扁平结构：指管理层次少管理幅度大的结构，分权型组织
    优点：有利于缩短上下级距离，密切上下级关系；信息纵向流通快，管理费用低；
    由于管理幅度较大，被管理者有较大的自主性、积极性和满足感
    缺点：不能严密地监督下级，易失控；管理幅度的增大，造成同级间沟通困难
;
*****_:
职权的概念：职权是组织设计中赋予某一管理职位的权利。包括三层含义：
1. 职权的来源是组织，它是组织授权的
2. 职权的基础是职位，获得职权必获得职位
3. 职权是以履行职责为前提的，职权的大小取决于职责范围的大小
分类：
1. 直线职权：即按照等级原则和指挥链，由上级对下级逐级发布命令和进行指挥的权利（主要）
2. 参谋职权：是一种服务和协助的关系，是承担参谋职能的人所拥有的职权（建议权）
3. 职能职权：根据高层管理者授权，参谋人员拥有的对其他部门或人员的直接指挥权
;
**** 领会
*****_:
管理幅度的影响因素：
1.管理人员的素质及领导风格
2.下属的素质
3.管理工作的复杂程度
4.管理的规范性
5.沟通和联络技术
6.授权的程度
7.空间距离的远近
8.外部环境
;
*****_:
组织设计影响因素：
1. 环境：根据外部环境的不确定程度来设计不同类型（机械或灵活）的组织结构
2. 战略：组织设计应该适应战略。战略在两个方面影响组织：战略要求和战略重点改变
3. 技术：组织设计需因技术的变化而变化。（单件小批量生产、大批量~、流程~)
4. 发展阶段：企业生命周期（创业阶段、集合阶段、规模化阶段、精细阶段），不同阶段组织的特点不同
原则：
1. 目标统一原则：总目标统领分目标
2. 专业化分工原则：合适的岗位合适的人
3. 统一指挥原则：各级机构和个人服从指挥
4. 责权对等原则：各层次各岗位权责一致
5. 有效管理幅度原则：管理幅度适度
6. 集权与分权结合原则：因情况而定
7. 稳定性与适应性相结合原则：因情况而定
8. 精简高效原则：机构简单，人员精干
;
*****_:
组织设计部门化：
指根据专业化原则把性质类似或有密切关系的活动划分在同一部门内，以提高工作效率
划分方法：
1.按职能划分部门（最普遍，在稳定的技术和环境下比较有效）
    优点：可以有效利用资源达到规模经济；符合专业化原则；有利于员工职业生涯发展
    缺点：协调困难；各部门易产生”隧道视野”；适应性差；不利于培养综合管理者
2.按产品划分部门（根据生产经营不同产品或系列划分，适合多元化经营的企业）
    优点：有利于深入研究各业务的特点，提高产品质量和增加产品功能，有利于业务改进，更好满足
顾客的需要；有利于部门内协调；便于对绩效的测评；有利于综合管理者的培养
    缺点：可能造成机构重叠；部门的本位主义；需要更多具有全面管理能力的人
3. 按地区划分部门（适合地区差异明显，环境多变的情况）
    优点：针对性强，能对本地环境变化迅速作出反应；地区内有很好的协作，各种活动易于协调；
便于对绩效的测评；有利于综合管理者的培养
    缺点：可能造成某些活动的重复、机构重叠；地区间会相互竞争，争夺组织资源，形成地区的本位
主义；总部协调困难；需要更多具有全面管理能力的人
4. 按顾客划分部门
    优点：有利于深入研究特定顾客的需求，对顾客更加了解，针对性强，服务更到位
    缺点：可能使企业的某些资源不能充分利用，忙闲不均，有时对顾客明确分类有难度，变化难适应
5. 按流程划分部门
    优点：符合专业化的原则，能有效利用专业化技术和特殊技能；简化员工培训；部门间关系清晰，
责任明确
    缺点：不适合培养全面的综合管理人才，各部门对本过程或环节的生产和质量负责而不是对最后的
成果负责；一个部门发生问题将直接影响整个组织目标的完成；需要部门间的紧密协调和高层严格控制
;
**** 应用
*****[#lightblue]:
集权与分权：集权与分权是指职权的集中程度和分散程度，它们是相对的，没有绝对集权和分权
1. 集权：职权集中化，是指决策权在很大程度上向处于较高管理层次的职位集中的
组织状态和组织过程
    优点：有利于集中领导和统一指挥；有利于部门与整体的协调一致；有利于加强
控制，形成统一意志。
    缺点：限制了下属的积极性、主动性和创造性发挥；使领导过多地关注具体事务
而不是重大问题；使组织缺乏必要的灵活性和适应性，易于僵化
2. 分权：职权的分散化，是决策权在很大程度上分散到处于较低管理层次的职位上
    优点：有利于发挥上下级主动性和创造性；能够使下级自主工作；便于领导关注
组织的重大问题；使组织有较强的灵活性和适应性
    缺点：不利于实行集中统一的指挥；容易导致各部门的本位主义倾向，影响整体
利益；增加协调和控制的难度，易于分散和各自为政

影响集权分权的因素：
1.决策的代价
2.政策一致性的愿望
3.组织的规模和经营特点
4.管理人员的性格素质
5.控制技术
6.组织的历史和文化
7.组织变革的速度
8.环境的变化
;
*****[#lightblue]:
授权：上层管理人员将适当的权利授予下属，让下属在制定的职责范围内
做出决定和支配资源。授权是分权的主要手段
授权的必要性：
1. 管理宽度的原因：时间、精力限制
2. 经济、效率的原因：因小失大、事无巨细
3. 知识限制的原因：术业有专攻
4. 培养管理人才的原因

授权的要求：
1.明确职责：该做什么，做到什么程度
2.根据预期成果授权：权利与任务适应
3.授权对象适合：愿意做、有能力的人
4.有顺畅的沟通渠道：上下信息沟通顺畅
5.有适当的控制：指挥和监督
;

*** 组织结构的类型
**** 识记
*****_:
组织结构的概念：是指组织的基本架构，是对完成组织目标的人员、工作、技术和信息
所做的制度性安排
;
**** 应用
*****[#lightblue]:
不同类型组织结构的特点、优缺点及实际中的应用：
类型包括「直线型」、「直线职能制」、「事业部制」、「矩阵制」、「委员会制」、「团队结构」：
1.「直线型」：指高层领导不通过或只通过一个或少数的中间层次直接指挥下属，不单独设
职能机构，实行上下垂直领导的一种组织结构形式。
    优点：领导隶属关系简单、明确，机构简单，指挥统一，上下信息传递迅速
    缺点：领导须通晓各种知识和业务，亲自处理各种工具工作，负担过重，无暇顾及
长远的重大问题，在组织规模扩大时无力应付，管理方式简单粗放（适用于小型组织）
2.「直线职能制」：以直线领导为主，同时辅以职能部门的参谋作用的组织结构。
    优点：分工细致，任务明确；有较高的效率；稳定性高；保证集中统一指挥；可发挥
各类专家的专业管理作用
    缺点：各部门缺乏全局观点；不易从组织内部培养熟悉全面情况的管理人才；分工
较细，手续繁琐，反应较慢，不易迅速适应新情况（适合环境稳定中小型组织）
3.「事业部制」：（又称斯隆模型、联邦分权制）是在一个企业内对具有独立产品市场、独立
责任和利益的部门实行分权管理的一种组织形式。一般做法：
    1）总公司成为投资决策中心，保留重大人事决策、预算控制、战略决策等权利，主要
利用利润指标对事业部进行控制
    2）在总公司下按产品或地区分许多个事业部或分公司，他们都是独立核算、自负盈亏
的利润中心
    3）下属的生产单位则是成本中心
    优点：专业化管理和集中统一领导的有机结合；有利于最高领导层摆脱日常事务，集中
精力考虑战略性决策，强化决策机构；每个事业部具有独立的利益，是一个分权单位，有
利于调动其积极性；有利于培养综合型高级管理人才
    缺点：集权与分权敏感，易产生本位主义；机构相对重叠，管理人员过多；对事业部经理
的素质要求较高；总公司对各事业部协调任务较重（适合环境比较复杂、多文化经营、大
规模组织）
4.「矩阵制」：（又称规划和目标机构制）在直线职能垂直形态组织系统的基础上，再增加一种
横向指挥系统，形成具有双重职权关系的矩阵制组织结构。
    优点：将集权与分权，纵向与横向管理结合起来，提高管理效率；灵活机动，专业设备
和人员得到了充分利用，适应性强；促进各种专业人员相互沟通、相互帮助、培养合作精神
和全局观念
    缺点：成员位置不固定，稳定性差，有临时观念影响工作责任心；违背统一指挥原则，小
组织成员无所适从（适合需要多部门相互配合或工作具有临时性的组织）
5.「委员会制」：由若干人组成的群体，委员会中各个委员的权利是平等的，依据少数服从多数
的原则处理问题。特点：集体决策、集体行动。委员会由临时和常设之分。其目的：
    1）集思广益，提高决策的正确性
    2）集体决策，防止个别人或个别部门权限过大，滥用权力
    3）加强沟通，了解来自各方面的意见和建议
    4）鼓励参与，激发决策执行者的积极性
注意问题：
    1）审慎使用委员会：清理可有可无的委员会
    2）选择合格的委员会成员：根据目的选择
    3）委员会的规模要适宜：在”沟通效果“和”代表性“间权衡
    4）发挥委员会主席的作用：领导才能决定工作成效
    5）提高委员会的运营效率：考核机制
    优点：可以发挥集体的智慧，提供更多、更完整的信息，避免个别人的判断失误；少数
服从多数，防止个人滥用权力；成员地位平等，有利于沟通和协调；有更多参与的机会，可
激发组织成员的积极性
    缺点：耗费时间，做出决定往往需要较长时间，有时议而不决；受某人或少数人主导；
从众现象或折中调和；责任模糊，集体负责时导致大家都不负责
6.「团队结构」：团队是指完成相互依存的任务，实现共同使命的一群人。团队结构指整个组织
由组织执行组织各项任务的团队组成的组织结构。其特点：
    1）具有共同目标，与组织目标密切相关
    2）具有自主决策权，要承担活动的全部责任
    3）团队中每个成员都是多面手，团队中有分工，但更强调合作，是相互作用的群体
    4）团队结构对顾客的响应速度更快，服务质量和服务效率更高
    优点：每个成员都有明确的团队工作并为之负责；具有较大的适应性，能接受新思想和
新工作方法，迅速分享信息，协调工作；团队能够给顾客提供更卓越的服务
    缺点：小组的领导人如果不提出明确要求，团队就缺乏明确性；稳定性差，团队必须持续
不断地注意管理；团队成员虽然了解共同任务，但不一定对自己的具体任务非常了解，甚至
可能对别人的工作过于感兴趣，而忽略了自己的工作
;

** 人员配备

*** 概述
**** 识记
*****_:
「人员配备」：是组织工作的逻辑延续，是指为了实现组织目标对人员进行恰当而
有效的「招聘」、「甄选」、「培训」、「绩效考核」等，从而确定合适的人员去
充实组织机构中所规定的各项职务，保证组织活动的正常进行
;
*****_:
特点：
1.人员配备以组织的目标和战略为指导，与组织的长期
发展规划相适应：要有前瞻性和预见性，服务组织目标
2. 人员配备是以人为中心的管理：”关心人、尊重人、
理解人、依靠人“，发挥人的积极性、主动性和创造性
3. 人员配备是管理最复杂的环节：选人、育人、用人、
留人、评人等。
;
**** 领会
*****_:
人员配备过程：
1.人力资源计划（步骤包括评估现有人力资源，评估未来所需要的
人力资源，制定一套相应的方案，以确保未来人力资源供需匹配）
2.工作分析与职位设计（编制成岗位说明书，具体明确工作职责与
权限、工作目标、工作特点、任职人员资格等，并能为工作评价、
人员招聘、绩效考核、培训与开发、薪酬管理等提供依据）
3.招聘与甄选
4.培训与发展
5.绩效考核：奖惩的依据
6.奖惩、调职、离职
;
*****_:
原则：
1.「因事择人」：是指根据岗位的要求来选拔具备相应知识与能力
的人员
2.「因才适用」：根据人的不同特点来安排工作，使人的潜能得到
最充分的发挥，忌”大材小用“或”小材大用“
3.「动态平衡」：要以发展的眼光看待人与事的配合关系，不断
调整，实现人与工作的平衡。组织变化 -》人员调整
人能力提高 -》不同岗位
;

*** 人员配备管理
**** 识记
*****_:
管理人员招聘的标准：
1.与组织文化相适应：个人与组织价值观契合
2.德才兼备：正品、次品、废品、毒品
3.决策能力：组织权利下移
4.沟通与合作的技能：沟通是合作的基本要求
5.创新精神：特别是高层管理人员
;
*****_:
「外部招聘」及优缺点：
优点：
1. 来源广泛，选择余地大，易于招到一流人才
2. 来自外部的候选人能够为组织带来新思想、新观念、新方法
3. 可以平息或缓和内部竞争者之间的矛盾
4. 人才现成，可节省培训费用
缺点：
1. 进入角色慢、缺乏人事基础
2. 对求职者无法深入了解
3. 影响内部员工的工作积极性
4. 外聘人员缺乏对企业的忠诚
;
*****_:
「内部提升」的优缺点：
优点：
1. 了解全面、准确性高
2. 可鼓舞士气、激励员工、增强员工对组织的忠诚
3. 有利于迅速开展工作
4. 使组织培训投资得到回报
5. 招聘费用低
缺点：
1. 来源局限、水平有限
2. 近亲繁殖
3. 内部竞争、引起同事不满
;
*****_:
「甄选」的概念：是指综合利用心理学、管理学等学科的理论、方法和技术，对应聘者
的任职资格、工作胜任程度等进行测量和评价到录用的过程
;
*****_:
「培训」的目标：
1. 掌握新的知识和技能
2. 发展各方面的能力
3. 形成统一的价值观
4. 增强员工之间的信息交流
;
*****_:
培训的方式：「岗前培训」、「在职培训」、「脱产培训」
1. 岗前培训：使员工学习和掌握基本的工作方法和程序，
帮助员工建立工作中的合作关系，使员工尽快调整自我，
尽早适应工作环境
2. 在职培训：与工作直接相联系，受训者置身于实际
工作之中，边学习、边工作、边提高，简单易行，节省
费用。工作轮换和实习是两种常见的在职培训。设置
助理职务和临时职务代理
3. 脱产培训：离职培训、脱岗培训，比较系统、正规、
有深度，培训效果好，尤其适用于管理领域和专业领域
的培训。缺点：会在短期内影响工作、培训成本也较高。
脱产培训的方法：课堂讲授法、视听教学法和模拟演练
法。
;
*****_:
「绩效考核」的概念：指组织定期测量、评估和检验个人或群体小组织的工作
及业绩的一种正式制度
;
**** 领会
*****_:
「招聘」的程序：
1.招聘计划阶段：将岗位空缺相关候选人数量和类型具体化
2.寻求候选人：自荐、引荐、毕业生、招聘广告、职介所、猎头公司
3.候选人甄选：”工作说明书“是甄选的依据
4.选定录用
5.检查评估：对招聘活动检查评估，不断修正、改进
;
*****_:
甄选的方法：
1. 申请表分析
2. 资格审查
3. 测试、面试及情景模拟
;
*****_:
甄选的程序：
1. 初选
2. 笔试
3. 面试：结构化面试、非结构化面试、混合式面试
;
*****_:
绩效考核的意义：
1.为「决策」提供了重要的参考依据
2.为「组织发展」提供了重要的支持
3.为确定员工的「工作报酬」提供依据
4.为「人事调整」提供了依据
5.为「培训」提供了依据
;
*****_:
绩效考核程序：
1.确定绩效考核目标并确定考评内容
2.确定考评责任者
3.评价业绩
4.考评结果的反馈和备案
;
*****_:
绩效考核方法：
1.个人自我评价法
2.小组评议法
3.工作标准法
4.业绩表评估法
5.排列评估法
现代绩效考核多采用目标管理法。
常用的多人评估系统：360度反馈。
;

** 组织变革
*** 概述
**** 识记
*****_:
「组织变革」：指组织根据内外环境的变化而进行的调整、改革和
适应的过程。目的是提高组织的效能
;
*****_:
组织变革的方式：
1.渐进式变革：逐渐的修正和改正，改革阻力小
2.激进式变革：快速抛弃传统习惯做法，彻底改变局面，
改革幅度大，阻力大
;
*****_:
组织变革内容：
1.「人员」变革：工作态度、期望、认知和行为，重点是组织
成员间在权利与利益等资源的重新分配
2.「结构」变革：组织设计、权利分配、分工与协调等
3.「技术」变革：设备、工具、技术、工艺和方法等
4.「组织文化」变革：核心是确立新的价值观取代旧的价值观、
往往难度最大时间最长
;
**** 领会
*****_:
组织变革动因：
1.外部动因
1） 宏观社会经济环境的变化
2） 科技进步的影响
3） 环境资源的影响
4） 竞争观念的改变
5） 全球化
2.内部动因：
1） 战略的调整
2） 设备引进与技术的变化
3） 员工受教育程度的提高
4） 组织规模和范围扩大，原来的
组织结构变得不适应
;
*****_:
组织变革目的：
1.使「组织」更具「环境适应性」
2.使「管理者」更具环境适应性
3.使「员工」更具环境适应性
;
*** 组织变革的过程和阻力
**** 领会
*****_:
组织变革的过程：
库尔特*勒温（Kurt*Lewin）的「三阶段」模式:
1.「解冻」：对现有状态否定，打破旧习惯，与传统决裂，丢掉对过去的
留恋，营造必须变革的气氛。主要任务：发现变革动力、营造危机感
和变革气氛、描绘变革蓝图、明确目标方向、形成变革方案
2.「变革」：养成新习惯，进入新状态，实施具体的变革行动。这是实质性
阶段。通常分为试验和推广两阶段。主要任务：按拟定方案开展变革
行动，使组织从现有模式向目标模式转变
3.「再冻结」：巩固新习惯，强化变革的成果。目的：避免退化、反弹
;
*****_:
组织变革的阻力：是指反对、阻挠、对抗变革的制约力。阻力可能来源于个人或群体，
也可能来自组织内部或外部环境对于不确定型的恐惧、可能失去利益和权利的恐惧、
保守的组织文化、缺乏竞争的市场环境都影响变革
;
*****_:
应对阻力克服方法：
1.开诚布公地与员工沟通
2.让员工参与到变革当中
3.利用成功的变革模式
4.减少不确定型（减少谣言）
5.谈判（满足一些人的利益、必要的妥协）
;
*** 当代组织变革新措施
**** 领会
*****_:
「组织扁平化」、「柔性化」、「团队化」，「大企业内部“小企业化经营”」的变化：
;
*****_:
扁平化：减少行政管理层次，裁减冗余人员
成因：
1. 分权理念
2. 快速适应市场变化
3. 信息技术的发展应用
;
*****_:
柔性化： 组织结构可调整，对环境变化、战略调整的适应能力。
目标是减少组织变革的冲击和震荡
;
*****_:
协作团队化：技能互补、责任共担、统一组织、相互协作
;
*****_:
大企业内部的“小企业化经营”：有意识地学习和借鉴小企业的
经营方式，化整为零，组件小型、自主和创新的经营单元。把
小企业灵活的经营优势引入到大企业的经营机制中
;

@endmindmap
