@startmindmap

* 领导

** 领导
*** 概念
**** 识记
*****_:
领导：是一种影响力，是对人们施加影响的艺术或过程，从而使人们情愿地、热心地为实现
组织或群体的目标而努力
领导者：就是组织中发挥领导作用的人，对于正式组织来说，是指具有一名以上下属的各级
主管
;
*****_:
领导者影响力来源：
「正式权力」和「非正式权力」：
1.来源于组织赋予，称为职位权力或正式权力。包括：
1） 法定权：以组织职位高低为基础
2） 奖赏权：源于被领导者期望奖励的心理
3） 强制权：源于被领导者的恐惧
2.来自领导者个人，称为个人权力或非正式权力
1） 专长权：具有知识优势，受人尊敬，服从
2） 个人影响权：品行优秀、德高望重
两者关系：正式权力是实现组织目标的手段；非正式权力是取得正式权力的
客观基础，是加强正式权力的重要条件
;
*****_:
领导活动的基本要素和特征：
基本要素：
1.领导者：领导活动的主题，最关键要素
2.被领导者：下属或追随者，是领导者领导的基础
3.目标：领导行为必须有明确目的
基本特征：
1.权力：领导的核心是权力，尽职尽责之权
2.责任：责任是领导者权力的象征
3.服务：领导就是服务
领导活动就是权力、责任、服务三统一。「权力是手段，责任是内容，服务是核心」
;
**** 领会
*****_:
领导的作用：
1.协调：消除分歧，协调关系和活动
2.指挥：指明组织活动目标和实现途径
3.激励：调动员工积极性
;
*****_:
领导与管理的区别：
1.从「本质」上，管理是建立在合法的、有报酬的和强制性
权力基础上对下属命令的行为。而领导可能建立在合法
的、有报酬的和强制性权力的基础上，但更多是建立在
个人影响力、专长以及模范作用等基础之上
2.从「功能特性」上，管理强调计划、组织、控制和解决问
题，是整合各种资源，借助各种手段来达到既定目标。
而领导强调提供方向、影响人和组织的凝聚力，以及
激励和鼓励人，通常关注意义和价值以及所要达到的
目标是否正确，是否值得
3.从「作用」上，管理比较注重细节、手段、技术、过程，
追求条例、程序和规范性。领导关注人，关注人的尊严
价值、潜能、激励和发展，侧重人文和目的、结果和艺术
追求创新、变革和突破
;

*** 领导理论
**** 应用
*****[#lightblue]:
「领导特质理论」：
侧重于研究领导人的心理、性格、知识、能力等特征，试图探讨
一种有效的领导者标准。即从优秀的人身上寻找共同的东西
包括：
1.斯托格迪尔的领导个人因素论
2.吉普的天才领导者特点论
3.鲍莫尔的领导品质论
4.吉赛利的领导品质论
领导特质：
1.努力进取，渴望成功
2.强烈的权力欲望
3.正直诚信，言行一致
4.充满自信
5.追求知识与信息

权力欲与自信心强的人，倾向于集权
正直诚信，渴望成功的人，倾向于事务型领导风格
知识与信息特强的人，倾向于战略思维
;
*****[#lightblue]:
「人性假设理论」：
强调领导行为与管理方式是建立在对人性不同认知的基础上
（一）「人性的四种假设」：经济人、社会人、自我实现人、复杂人
1.经济人假设：最早由亚当斯密在《国富论》中描述，泰勒进一步
落实，即”胡萝卜加大棒“的管理方法。人由经济诱发工作动机，人
的情感缺乏理性、不能克制自己。会干预人对经济利益的合理要求
2.社会人假设：由梅奥在”霍桑试验”中提出，影响人生产积极性的
因素，除物质外，还有社会、心理因素，士气、人际关系，家庭和
社会生活
3.自我实现假设：由马斯洛在“需要层次论”中最早提出，认为人一
般是勤奋的，能够自我激励和自我管理，要求进步，强调创造良好
工作环境，把人作为宝贵资源，使员工能力充分发挥
4.复杂人假设：认为人是很复杂的，需求多样，且不断变化，强调
管理者要能够鉴别情景、分析差异、诊断问题
（二）「X理论与Y理论」：美国心理学家麦格雷戈与20世纪60年代提出
1.X理论的假设：认为人们有消极的工作源动力
1） 懒惰       2） 不关心集体     3） 缺少进取心
持X理论的管理者会趋向于设定严格的规章制度，以减少员工消极性
2.Y理论的假设：认为人们有积极的工作源动力
1） 人有上进心   2） 愿意接受工作    3）能自我调节和监督
4） 具有相当高的创新能力    5）人的才智并未充分发挥
持Y理论的管理者会趋向于对员工授予更大的权力，让员工有更大
的发挥机会，以激发员工对工作的积极性
（三）「超Y理论」：基于“复杂人”假设
1.人的需要多种多样，且不断变化
2.同一时间内有各种需要和动机
3.随着发展不断产生新的需要和动机
4.不同部门或单位产生不同的需要
5.对不同的管理方式有不同的反应
要求管理者观察员工的个别差异，具体分析，因人而异采取灵活
多变的管理方法
;
*****[#lightblue]:
「领导方式理论」：
领导者在行使权力过程中的领导行为方式或领导作风，直接
影响领导的有效性
1.勒温的三种基本领导风格
1） 独裁式领导：权力定位于领导者个人手中
2） 民主式领导：权力定位于群体
3） 放任式领导：权力定位于每个职工手中
2.领导方式的连续统一体理论：1958年坦南鲍姆和施密特
《哈佛商业评论》：从经理的自由领域到下属的自由领域
之间列举了七种代表性模式（独裁到民主）
3.密执安大学的双中心论：探寻群体效率与领导者行为的关系
领导行为划分为员工导向和生产导向两个维度。前者重视人际
关系，关心下属；后者强调技术，关心任务的完成情况，视
成员为达到目标的工具。研究发现：员工导向的领导者与高
群体生产率和高工作满意度呈正相关。而生产导向的领导者
则与低群体生产率和低工作满意度联系在一起
4.俄亥俄州立大学四分图理论：试图找出领导的有效性与哪些
行为因素有关。“抓组织”和“关系人”两种倾向，前者以工作
为中心，后者以人际关系为中心。双高的领导者能使下属取得
高工作绩效和高满意度，常规性工作除外
5.『管理方格理论』（九九方格）*****几乎年年考*****
在四分图基础上，罗伯特*布莱克和简*莫顿于1964年提出
1.1型：贫乏型领导方式
9.1型：任务型领导方式
1.9型：俱乐部型领导方式
5.5型：中间型领导方式
9.9型：团队型管理或战斗集体型管理
认为9.9型是最有效的领导方式，领导者应客观分析组织内外
情况，以及自己的领导方式，尽力转化为9.9型，以求最高
效率
;
*****[#lightblue]:
「领导权变理论」：
领导方式要针对 领导者、被领导者机器环境因素不同而
有所变化，不能用固定方式管理，也称为领导情景理论
1.菲德勒模式
1） 以工作为中心的领导者，在对领导者非常有利或非常
不利的组织环境中，能取得最好的成绩
2） 以人际关系为中心的领导者，在中等有利程度的组织
环境中，能取得最好的成绩
三个工作环境因素影响领导风格的有效性：上下级关系、
工作结构、职位权力
2.领导生命周期理论
把下属成熟度作为一项重要情景变量，认为领导有效性
由工作行为、关系行为和下属的成熟度三因素决定
成熟度：职工对成就的要求、承担责任的意愿、工作的
熟练程度和自我控制能力
    1.高工作、低关系：命令型，适用于成熟度低的下属（M1)，
    采用单向沟通方式，明确任务和规程
    2.高工作、高关系：说服型，适用于较不成熟的下属（M2)，
    采用双向沟通信息的方式，增强意愿，加强自我控制
    3.低工作、高关系：参与型，适用于比较成熟的下属（M3)，
    不乐意接受过多的指示和约束，采用双向沟通和悉心倾听
    的方式，支持下属发挥才能
    4.低工作、低关系：授权型，适用于高成熟度的下属（M4)，
    有承担工作责任的能力、意愿和自信心，领导只需监督、
    授权下属，自行决定
;

*** 领导艺术
**** 应用
*****[#lightblue]:
分析各种领导艺术：
「提高工作效率的艺术」、「知人善任的艺术」、
「授权的艺术」、「协调人际关系的艺术」
;
*****[#lightblue]:
1.提高工作效率的艺术
1） 恪守职责，恪尽其能，凡事不能包揽：不干预下一层次的事，
不颠倒工作主次
2） 任何工作都要问三个能不能：能不能取消它，能不能与别的
工作合并，能不能用简便的东西替代
3） 总结经验教训
4） 善于运筹时间，要事先办
;
*****[#lightblue]:
2.知人善任的艺术
1） 知人：首先明确知人的原则（全面、历史、发展地、在实践中、在
关键时刻看人）；其次掌握知人的基本技巧和方法；最后，识才要有
慧眼，善于发现人才
2） 用人：明确用人原则（德才兼备、量才任职、授权、晋升）；掌握
用人的技巧与艺术（扬长避短，用其所长；用人不疑，疑人不用；
五湖四海，宽以待人；提携新人，用当其时）；用人的禁忌（任人唯亲
、对人才求全责备、武大郎的“心态”、在人才使用上要注意合理搭配，
切记伏龙凤雏一把抓）
;
*****[#lightblue]:
3.授权的艺术
1） 因事择人，视能授权（根本准则）
2） 权责同授，交代明确
3） 逐级授权，不授权力之外的权
4） 授权要有度
5） 授权形式要合理
6） 授权后要放手
7） 要掌握有效的控制方法
;
*****[#lightblue]:
4.协调人际关系的艺术
1） 正确处理上下级关系：具有相互协作、支持、竞争、选择、地方
等关系特征，上级关系：需要关怀和培养；下级关系：调动积极性
2） 正确处理同级的关系：目标一致、地位平等、频繁接触、相互依存
3） 正确处理领导者与群众的关系：员工认同、下级追随是领导
成功的关键
;

** 激励
*** 概述
**** 识记
*****_:
概念：激励是指激发人的需要与动机，引导行为指向目标的活动过程。
简单而言就是调动人的积极性的过程
;
*****_:
激励过程：
;
**** 领会
*****_:
激励目的和作用：
;
*** 理论
**** 应用
*****_:
需要层次理论：
;
*****_:
双因素理论：
;
*****_:
成就需要理论：
;
*****_:
期望理论：
;
*****_:
公平理论：
;
*****_:
强化理论：
;
*****_:
归因理论：
;
*** 原则和方法
**** 应用
*****[#lightblue]:
激励的原则与激励的方法在管理实践的应用：
;

** 沟通
*** 概述
**** 识记
*****_:
概念：沟通是人与人之间进行信息交流的活动
;
*****_:
要素：
1. 信源：信息发送者
2. 信息内容：沟通的内容
3. 信宿：信息接收者
4. 信道：信息交流渠道
;
*****_:
特点：
1. 心理因素对沟通的影响很大
2. 沟通既是信息传递过程，又是情感交流过程
3. 沟通主要以语言为载体：口头、书面、肢体
4. 在人际沟通过程中会出现沟通障碍：渠道和心理
;
**** 领会
*****_:
必要性：
从管理角度讲，沟通是为了完成设定的目标，把信息、思想和情感在个人
或群体间传递，并达成共同协议的过程。即通过沟通，使组织成员对组织
的任务与目标获得了解并最终达成共识
1. 上下级信息、政令畅通
2. 组织部门间能协调配合
3. 个人间能了解合作
4. 便于组织了解顾客需求及市场变化
;
*****_:
作用：
1. 沟通是保证决策科学的基本前提：决策依靠既是、完整、准确的信息
2. 沟通是改善人际关系的基本手段：良好畅通沟通渠道能提高组织凝聚力
3. 沟通是改变员工行为的重要方法：良好的上传下达能获得员工的理解和支持
4. 沟通是适应外部环境的重要途径：沟通可以从外部获取生存、发展所需信息
;
*****_:
原则：
1. 尊重原则
2. 相容原则
3. 理解原则
;
*****_:
过程：
1. 信息的发出
2. 信息的传递
3. 信息的接收
4. 信息的反馈
5. 噪音：已切干扰因素
;
*** 基本类型
**** 领会
*****_:
语言沟通和非语言沟通：
语言沟通：
1. 口头沟通：交谈、讲座、电话
2. 书面沟通：文件、报告、期刊
3. 电子媒介沟通：图标、图像、声音
非语言沟通：
通过身体动作、体态、语气语调、表情、
空间距离等方式交流信息，进行沟通
;
*****_:
正式沟通和非正式沟通：
正式沟通：
按照组织设计中事先规定好的结构和系统信息的路径、方向、媒体
等进行信息沟通，如组织之间的信函来往、文件、召开会议、上
下级之间的定期情报交换以及组织正式颁布的法令、规章、公告等
优点：正规、严肃、富有权威性、容易保持沟通信息的准确性及保
密性。缺点：对组织机构的依赖性较强，缺乏灵活性，沟通形式刻板
，信息传播范围受限，传播速度慢
非正式沟通：
是指正式组织途径以外的沟通方式（小道消息）。主要传播员工所
关心的信息。优点：速度快、形式多样、效率高、满足员工社会需要
。缺点：难控制，容易失真，影响凝聚力和人心稳定
;
*****_:
下行沟通、上行沟通和平行沟通：
下行沟通：自上而下的沟通，常见形式：工作指令、命令、谈话
、会议纪要、广播、年度报告、政策陈述、程序、手册和公司出
版物等。
上行沟通：自下而上的沟通，常见形式：设置意见箱、汇报会、
接待日、信访制等。
平行沟通：同级和部门间，优点：使办事程序和手续简化，节省
时间，提高工作效率。是组织各个部门之间相互了解，有助于培养
整体观念和合作精神，客服本位主义倾向、增加职工之间的互谅
互让，培养友谊，满足成员的社会需要，使成员提高工作兴趣，改
善工作态度。
缺点：头绪过多、信息量大、易于造成混乱；也有可能成为职工
发牢骚、传播小道消息的途径，造成涣散组织士气的消极影响。
;
*****_:
单向沟通和双向沟通：
单向沟通：指没有信息反馈的沟通，适合情形：1 问题简单，时间紧；
2 下属易于接受的方法；3 下属没有解决问题的足够信息；4 上级缺乏
处理反馈意见的能力
双向沟通：指有反馈的沟通，即信息发送者和接收者之间相互进行交流
的沟通。特点：耗时长，准确性高，噪声大。适合情形：1 时间多，问题
难；2 下属对方案接受程度重要；3 下属能提供有价值的信息和建议； 4
上级习惯双向沟通，能建设性处理意见。
;
*****_:
沟通网络： 指一群人建立和保持联系，以便相互沟通的一种形式。
一般有五种形态：「链式」、「轮式」、「Y式」、「环式」、「全通道式」
;
*****_:
链式：又称直线型沟通，指若干沟通参与者，从最初的
发信者到最终的收信者，环环衔接，形成信息沟通的
链条，属于控制型结构。优点：传递信息速度快，解决
简单问题的时效最高。缺点：信息容易失真；平均满意度
有较大的差距；沟通面狭窄，不易形成群体意见。
;
*****_:
轮式：又称辐射型沟通，指信息经由中心人物面向周围
多线传递，属于控制型沟通网络，只有一个成员是各种
信息的汇集点和沟通中心。优点：集中化程度高，解决
问题速度快；解决问题精度高；处于中心地位的人满足
程度较高。缺点：沟通渠道少；平行沟通不足，不利于
提高士气；成员评价满足度低，易滋生专制交流网络。
;
*****_:
Y式：是一个纵向沟通网络，实际上是链式、轮式的结合。
其速度、满意度、失真度介于两者之间，中心的人员
拥有信息且具有权威和满足感。优点：网络集中化程度
高，较有组织性，信息传递速度快，组织控制较严格
;
*****_:
环式：类似闭合的链式沟通，属于封闭式控制结构。优点
：组织内民主气氛较浓，团体的成员具有一定的满意度，
有助创造士气。缺点：集中化程度低，信息速度和准确
度难以保证，信息易于分散，难以形成中心。
;
*****_:
全通道式沟通：全方位开放式的网络系统，沟通渠道多，
高度分散，组织内每个成员都能同其他成员交流，没有
限制，成员平等、发表意见自由。优点：成员平均满意度
高，士气高昂；沟通渠道开阔，弥补了环式难于迅速集中
信息的缺陷。缺点：渠道太多容易混乱，沟通路线的数目
会限制信息的接收和传出能力，信息传递费时、影响
工作效率，不适用较大组织
;
*** 障碍与克服
**** 领会
*****_:
沟通障碍：沟通障碍是指信息在交换过程中，由于信息的意图收到干扰或误解，
而导致沟通失真的现象。
1. 信息沟通过程中的障碍：是指信息从发送者到接收者传递过程中
遇到的种种干扰和问题。
1） 发送者障碍：过滤：有意操纵信息，使对接收者有利；错觉：
歪曲的直觉；语言障碍：表达不当、词不达意等
2） 信息传递过程障碍：渠道或媒介不当；时机不当
3） 接收者障碍：选择性知觉障碍；情绪障碍；信息过量障碍
4） 反馈过程障碍：反馈渠道或过程信息失真
2. 沟通环境方面障碍：
1） 组织结构障碍：不合理的组织结构不利于沟通
2） 组织文化障碍：独裁和缺乏沟通场所都不利于沟通
3） 社会环境方面障碍：不同文化背景和跨文化组织沟通不同
;
*****_:
沟通障碍克服：
1. 沟通要有认真的准备和明确的目的：对内容正确、清晰理解；
目的统一思想协调行动
2. 沟通内容要确切：言之有物，避免空话、套话
3. 沟通要有诚意：一般自下向上沟通较缺乏诚意（经理）
4. 沟通方式要适合：当面沟通、口头沟通、双向沟通效果较理想
5. 沟通渠道要拓宽：缩短信息传递链；保障双向沟通
;

@endmindmap