@startmindmap

* 战略实施与控制

** 企业经营战略的实施与控制

*** 企业经营战略的实施
**** 识记
*****_:
企业经营战略实施的含义：
;
*****_:
企业经营战略实施的原则：
;
*****_:
指令型方式：
;
*****_:
变革型方式：
;
*****_:
合作型方式：
;
*****_:
文化型方式：
;
*****_:
增长型方式：
;
*****_:
时间分解：
;
*****_:
空间分解：
;
**** 领会
*****_:
经营战略与组织结构的关系：
;
*****_:
企业发展阶段与经营战略：
;
*****_:
企业战略态势与组织结构：
;
*****_:
企业领域与组织结构：
;
*****_:
企业经营战略实施的方式：
;
*****_:
滚动计划法：
;
*****_:
战略领导群体的结构构成：
;
*****_:
战略领导群体组件的原则：
;
**** 简单应用
*****_:
依据不同经营战略对不同组织结构类型进行选择：
;
*****_:
结合案例资料对企业组件战略领导群体的原则进行分析：
;
*****_:
结合企业实践对其战略领导群体结构进行分析：
;
**** 综合应用
*****[#lightblue]:
能对企业经营战略实施过程的原则、方式和重点工作进行综合分析：
;

*** 企业经营战略的控制
**** 识记
*****_:
企业经营战略控制的含义：
;
*****_:
企业经营战略控制的对象：
;
*****_:
企业经营战略控制的层次：
;
*****_:
前馈控制：
;
*****_:
现场控制：
;
*****_:
反馈控制：
;
*****_:
直接控制：
;
*****_:
间接控制：
;
**** 领会
*****_:
必要性：
;
*****_:
控制的对象：
;
*****_:
重点控制的原则：
;
*****_:
经济合理原则：
;
*****_:
企业经营战略控制基本方式的选择：
;
**** 简单应用
*****_:
结合企业实践队经营战略控制对象与基本要素进行分析：
;
*****_:
对企业经营战略控制原则的实践应用进行分析：
;
**** 综合应用

@endmindmap