@startmindmap

* 计划
** 决策

*** 概述
**** 识记
*****_:
概念：组织为了实现某一特定目标，从两个以上的可行方案中，选择一个最优的并组织实施的全过程
;
*****_:
类型：
1. 按「性质」不同：「战略」决策、「战术」决策、「业务」决策
2. 按「表现形式」不同：「程序化」决策（常规的、重复的、例行性的）、「非程序化」决策（不重复发生无先例可循的决策）
3. 按「决策方法」不同：「确定型」决策（一个方案只有一个结果）、「风险型」决策（一个方案可能有不同结果）、「不确定型」决策（不同结果概率不确定）
4. 按「决策主体」不同：「个人」决策、「群体」决策
;
**** 领会
*****_:
地位和作用：
    - 决策理论学派西蒙认为：“管理就是决策”
    - 决策是管理的核心内容，贯穿于管理活动的全过程
    - 决策正确与否，是管理成败的关键
    - 中国失败企业家80%在于投资失败，这源于决策失败，表现为：决策
      的独断和无制约、决策的随意性、一夜暴富的投机性
    - 正确的决策成为我国企业必须解决的一大问题
;

*** 原则、标准与影响因素
**** 识记
*****_:
原则：
    - 信息原则：信息是决策的物质基础
    - 预测原则：科学预测，避免误判
    - 可行性原则：综合考虑利弊，保证决策可行性
    - 系统原则：统筹兼顾，平衡发展
    - 对比择优原则：选择最佳方案
    - 反馈原则：实践检验决策
;
*****_:
标准：
1. 泰勒提出的“最优标准”：追求最佳
2. 西蒙提出的“满意标准”：通常难以做出最优，只能相对满意
3. 哈罗德*孔茨“合理性标准”：以符合目的为根本标准，强调各决策阶段的效果与工作质量
;
**** 领会
*****_:
影响因素：
    - 环境因素：推动决策和制约决策
    - 组织文化：团结、和谐、平等的组织文化会鼓励人们积极参与组织决策
    - 决策的个人因素：决策能力以及对待风险的态度是决策成功的关键
    - 时间因素：时间敏感型决策对速度要求高于质量
    - 过去的决策：有利于决策连贯性和维持组织稳定性，但不利于创新
;

*** 程序与方法
**** 领会
*****_:
决策的程序：
1.识别机会或诊断问题：决策的起点
2.确定目标：决策的前提
3.拟定可行方案：决策的基础
4.方案选优：决策的关键点
5.典型试验：决策试点
6.普遍实施：决策的落实
7.跟踪控制：决策的检查
;
**** 应用
*****[#lightblue]:
运用决策的方法：
1. 「定性决策法」
    依靠决策者的直觉、经验和主观判断，也称软决策
    优点：方便易用，适用于非程序化决策
    缺点：缺乏论证，主观性强
    1.「头脑风暴法」：集体决策，鼓励创新思维
    2.「名义群体法」：名义小组法，集体决策
    3.「德尔菲法」：专家意见法，特点：匿名性、反馈性和统计性
    4.「电子会议」：人机结合决策，优点：匿名、诚实和高效
2. 「定量决策法」
    1.确定型决策方法：最理想的决策状态
        「盈亏平衡分析法」（量本利分析法或保本分析法）
        「内部投资回收率法」
        「价值分析法」
    2.风险型决策方法：目标大多数是经济的，可以用货币衡量的
        决策依据的标准：净收益最大化或净损失最小化
        风险型决策方法，一般有收益表法、边际分析法、决策树法和效用理论法
        决策树最常用：方形表示决策点，圆形表示方案节点，三角表示结果点
        『决策树』步骤：1.画决策树；2.计算期望值；3.剪枝确定最优方案
    3.不确定型决策
        「悲观决策法」：华德准则，小中取大
        「乐观决策法」：赫威斯准则，大中取大
        「折中决策法」：折中后取大
        「最大最小后悔值法」：机会损失最小值决策，大中取小
        「同等概率法」：机会均等法，概率相同分别计算收益值取大
;

** 计划

*** 概述
**** 识记
*****_:
概念：计划是明确管理的总体目标和各分支目标，并围绕这些目标对未来活动
的具体行动任务、行动路线、行动方式、行动规则等进行规划、选择 筹谋的活动
;
*****_:
特点：
1.目的性，计划为了有效达到目的
2.首位性，是其他职能的前提和基础
3.普遍性，各级各类管理者都需计划（重要）
4.适应性，具有灵活性，适应环境变化
5.经济性，最小成本获得最大产出
;
*****_:
计划的内容 5W1H：
    - 做什么（what）
    - 为什么做（why）
    - 何时做（when）
    - 何地做（where）
    - 何人做（who）
    - 如何做（how）
;
*****_:
分类：
1. 按计划形式
    1.宗旨，组织是干什么的
    2.目标，组织及部门在一定时期内要达到的具体成果
    3.战略，为实现组织目标的长远目标而采取的总计划
    4.政策，组织对成员做出决策或处理问题应遵循的行动方针的一般规定
    5.程序，具体问题应该按照怎样的时间顺序处理
    6.规则，执行程序中每一步应遵循的原则和规章
    7.规划，为了实施既定方针而制定的综合性计划
    8.预算，是以数字表示预期结果的一种报告书
2. 按计划期限
    1.长期计划，5年以上纲领性轮廓性的计划
    2.中期计划，衔接长短计划的作用
    3.短期计划，1年以内，年度计划 
3. 按计划性质
    1.战略计划，总体、周期长、涉及面广、有较大弹性
    2.战术计划，服从、实行战略计划而制定的计划，解决实际问题，时间短
;
**** 领会
*****_:
作用：
1.有利于明确工作目标，提高工作效率
2.有利于增强管理的预见性，规避风险
3.有利于减少浪费，取得最佳经济效益
4.有利于控制工作的开展
;
**** 应用
*****[#lightblue]:
联系实际分析计划制定程序：
1.评估「机会」
2.确定「目标」
3.确定「前提条件」
4.拟定可供选择的「方案」
5.评价各种「备选方案」
6.「选择方案」
7.拟定辅助「计划」
8.编制「预算」
;
*****[#lightblue]:
计划工作原理在实际中的应用：
1. 「限定因素原理」（又称木桶原理）：限定因素是指妨碍目标得以实现的因素。
在其他因素不变的情况下，抓住限定因素，就能实现期望目标
2. 「许诺原理」：任何一项计划都是对完成某项工作所做的许诺。
许诺越大，所需时间就越长，实现目标的可能性就越小。计划必须有期限要求
3. 『灵活性原理』：计划工作必须具有灵活性，当出现意外情况时，有能力改变
方向而不必花费太大代价。使计划有「适应性」，“量力而行，留有余地”
4. 「改变航道原理」：计划总目标不变，但实现目标的进程（即航道）可以
因情况的变化随时改变。要定期检查计划，一旦情况
发生变化，就要调整计划或重新制定计划。灵活性原理
是计划本身有适应性，改变航道原理是使计划的执行
过程具有应变能力
;

*** 战略计划
**** 识记
*****_:
愿景：对组织未来发展方向和目标的构想和设想，对未来展望和憧憬
使命：组织存在的理由和价值，使命的三个特点：长期性、指导性、激励性
;
**** 领会
*****_:
重要性：由于组织赖以生存的环境多变，依靠传统计划方法制定未来计划已经不合时宜，
需要审时度势、高瞻远瞩对外部环境变化做出预测和判断，规划发展目标
;
*****_:
与长期计划的区别：
1. 战略计划是一种可以改变组织性质的重点计划
2. 战略计划的制定通常由少数高层领导参与
3. 战略计划着眼点是外部环境的改变
;
*****_:
企业的基本战略：
1. 总成本领先战略
2. 差别化战略
3. 集中战略
;

*** 计划的方法与技术
**** 识记
*****_:
目标管理：是由组织的员工共同参与制定具体的、可行的且能客观衡量效果的目标，
在工作中自我控制，努力实现目标
;
*****_:
目标管理的特点：
1. 员工参与管理：员工参与上下级共同决定
2. 以自我管理为中心：通过自我监督和衡量，修正自己的行为
3. 强调自我评价：经常自我检查
4. 重视成果
;
*****_:
滚动计划法及其特点：滚动计划法是一种修订未来计划的方法，按照计划的执行情况和环境变化，
调整和修订未来计划，并逐期向前移动。特点是：「分段编制，近细远粗」、「长、短期计划紧密结合」
优点：各阶段和下一时期「有机衔接」，更符合实际；较好解决了「计划稳定」和「实际多变」
;
*****_:
甘特图及特点：也称条状图，以图示方式通过「活动列表」和「时间刻度」表示活动顺序和持续时间。
特点：简单、醒目和便于编制
;
**** 领会
*****_:
目标管理的理论基础：是人本主义与效率主义二者的结合，在专业化与人性化的原则下产生了许多管理思想，
其中引人注目的管理思想是「授权」，为了实施授权，才有了目标管理
;
**** 应用
*****[#lightblue]:
联系实际分析目标管理方法的应用：
实施目标管理，要从「建立目标」开始，经过「目标分解」、「目标考核」和「成果评价」。
1. 确定目标是根据外部环境和内部条件确定在一定时期要取得的成果；
2. 目标展开包括：目标分解、目标对策、目标责任
3. 目标实施阶段组织要按照目标要求同心协力、分工协作
4. 最后对目标成果做出客观评价
;


@endmindmap