@startmindmap

* 总论
** 企业经营战略概述

*** 企业经营战略简介
**** 识记
*****_:
<&flag>企业经营战略概念：
指企业在竞争更激烈、复杂多变的环境下，为谋求生存和发展而做出
「总体」性、「长远」性的「谋划和方略」
实质是在于寻求变革和创新，创造性经营，适应当前和未来环境需求，
获得生存和长久发展
;
*****_:
<&flag>企业经营战略特征：
1. 「全局性」：总体发展、整体功能、总体效果
2. 「长远性」：3-5年、10年、分阶段
3. 「竞合性」：竞争与合作
4. 「纲领性」：长远目标、发展方向
5. 「应变性和相对稳定性」：非朝令夕改
;
**** 领会
*****_:
<&flag>产生的背景：
1.「需求」结构的重大变化
2.「市场竞争」日趋激烈
3.「科学技术」的不断进步
4.「资源供应」日益紧张
5.「生态环保」要求越来越高
6.「产业」结构的快速调整
;
*****_:
<&flag>作用：
1. 为企业的长期发展指明「方向」
2. 为企业顺利发展提供「保障」
3. 为企业管理增强「活力」
4. 为提高经营者「管理水平」提供可靠条件
;

*** 企业经营战略理论形成和发展
**** 识记
*****_:
「迈克尔波特」提出的「竞争五种力量」：
1. 现有竞争者；
2. 潜在加入者；
3. 替代品生产者；
4. 资源供应者；
5. 产品购买者
;
*****_:
企业核心能力和特点：
1. 能力：
战略管理、技术开发、生产制造、市场营销、组织管理等
2. 特点：
1) 延展性：延展到新产品开发、创造新市场
2) 增值性：增加顾客价值
3) 独特性：与众不同，不被轻易模仿、掌握
;
**** 领会
*****_:
「企业战略理论」的主要观点：(安索夫--战略管理的<b>鼻祖</b>)
1. 企业战略计划必须有「资源」、组织保障
2. 制定的战略必须与「环境」相适应
3. 企业经营战略「四要素」：「市场」范围、「成长」方向、「竞争」优势、「协同」作用
;
*****_:
迈克尔波特「竞争战略理论」主要观点：
1. 竞争因素「五力模型」：现有竞争者；潜在加入者；替代品生产者；
资源供应者；产品购买者
2. 制定竞争「三大战略」：总成本领先战略、差异化战略、集中化战略
3. 产品和行业有「寿命周期」
4. 企业要形成竞争优势，分析企业自身「价值链」
;
*****_:
普拉哈拉德和加里哈默尔(<b>二哈</b>)「<b>核心</b>能力战略」理论观点：
企业在长期的经营活动中形成了许多种能力，如战略管理、技术开发、生产制造、
市场营销、组织管理等，但「企业核心能力」是众多能力最根本的部分，企业核心能力
是以一个组织内部一系列互补的技能和知识的结合
;

*** 企业经营战略的管理体系
**** 识记
*****_:
企业经营战略管理的含义：
1. 狭义：企业家从战略的高度对企业的整个生产经营活动
所进行的管理，具体地说是指对企业经营战略的制定过程、
实施和控制和修正过程所进行的管理
2. 广义：是运用战略对整个企业进行管理
;
*****_:
企业经营战略管理体系的构成：
1. 经营战略管理过程体系：三阶段：（经营战略）分析阶段；制定、决策阶段；实施、反馈阶段
2. 经营战略层次体系：三层次：总体经营（战略）、经营单位、职能层经营
3. 经营战略方案的内容体系：多种、多层次方案的选择
;
**** 领会
*****_:
<&flag>企业经营战略的「层次体系」：
1.「公司」层
    对市场需求、竞争状况、资源供应、企业实力、国家政策、
社会需求等因素分析后，确定的统率和指导企业长远发展的
谋划和方略
竞争态势：发展型（战略）、稳定型、紧缩型
经营领域：专业化（经营战略）、多元化
主客观条件：保守型（战略）、可靠型、风险型
资源配置：粗放型（经营战略）、集约型
2.「业务」层
    公司二级经营单位的经营战略，包括：产品定位战略、
投资战略、竞争战略、合作战略等
3.「职能」层
    主要回答某职能部门如何卓有成效开展工作，主要包括：
市场营销、产品、财务、技术创新、人力资源、企业文化
;
**** 应用
*****[#lightblue]:
<&flag>企业经营战略管理过程「系统」：
1. 经营战略环境「分析」阶段
1）外部环境分析 2）内部环境分析 3）经营领域分析
2. 经营战略制定与决策阶段
制定：建立长期目标 1）企业愿景、使命、目标、地位 
2）总体战略、业务战略和职能「战略制定」
决策：确定方案
3. 经营战略「实施与反馈」阶段
1）实施前准备工作 2）实施和推进 3）控制与反馈
4）评价工作
;
*****[#lightblue]:
企业经营战略方案的内容体系：
1. 战略思想
2. 战略目标
3. 战略重点
4. 战略方针
5. 战略阶段
6. 战略决策
;

@endmindmap