@startmindmap

* 管理学原理
** 管理与管理学

*** 管理
**** 识记
*****_:
概念：组织为了更有效实现「组织目标」而对各种资源进行
「计划」、「组织」、「领导」、「控制」的一系列「协调」活动过程；
;
*****_:
特征：
1. 「管理活动」不同于「作业活动」：
	作业活动：为实现自身目的的活动；管理活动：保证作业活动的有效
	两项活动密切相关但区别明显：范围广、责任更大、本职活动（新管理者误区）
2. 具有科学性和艺术性：
	有规律、原则、原理、知识体系；需要创造、灵活、随机应变
3. 以人为本：需要处理好人际关系，尤其中国
;
*****_:
职能：
1. 管理过程中从事的活动；
2. 计划、组织、领导、控制：
	计划：对组织未来活动预先筹划安排
	组织：为完成计划对分工整体安排
	领导：指挥和影响下属为实现组织目标努力工作
	控制：保证按预定计划运转监督检查
3. 法约尔：计划、组织、指挥、协调、控制；
;
**** 领会
*****_:
产生：
1. 欲望无限性和资源的有限性之间的矛盾；
2. 人类群体活动的产物：「作业活动」和「管理活动」；
;
*****_:
有效性衡量：
管理是追求「有效」的过程
「有效」=「效率」+「效果」
「效率」= "做正确的事" = 「有效管理者」= 降低资源消耗
「效果」= "正确的做事" = 「成功管理者」= 提升目标达成度
;
**** 应用
*****[#lightblue]:
管理的必要性：
1. 管理是社会进步和发展的物质力量：美英对比，英比美低；日本成功因管理较好
2. 管理是组织生存发展的重要条件：彼得德鲁克"没有机构就没有管理，没有管理就没有机构"
3. 管理活动具有普遍性：任何组织（层次）都需要管理；管理基本原理对组织普遍适用
;

*** 管理者
**** 识记
*****_:
概念：组织中行使管理职能、通过「协调他人」的活动实现「组织目标」的人
;
*****_:
分类：
	-层次：「高层」、「中层」、「基层」
	-领域：「综合」、「专业」
;
*****_:
角色：（三类十种-亨利*明茨伯格）
	-人际关系：挂名首脑、领导者、联络者
	-信息：监听者、发言人、传播者
	-决策：企业家、混乱驾驭者、资源分配者、谈判者
;
**** 领会
*****_:
技能：
1. 技术技能（基层）：使用某一专业领域的程序、技术、知识和方法完成组织任务
2. 人际技能（中层）：处事能力，理解、激励他人并与他人共事
3. 概念技能（高层）：纵观全局、洞察企业与环境要素相互影响和作用
;
*****_:
管理四项活动（时间精力不同）：
1. 传统管理：决策、计划、控制
2. 沟通：交流理性信息和处理文书
3. 人力资源管理：激励、惩戒、调节冲突、人员配备、培训
4. 网络联系：社交活动、政治活动、外界交往
;
*****_:
效果：
1. 有效：工作数量多、质量好、下级满意度高；特点：沟通多，网络联系少
2. 成功：晋升快的管理者；特点：网络联系多，人力资源少
;

*** 管理学
**** 识记
*****_:
概念：
1. 是系统研究管理过程的普遍规律、基本原理和一般方法的科学；
2. 是千百年来人类管理经验智慧的高度概括总结；
3. 是人们学习管理的主要途径；
4. 泰勒《科学管理原理》问世标志管理作为科学诞生
;
*****_:
学习方法：唯物辩证法；理论联系实际法；系统方法
;
**** 领会
*****_:
特点：「综合性」、『不精确性』（多科性）、「实践性」、「历史性」、「发展性」
;

** 管理理论形成与发展

*** 前期管理实践和思想
**** 识记
*****_:
亚当斯密：
1. 提出「分工协作原理」和「生产合理化」概念；
2. 提出「经纪人」观点：人是自私的，追求个人利益
;

*** 管理理论形成
**** 识记
*****_:
古典管理理论特点：
1. 以提高生产率为目标；
2. 以科学求实态度进行调查研究；
3. 强调以个人为研究对象，重视个人积极性发挥；
4. 强调规章制度的作用
;
**** 领会
*****_:
「科学管理理论」：（泰勒-科学管理之父）
列宁评价：泰勒科学管理既是资产阶级剥削员工最巧妙、最残忍的手段，也是一系列最丰富的科学成就
6个观点：
1. 工作定额原理
2. 标准化原理
3. 科学挑选工人病使之成为"第一流工人"
4. 实行差别计件工资制
5. 管理工作专业化
6. 管理控制的例外原理
;
*****_:
「一般管理理论」：（法约尔-管理过程之父）
要点：
1. 对「经营」与「管理」的研究：经营是直到或引导一个组织去向某一既定目标的活动，「管理仅仅是经营的一项活动」
2. 管理五要素：计划、组织、指挥、协调、控制
3. 管理十四原则：分工、权力与责任、纪律、个人利益服从集体利益、统一指挥、报酬合理、集权与分权、
	秩序、等级链与跳板、公平、人员稳定、首创精神、集体精神
;
*****_:
「行政组织理论」：（韦伯）
1. 理想的组织形态的基础是「权力」：超凡权力、传统权力、法定权利
2. 管理制度
3. 组织结构
特点：
1. 明确的分工；
2. 自上而下的等级系统（权利等级链）；
3. 人员任用根据职务的要求；
4. 职业管理人员：上级任命、固定薪金、工作人员、升迁制度；
5. 遵守规则和纪律；
6. 组织中成员的关系为职业关系
;

*** 行为科学兴起
**** 领会
*****_:
霍桑实验：（梅奥）
1. 工人是「社会人」，而非单纯追求金钱收入的"经纪人"；
2. 生产率的高低主要取决于工人的态度，即「士气」；
3. 企业中存在「非正式组织」；
4. 新型领导能力就是要在「正式组织的经济需求」和「非正式组织的社会需求」间保持平衡
;
*****_:
行为科学建立发展：
1. 动机激励理论（核心）：需求层次论、双因素论、成就需要论
2. 企业管理中的"人性"理论（基础）：XY理论、不成熟-成熟理论、超Y理论
3. 领导方式理论：包括领导方式连续统一理论、支持关系理论
4. 组织与冲突理论：团体力学理论、意见沟通理论、敏感性训练
;
**** 应用
*****[#lightblue]:
行为科学理论在现代管理的运用
;

*** 现代管理理论丛林
**** 领会
*****_:
各管理学派特点：
1. 管理过程学派：（哈罗德孔茨）管理过程和「管理职能」密不可分
2. 社会系统学派：
    1) 组织是一种「协作系统」；
    2) 协作要素包括「协作的意愿」、「共同目标」、「信息联系」；
    3) 组织目标「效力」和个人目标「效率」
    4) 「正式组织」和「非正式组织」关系和相互作用
    5) 经理人职能：信息联系；组织成员服务；制定和规定目标
3. 决策理论学派：（西蒙）决策在管理中重要性
4. 系统管理学派：企业是一个人造的开放系统
4. 社会-技术系统学派：管理者应把「技术系统」（机器设备、采掘方法）和「社会系统」结合考虑
5. 经验主义学派：从企业管理分析成功和失败经验，传授给管理者
6. 权变理论学派：也称管理情景论，强调随机应变
7. 经理角色学派：（亨利*明茨伯格）强调经理担任的角色和提高经理工作效率
8. 管理科学学派：又称“数学学派”，认为管理就是用数学模型和程序表示，求出最优解
;

** 组织环境和组织文化

*** 组织环境
**** 识记
*****_:
概念：影响组织生成和发展的各种力量和条件因素的集合
;
*****_:
分类：
1. 外部环境
    1) 一般环境：宏观环境（大环境）、PEST 政治、经济、社会、技术
    2) 具体环境：特殊环境，波特五力
2. 内部环境
;
*****_:
特点：
1. 客观性
2. 复杂性
3. 关联性
4. 「不确定型」
5. 层次性
;
**** 领会
*****_:
「组织」与「环境」的关系：
1. 环境影响组织：
    环境是组织赖以生存的土壤；
    外部环境影响组织内部的各种管理工作；
    环境制约组织的管理过程和管理效率；
2. 组织影响环境：适应环境、改变自己；影响环境、选择新环境
;

*** 组织环境分析
**** 应用
*****[#lightblue]:
一般环境分析（PEST分析）：
1. 政治因素：国家制度、政治形势、国际关系、政治方针、国家法律
2. 经济因素：（宏观-国家）经济制度、经济结构、产业布局、经济发展；（微观-地区）消费者收入水平、消费偏好、储蓄、就业
3. 社会因素：人口规模、年龄结构、收入分布、文化传统、教育水平、消费结构、人口流动
4. 技术因素：新发明、新技术、新工艺、新材料
;
*****[#lightblue]:
具体环境分析（五力模型）：
1. 现有竞争者的抗衡：关注并分析研究竞争对手，识别机会挑战
2. 潜在进入者威胁：存在超额利润，设置进入壁垒
3. 替代品威胁：功能替代，性价比
4. 供应商议价能力：（表现）提价或降低质量；（对策）视为合作伙伴共赢
5. 购买者议价能力：（表现）压价或要求更高质量或比较企业使其相互竞争；（对策）产品特别、成本保密、力争垄断
;
*****[#lightblue]:
内部环境分析：
目的：掌握组织历史和目前现状，明确组织优势和劣势，扬长避短
内容：组织结构、组织文化、资源条件、价值链、核心能力
方法：
    纵向分析：组织各方面职能的历史演化，发现组织的优势劣势
    横向分析：将组织的情况和行业水平横向比较，发现对于行业的平均优势劣势
;
*****[#lightblue]:
SWOT分析：
含义：优势(Strengths)、劣势(Weaknesses)、机会(Opportunities)、威胁(Threats)
步骤：1、分析优势劣势 2、分析机会威胁 3、将内外组合形成可行的发展战略
组合：优势-机会(SO)、劣势-机会(WO)、优势-威胁(ST)、劣势-威胁(WT)
;

*** 组织文化
**** 识记
*****_:
概念：组织文化（企业文化）是一个组织的价值观、信念、仪式、符号、处事方式等组成的特有文化形象，
一个企业的动力及凝聚力都来自于企业文化，技术知识一个平台
;
*****_:
层次：
1. 理念层：核心和灵魂
2. 制度和行为层：规章制度和行为准则
3. 象征层：物质层，具体体现
;
*****_:
特征：
1. 客观性：有组织必然存在组织文化
2. 独特性：组织会形成各自独特的组织文化
3. 相对稳定性：长期积淀形成
4. 继承融合性：继承发展
5. 发展性：随着社会发展、环境变化逐步演进
;
**** 领会
*****_:
产生：孕育于日本，产生于美国
;
*****_:
发展：美国关礼杰对日本的管理思想反思和多角度比较研究，发明一系列著作，共同点：
1. 分析了西方管理的不足之处，忽视社会科学研究，忽视了人的感情因素
2. 肯定了企业文化在企业生存发展的关键作用
;
**** 应用
*****[#lightblue]:
功能：
1. 导向功能：软约束，引导全员朝目标前进
2. 凝聚功能：培养认同感和归属感，形成向心力
3. 激励功能：调动员工积极性
4. 调适功能：改变员工旧的价值观、建立新价值观
5. 辐射功能：组织文化具有学习性、分享性和传递性，向外辐射
;
*****[#lightblue]:
塑造途径：
1. 确立合适的「价值观标准」；
2. 选择与组织价值观相融的「应聘者」；
3. 强化「员工的认同感」；
4. 建立符合组织文化要求的「奖励」系统；
5. 不断「丰富和完善」组织文化
;

** 管理道德和社会责任

*** 管理道德概述
**** 识记
*****_:
概念：道德一般可分为「社会公德」、「家庭美德」、「职业道德」三类；
「职业道德」是同人们的职业活动紧密联系的符合职业特点所要求的道德准则、道德情操与道德品质的总和；
「管理道德」作为一种特殊的「职业道德」，是从事管理工作的管理者的行为准则与规范的总和，是特殊的
职业道德规范，是对管理者提出的道德要求；
;
*****_:
特征：
1. 普遍性：适用于各个领域管理
2. 特殊性：调整管理关系、规范管理行为
3. 非强制性：受舆论影响
4. 变动性：不断变化发展丰富
5. 社会教化性：管理者的道德示范和引导作用
;
**** 领会
*****_:
影响因素：
1. 道德发展阶段：
    前惯例层次：最低层次，受个人利益支配
    惯例层次：道德观受他人期望影响。为整体利益着想的事道德良性的，否则是恶性的
    原则层次：最高层次，个人道德原则。强调个性和个人英雄主义，充分施展和发展自我
2. 个人特征：
    自我强度：度量一个人的信念强度
    控制中心：度量人们在多大程度上是自己命运的主宰
3. 组织结构变量：模糊的组织结构和只看重结果的绩效评估都会影响管理者道德
4. 组织文化：组织文化的内容和强度影响道德行为
5. 问题强度：道德问题强度会直接影响管理者的决策。问题强度较大时，我们更期望管理者采取道德的行为
;
*****_:
培育途径：
1. 挑选道德素质高的管理者：至少是一个高道德标准律己的人
2. 做好管理道德教育工作：提高认识、培养情感、锻炼意志、鉴定信念、梳理典型
3. 提炼规范管理道德准则：形成标准，实行管理道德规范化管理
4. 管理道德列入岗位考核内容：加强检查、考核、奖惩
5. 提供正式的保护机制：不用担心斥责或报复行事
;

*** 社会责任
**** 识记
*****_:
含义：社会责任是指组织在遵循、维护和改善社会秩序、保护增加社会福利方面所承担的职责和义务
;
*****_:
两种不同的社会责任观：
1. 古典观（纯经济）：认为企业只应该对股东负责，企业只要是股东的利益得到满足，就是具有社会责任的表现
    该观点核心思想是企业管理者唯一的社会责任就是实现利润最大化，谋求最大投资回报
2. 社会经济观：认为企业除了要赚取合理利润以外，还应为相关利益群体承担起应该负担的社会责任
    必须以不污染、不歧视、不从事欺骗的广告宣传来保护社会福利
;
**** 领会
*****_:
「社会责任」与「经营业绩」：
企业社会责任与经营业绩之间的关系没有统一结论
大量实践表明：企业遵守严格的环境标准、从事环境公益事业，「短期内无疑会增加经营成本」，但「长期来看，责任与业绩是正相关」
企业履行社会责任有助于提高强企业绩效，梳理良好公众形象，获得更多外部支持，从而提高经济绩效
企业可以从以下方面着手：
1.员工：尊重员工话语权，为员工创造自由的工作环境
2.慈善、公益：参加力所能及公益、慈善活动，帮助困难群体
3.环境保护：生产中充分考虑社会责任，建立“绿色”、可持续发展
;
**** 应用
*****[#lightblue]:
具体体现：
1. 对「雇员」的责任：“以人为本”维护员工的合法权益，建立规范和谐稳定的劳动关系
2. 对「顾客」的责任：提供安全的产品、售后服务、必要指导和赋予顾客自主选择的权利
3. 对「竞争对手」的责任：不假冒其他企业的商标，不生产假冒伪劣产品
4. 对「环境」的责任：维护环境质量、使用清洁能源、共同应对气候变化和保护生物多样性
5. 对「社会发展」的责任：救助灾害、救济贫困、赞助教育、科学、文化、卫生
;

@endmindmap
