@startmindmap

* 管理学原理
** 管理与管理学

*** 管理
**** 识记
*****_:
概念：组织为了更有效实现「组织目标」而对各种资源进行
「计划」、「组织」、「领导」、「控制」的一系列「协调」活动过程；
;
*****_:
特征：
1. 「管理活动」不同于「作业活动」：
	作业活动：为实现自身目的的活动；管理活动：保证作业活动的有效
	两项活动密切相关但区别明显：范围广、责任更大、本职活动（新管理者误区）
2. 具有科学性和艺术性：
	有规律、原则、原理、知识体系；需要创造、灵活、随机应变
3. 以人为本：需要处理好人际关系，尤其中国
;
*****_:
职能：
1. 管理过程中从事的活动；
2. 计划、组织、领导、控制：
	计划：对组织未来活动预先筹划安排
	组织：为完成计划对分工整体安排
	领导：指挥和影响下属为实现组织目标努力工作
	控制：保证按预定计划运转监督检查
3. 法约尔：计划、组织、指挥、协调、控制；
;
**** 领会
*****_:
产生：
1. 欲望无限性和资源的有限性之间的矛盾；
2. 人类群体活动的产物：「作业活动」和「管理活动」；
;
*****_:
有效性衡量：
管理是追求「有效」的过程
「有效」=「效率」+「效果」
「效率」= "做正确的事" = 「有效管理者」= 降低资源消耗
「效果」= "正确的做事" = 「成功管理者」= 提升目标达成度
;
**** 应用
*****[#lightblue]:
管理的必要性：
1. 管理是社会进步和发展的物质力量：美英对比，英比美低；日本成功因管理较好
2. 管理是组织生存发展的重要条件：彼得德鲁克"没有机构就没有管理，没有管理就没有机构"
3. 管理活动具有普遍性：任何组织（层次）都需要管理；管理基本原理对组织普遍适用
;

*** 管理者
**** 识记
*****_:
概念：组织中行使管理职能、通过「协调他人」的活动实现「组织目标」的人
;
*****_:
分类：
	-层次：「高层」、「中层」、「基层」
	-领域：「综合」、「专业」
;
*****_:
角色：（三类十种-亨利*明茨伯格）
	-人际关系：挂名首脑、领导者、联络者
	-信息：监听者、发言人、传播者
	-决策：企业家、混乱驾驭者、资源分配者、谈判者
;
**** 领会
*****_:
技能：
1. 技术技能（基层）：使用某一专业领域的程序、技术、知识和方法完成组织任务
2. 人际技能（中层）：处事能力，理解、激励他人并与他人共事
3. 概念技能（高层）：纵观全局、洞察企业与环境要素相互影响和作用
;
*****_:
管理四项活动（时间精力不同）：
1. 传统管理：决策、计划、控制
2. 沟通：交流理性信息和处理文书
3. 人力资源管理：激励、惩戒、调节冲突、人员配备、培训
4. 网络联系：社交活动、政治活动、外界交往
;
*****_:
效果：
1. 有效：工作数量多、质量好、下级满意度高；特点：沟通多，网络联系少
2. 成功：晋升快的管理者；特点：网络联系多，人力资源少
;

*** 管理学
**** 识记
*****_:
概念：
1. 是系统研究管理过程的普遍规律、基本原理和一般方法的科学；
2. 是千百年来人类管理经验智慧的高度概括总结；
3. 是人们学习管理的主要途径；
4. 泰勒《科学管理原理》问世标志管理作为科学诞生
;
*****_:
学习方法：唯物辩证法；理论联系实际法；系统方法
;
**** 领会
*****_:
特点：「综合性」、『不精确性』（多科性）、「实践性」、「历史性」、「发展性」
;

** 管理理论形成与发展

*** 前期管理实践和思想
**** 识记
*****_:
亚当斯密：
1. 提出「分工协作原理」和「生产合理化」概念；
2. 提出「经纪人」观点：人是自私的，追求个人利益
;

*** 管理理论形成
**** 识记
*****_:
古典管理理论特点：
1. 以提高生产率为目标；
2. 以科学求实态度进行调查研究；
3. 强调以个人为研究对象，重视个人积极性发挥；
4. 强调规章制度的作用
;
**** 领会
*****_:
「科学管理理论」：（泰勒-科学管理之父）
列宁评价：泰勒科学管理既是资产阶级剥削员工最巧妙、最残忍的手段，也是一系列最丰富的科学成就
6个观点：
1. 工作定额原理
2. 标准化原理
3. 科学挑选工人病使之成为"第一流工人"
4. 实行差别计件工资制
5. 管理工作专业化
6. 管理控制的例外原理
;
*****_:
「一般管理理论」：（法约尔-管理过程之父）
要点：
1. 对「经营」与「管理」的研究：经营是直到或引导一个组织去向某一既定目标的活动，「管理仅仅是经营的一项活动」
2. 管理五要素：计划、组织、指挥、协调、控制
3. 管理十四原则：分工、权力与责任、纪律、个人利益服从集体利益、统一指挥、报酬合理、集权与分权、
	秩序、等级链与跳板、公平、人员稳定、首创精神、集体精神
;
*****_:
「行政组织理论」：（韦伯）
1. 理想的组织形态的基础是「权力」：超凡权力、传统权力、法定权利
2. 管理制度
3. 组织结构
特点：
1. 明确的分工；
2. 自上而下的等级系统（权利等级链）；
3. 人员任用根据职务的要求；
4. 职业管理人员：上级任命、固定薪金、工作人员、升迁制度；
5. 遵守规则和纪律；
6. 组织中成员的关系为职业关系
;

*** 行为科学兴起
**** 领会
*****_:
霍桑实验：（梅奥）
1. 工人是「社会人」，而非单纯追求金钱收入的"经纪人"；
2. 生产率的高低主要取决于工人的态度，即「士气」；
3. 企业中存在「非正式组织」；
4. 新型领导能力就是要在「正式组织的经济需求」和「非正式组织的社会需求」间保持平衡
;
*****_:
行为科学建立发展：
1. 动机激励理论（核心）：需求层次论、双因素论、成就需要论
2. 企业管理中的"人性"理论（基础）：XY理论、不成熟-成熟理论、超Y理论
3. 领导方式理论：包括领导方式连续统一理论、支持关系理论
4. 组织与冲突理论：团体力学理论、意见沟通理论、敏感性训练
;
**** 应用
*****[#lightblue]:
行为科学理论在现代管理的运用
;

*** 现代管理理论丛林
**** 领会
*****_:
各管理学派特点：
1. 管理过程学派
2. 社会系统学派
3. 决策理论学派
4. 社会-技术系统学派
5. 经验主义学派
6. 权变理论学派
7. 经理角色学派
8. 管理科学学派
;

** 组织环境和组织文化
** 管理道德和社会责任

@endmindmap
