@startmindmap

* 词汇
** 拆解
*** 规则
**** 元音互换，含义不变
**** s、t、d 互换，含义不变
*****_:
conclu<b>d</b>e -> conclu<b>s</b>ion
deci<b>d</b>e -> deci<b>s</b>ion
conver<b>t</b> -> conver<b>s</b>ion
permi<b>t</b> -> permi<b>s</b>sion
admi<b>t</b> -> admi<b>s</b>sion
ea<b>t</b> -> -e<b>s</b>-/-e<b>d</b>- -> obe<b>s</b>e/e<b>d</b>ible
;
**** 词根 + 连接(-u-/-ul-/-o-/-ol-) + 后缀，方便发音无含义
***** grad<b>u</b>ate / stim<b>ul</b>ate
**** 开头a + 两个辅音字母(x) = axx (abb-/acc-/add-/aff-/agg-) 最后一个x代表词根开始
*** 前缀(50+-)
****[#lightblue] re-
***** 相反 eg. resent
***** 返回 eg. return
***** 反复/又/再/加强 eg. repeat
**** pro-
***** (=forward) (动态含义)向前
**** pre-
***** (静态)前面、提前
**** ac-
***** (=to) 去
****:a-
ad-;
***** (=to) 去
***** 加强
****:e-
ex-
es-;
***** 向外
***** 超出

*** 词根
****[#lightblue]:-cess-、-ceed-、-cede-、-gress-、
-gred-、-grad- (=to go) 走
-cess-(n.) -ceed-(v.);
***** process (392)
******_:
n.过程、进程；v.处理、加工
pro- 向前 -cess- 走
data procession
information processing
;
***** processor (4663)
******_:
n.处理器
process 处理器 -or 名词后缀
;
***** procession (7783)
******_:
n.队伍、行列；一列、一排；列队行进
pro- 向前 -cess- 走 -ion 名词后缀
英英释义：走路、骑马、开车等
A procession is a group of people who are
walking, riding, or driving in a line as
part of a public event.
;
***** graduate (2133)
******_:
v.毕业；n.(本科)毕业生
-grad- 走 -u- 连接 -ate 名词后缀 -> 要走 -> 离开学校
;
***** undergraduate (4804)
******_:
n.大学本科生、肄业生
under- 下、未达到 -graduate- 毕业
;
***** ingredient (2613)
******_:
n.原料、要素、组成部分
in- 进入 -gred- 走 -i- -ent 名词后缀 -> 走进去
;
***** aggressive (2538)
******_:
adj.侵略性的、激进的
aggress v.侵略
aggression n.侵略
a- 加强语气 -g-(axx) -gress- 走
;
***** progress (1517)
******_:
v.前进；n.进步
pro- 向前 -gress- 走
make rapid ~ 取得快速的进步
;
***** proceed (2720)
******_:
v.前进、继续进行；继续
pro- 向前 -ceed- 走
proceed with sth.
proceed to 前往、进入
;
*****[#lightblue] proceedings (5436)
******_:
n.诉讼、议程、一系列活动事件
legal proceedings 法律诉讼
;
***** procedure (1376)
******:
n.程序、步骤
pro- 向前 -ced- 走 -ure 名词后缀
surgical procedures 手术程序
legal procedures 法律程序
;
***** precede (5675)
******_:
v.领先于、优于
pre- 提前、前面 -cede- 走
;
***** precedent (5698)
******_:
n.先例、前例；adj.先前的
precede 前面 -ent 名词后缀
;
***** unprecedented (4450)
******_:
adj.史无前例的、空前的
un- 否定 -precedent 先例 -ed 形容词，的
precedented 有过先例的
the bubble rish ~ level 房地产泡沫达到史无前例的水平
;
***** precedence (13362)
******_:
n.优先、领先
pre- 前面 -ced- 走 -ence 名词后缀
同义：priority n.优先权、优先
priority = prior- 优先于、先于 -ity 名词后缀
give precedence/priority to sth. 优先考虑某事情
;
***** access (4416)
******_:
v./n.接近、进入；使用、获取
ac- (=to)加强 -cess- 走
access email
have access to
;
***** accessible (4423)
******_:
adj.可接近的、可使用的、可获得的
access 接近、使用 -ible 可以...的
accessible capital：可用资金
Lily is accessible：Lily是平易近人的
;
***** accessory (6532)
******_:
n.附件、配件、从犯
ac- (=to)去、强调 -cess- 走 -ory 名词后缀
;
***** recession (3611)
******_:
n.衰退；凹处；后退；不景气
re- 回 -cess- 走 -ion 名词后缀
recede v.后退、撤退
;
***** excess (5825)
******_:
n.无节制；过度、过量；超过、超额
ex- 向外、出去、超出 -cess- 走
global excess demand
excess weight：过度肥胖
;
***** excessive (4620)
******_:
adj.过分的；过多的，极度的
;
***** exceed (3308)
******_:
vt.胜过；超过
ex- 向外、出 -ceed- 走
;
***** exceedingly (11078)
******_:
adv.非常；极其；极度地
exceedingly polite forms：极度有礼貌的形式
;
***** cease (4518)
******_:
vt/vi/n.停止；终了
ceas (=-cess-)走
;
*** 后缀
****[#lightblue]:-or
-ar
-er
-ur;
***** n. 人、物、机器
***** adj.
***** v. (较少出现)
****[#lightblue] -ory
***** n.
**** -ing
***** n.
****:-ate
-ite
-ute;
***** v. (使动词)
***** adj.
***** n. (极少出现) 人、物
**** -ive
***** adj. 大、多；xxx的
***** v.
***** n. 人、物
****:-ent
-ant;
***** n. 人、物
***** adj. xxx的
****:-ance
-ence
-ancy
-ency;
***** n. 无含义
** 单词
*** etymology
**** n.词源学


@endmindmap