@startmindmap

* 战略环境分析阶段

** 企业经营战略环境分析
*** 企业经营战略环境概述
**** 识记
*****_:
企业经营战略「环境」的概念：
「一切」直接和间接影响企业经营活动的「条件总和」
战略环境分析：通过对企业自身所处内外环境充分认识和评价，
以便发现机会和威胁，确定优势和劣势，从而为制定实施战略
提供指导
;
*****_:
<&flag>战略环境分类
1.外部环境：
  1.「宏观」环境：也称一般环境，是指可能对所有企业产生影响的集合，
    包括：政治、社会文化、经济、技术环境
  2.「行业」环境：也称中观环境，对行业内企业会产生影响的因素，
    包括：供应商、客户、现实竞争者、潜在竞争者、替代品生产者（五力模型）
  3.「微观」环境：具体环境或特殊环境，直接迅速对某个企业直接影响的力量，
    包括：供应商、中介机构、顾客、直接竞争者、公众等 
2.内部环境
;
**** 领会
*****_:
企业经营战略环境的重要性：
正确认识和分析经营战略环境是正确制定
经营战略的先决条件
;
*****_:
<&flag>企业经营战略环境的特点：
1.客观性
2.复杂性
3.关联性
4.「不确定型」
5.层次性
;
*****_:
企业与经营战略环境的关系：
1.经营战略环境对企业的影响：
1）经营战略环境是企业赖以生存的土壤
2）外部环境因素影响着企业内部的各种经营活动
3）经营战略环境制约企业的经营活动和经营效率
2.企业对经营战略环境的影响
1）适应环境
2）影响环境
3）选择环境
;
**** 应用
*****[#lightblue]:
<&flag>影响同业企业竞争激烈程度的主要因素：
1.同企业的数量和力量对比
2.行业发展速度
3.产品的差异化程度和用户的转换成本
;
*****[#lightblue]:
结合实例能对企业经营战略环境重要性进行分析：
;
*****[#lightblue]:
结合实例对企业与经营战略环境之间的相互关系进行分析：
;

*** 企业经营战略环境分析的内容
**** 识记
*****_:
<&flag>PEEST(宏观环境)分析：「政治」（Politics）、「经济」（Economic）、「自然生态」（Environment）、
「社会」（Society）、「技术」（Technology）
政治因素：
  指对企业经营活动具有实际或潜在影响的政治力量和有关法律法规
  政治因素的类别；政治与法律；政治环境与企业
经济因素：
  1. 宏观经济：国家经济制度、经济结构、产业布局、资源状况、发展水平
  2. 微观经济因素：消费者收入变化、支出模式、储蓄、信贷
生态资源因素：
  企业所面临的地理位置、气候条件和资源状况等自然因素。
  生态资源资源直接影响企业的选址、产品、成本、经营效率等，同时对生态资源的
  态度也直接反应企业的社会责任感
社会文化因素：
  1. 社会环境：价值观、民族特征、生活方式、消费心理、人口
  2. 文化环境：教育水平、风俗习惯、宗教、医疗、体育
技术因素：
  不仅包括引起革命性变化的发明，还包括企业生产的新技术、新工艺、新材料
;
*****_:
<&flag>行业环境分析：
目的：为了了解行业总体情况及发展趋势，从中发现生存发展机会；同时了解行业
威胁，把握竞争态势，制定正确战略
分析内容：
1. 现状和前景：寿命周期；行业规模；技术状况；行业战略集团
2. 竞争结构（五力模型）：现有竞争者；潜在进入者；替代品；供应商议价；购买者议价
;
*****_:
微观环境分析：
指对企业经营活动构成直接影响的各种外部力量，包括：供应者、中介、顾客、竞争者、公众
;
*****_:
企业内部环境：
指企业内部的各种内部物质、文化环境的总和（企业资源、能力、文化）
分析目的：分析企业自身的优势劣势；查出造成劣势的原因，找出内部潜力；
为企业正确制定经营战略、编制经营计划提供科学依据
分析内容：
1. 企业一般情况：管理水平、发展、技术素质、生产条件、资源
2. 企业经营实力：产品竞争能力、技术开发能力、生产能力、营销能力、获利能力
;
**** 领会
*****_:
宏观环境分析的内容：
1. 政治环境
2. 经济环境
3. 社会文化、技术环境
4. 自然生态环境
;
*****_:
行业竞争结构分析：
;
*****_:
内部环境分析的内容：
;
**** 简单应用
*****_:
对企业所处的宏观环境进行分析：
;
*****_:
对企业的行业环境进行分析：
;
*****_:
对企业的内部环境进行分析：
;
**** 综合应用
*****[#lightblue]:
应用所学知识对企业经营战略环境进行综合分析：
;

*** 企业经营环境分析的方法
**** 识记
*****_:
「SWOT」分析法含义：在外部环境和内部环境分析的基础上，把两种分析方法结合、进行寻求
外部环境中「机会」和「风险」（威胁）、内部环境中「优势」与「劣势」的分析方法
步骤：
1. 分析内部优势劣势；
2. 分析外部机会威胁；
3. 寻求组合
;
*****_:
「波士顿矩阵」分析法：又称四象限分析法，将「市场需求增长率」和「相对市场占有率」两个指标
作为衡量标准并形成矩阵图形，对企业经营领域分析的方法
;
*****_:
「麦肯锡矩阵」分析法：又称GE矩阵法，将「战略经营领域吸引力」和「企业竞争地位」两个指标
作为分析组合
;
**** 领会
*****_:
SO、WT、WO、ST组合：
1. 优势-机会(SO)组合：理想战略模式。收购竞争对手、扩大生产规模
2. 劣势-机会(WO)组合：扭转型战略
3. 优势-威胁(ST)组合：扬长战略
4. 劣势-威胁(WT)组合：防御战略
;
*****_:
<&star>「波士顿矩阵」分析法：
「市场增长率」和「市场占有率」对「企业经营领域」(市场)分析的方法
1. “双高”：「明星」类产品。抓住机遇，重点投资，促进发展
2. “双低”：「瘦狗」类产品。果断放弃
3. “增长高占有低”：「问题」(野猫)类产品。完善提高，转化为「明星」
4. “占有高增长低”：「现金牛」类产品。严格控制投资，维持规模，获取利润，支持「明星」和「问题」
;
*****_:
麦肯锡矩阵分析法：
比波士顿矩阵指标更丰富：
「战略经营领域新引力」=「需求增长率」+「未来盈利率」+「环境变化和偶发事件概率」
「企业竞争地位」=「投资水平程度」+「竞争优势程度」+「达到一流企业程度」
;
*****_:
内部价值链分析法：企业竞争优势来自企业为顾客创造超过其成本的价值：「竞争优势」=「价值」-「成本」
企业竞争优势来自设计、生产、营销、交货及对产品辅助作用的活动集合，这些环节统称「价值链」
价值链中「盈余」代表竞争优势的大小，一般用「利润」表示
;
**** 简单应用
*****_:
依据企业产品或业务的市场增长率和市场占有率的不同组合选择不同经营战略：
;
**** 综合应用
*****[#lightblue]:
结合案例，借助SWOT分析法进行企业业务的经营战略选择：
;

** 企业战略经营领域分析

*** 企业战略经营领域概述
**** 识记
*****_:
经营(时空)领域：是指企业选定行业和目标市场相结合形成的经营场所
;
*****_:
战略经营领域：Strategic Bussiness Area (SBA) 指对企业生存发展具有决定性作用的特定微观环境，是企业
在选定行业投放资源，提供特定产品和劳务，满足目标市场特定需求，迎接特定
竞争，施展特定战略，追求理想效益的经营场所
;
*****_:
战略经营领域结构：指企业选择两个以上SBA，相应地投入了不同的经营资源，
带来了不同的经营效益，所形成不同SBA之间「质」的组合和「量」的比例关系
;

*** 确定战略经营领域结构的原则
**** 识记
*****_:
确定战略经营领域结构的一般原则：指环境引力和企业实力平衡原则(记忆提示波士顿矩阵)
1.明星SBA：「环境引力」大、「企业实力」大；
2.问题SBA：环境引力大、企业实力小（逆差）；
3.奶牛SBA：环境引力小、企业实力大（顺差）；
4.瘦狗SBA：环境引力小、企业实力小；
;
**** 领会
*****_:
企业的生存与发展平衡的原则：目的保证企业生存和发展要解决的根本问题，防止企业 SBA
结构选择不当
按「环境引力」和「企业实力」的强弱关系划分四象限：
1. “双强”：「成长期」
2. “双弱”：「衰退期」
3. “引力强实力弱”：「投入期」
4. “实力强引力弱”：「成熟期」

1. 用行业或SBA「寿命周期」阶段代表「环境引力」：
    a. 未来（投入期、成长期）：明星、难点
    b. 今天（成熟期、衰退期）：奶牛、瘦狗
2. 用企业「综合实力」代表「企业实力」：
    a. 前途光明：明星、奶牛
    b. 前途暗淡：难点、瘦狗
失衡状态：
1. 全部集中在「投入期」、「成长期」；
2. 全部集中在「成熟期」、「衰退期」；
3. 虽然「引力」分布均衡，但「实力」差；
;
*****_:
企业投入与收入平衡的原则：追求盈利是企业投资的基本动机，SBA结构应保证收入大于投入
不同象限的SBA投入收入关系：
1. 明星区：投入与收入相抵，没有盈余；利润率高，研发宣传生产费用高
2. 问题区：收入不抵资金投入，亏损；利润率高，实力不足，销量有限
3. 金牛区：收入大于支出，盈余；增长率低，利润率低，销量大，资金投入少
4. 瘦狗区：收入低于投入，亏损；收入少，固定资金、流动资金占用严重
;

*** 企业战略经营领域的分析方法
**** 识记
*****_:
战略主体：
;
*****_:
战略关系：
;
**** 领会
*****_:
「环境引力」与「企业实力」的对比分析法：
任何一个战略经营领域都是环境引力和企业实力的结合，研究SBA必须将两反面，孤立地、片面地
研究任何一方都不能得到深入、中肯的结果。
企业是战略主体，而环境是企业的适应对象，离开环境分析企业就无所参照，对自己的优势与劣势
缺乏情形认识，战略方向就不明确；同样企业若缺乏对自身规律的认识，在复杂环境面前难免无从
下手
;
*****_:
SBA的运行规则和战略主体、战略关系、战略关键分析：
1.SBA运行规则分析：
  a.客观规律：需求偏好、产品技术规律
  b.主观规律：产业政策、法律文本
  c.多元：宏观、微观、中观；政治、经济、文化、法律
  d.多层：集团公司、子公司
2.战略主体：指SBA特定需求者、供应者、直接竞争者、潜在竞争者、替代竞争者、政策制定者
及企业自身，分析要点：
  a.各类战略主体的总量和结构
  b.主要战略主体的实力、策略和活动方式
  c.要善于辨别SBA的运行规则和特点
3.战略关系：指SBA内各战略主体间形成的错综复杂的关系，包括企业与消费市场、供给者、竞争者
、政策制定部门和相关部门的战略关系
  a.直接关系：企业与各战略主体之间
  b.间接关系：其他战略主体之间
4.战略关键分析：指影响企业生存与发展、最紧要的规则、主体和关系，即是诸多规则、主体和
关系的主要矛盾。战略关系「客观存在」，但企业有选择权利
;
*****_:
环境风险度与管理模式：研究战略经营领域必须密切注意风险环境变化。
安索夫根据环境变化速度和深度将环境风险度划分为五类管理模式：
「管理模式」：「环境稳定程度」、「环境变化速度」->「环境变化性质」、「企业关键职能」
1.「稳定型」：「稳定」、「很慢」                ->「微小量变」、「生产管理」
2.「反应型」：「较稳定」、「慢」                ->「量变」、「扩张型生产管理」
3.「先导型」：「不稳定」、「较快」              ->「质变」、「市场营销管理」
4.「探索型」：「很不稳定」、「快」              ->「快速质变」、「战略管理」
5.「创造型」：「极不稳定」、「很快」            ->「急速质变」、「风险管理」
;
**** 应用
*****[#lightblue]:
应用「环境引力」与「企业实力」的对比分析法对经营战略领域进行分析：
1. 发展型态势：环境机会与企业优势结合的结果
2. 紧缩型态势：环境威胁与企业劣势结合的结果
3. 稳定型态势：环境风险度与企业适应度基本相适应的结果
确定SBA的战略方针、重点、优势和向量要围绕其成功关键因素进行
;
*****[#lightblue]:
结合实例对战略经营领域的运行规则和战略主体、战略关系、战略关键进行分析：
SBA分析需要分析企业与以下竞争力量之间的战略关系：
1.与消费者市场的战略关系分析
2.与供应者的战略关系分析
3.与竞争者的战略关系
4.与政策制定部门和相关部门的战略关系
;



** 企业使命和战略目标
*** 企业使命决策
**** 识记
*****_:
「企业使命」的含义：指企业的目的、性质、任务及其在国家经济发展和
社会进步中应当承担的社会责任等方面做出的规定
;
**** 领会
*****_:
确定企业使命的重要性：
1.用于界定企业经营领域：存在目的、活动范围、客户、产品服务，明确规定企业发展方向
2.是确定战略目标的前提：从而制定企业合理现实实现战略目标
3.是战略方案制定和选择的依据：从而合理确定事业的先后顺序和关键活动
4.是合理配置企业资源的基础：正确分配企业有限的资源
;
*****_:
企业使命决策的内容：
1.企业性质的确定
2.企业成长方向的选择
3.经营目的的确定：生存、发展、盈利
4.企业经营哲学的性质：观念和行为准则
5.企业经营方针的选择：基本原则、指导方略、行动方针
6.企业社会责任的确定：市场、顾客、生态、就业、公益
;
*****_:
确定企业使命应重视研究的几个问题：
1.要以「顾客基本需求为中心」确定企业使命：顾客需求多元化、买方市场
2.正确的企业使命必须具有「约束力」：惩罚
3.企业使命要具有「鼓动性」：激励
;
**** 简单应用
*****_:
联系实际分析企业使命的决策：
1.坚持企业原有使命的决策：坚持原有经营领域和服务方向，继续把原有顾客作为自己市场
2.扩大企业使命的决策：开辟新的经营事业和扩大服务领域、对象
3.改变企业使命的决策：从原有的领域撤退，重新选择客户群
;
*****_:
对现实企业的使命能做出分析：
企业使命决策应考虑的因素有，国家长远发展规划和产业政策、市场需求、竞争态势、企业实力
;

*** 企业战略目标决策
**** 识记
*****_:
「战略目标」的含义：是企业使命和宗旨的具体化和定量化，把企业经营目的转化为多方面、
可以量化的具体指标，反应企业经过一定时期的努力应达到的经营水平。是企业奋斗纲领，
是衡量企业工作是否实现其使命的标准，是企业经营战略的核心
;
*****_:
战略目标的构成：
1.纵向：（分解成树形）「企业使命」上制定「总战略目标」，层层分解多个「职能性战略目标」
，每个职能性战略目标层层分级多个「子目标」
2.横向：
  按着力点不同分为：
  1.发展性目标：提高企业各方面素质，增强发展能力
  2.效益性目标：产出、投入、成本、利润
  3.竞争性目标：尽可能多占据市场份额
  4.利益性目标：增加投资回报、企业收益、经营者劳动者收入
  按社会贡献不同：
  1.用来满足企业生存和发展所需的项目目标
  2.用来满足与企业有利益关系的各个社会群体要求的目标
  德鲁克提出：
  1.市场推销目标
  2.创新目标
  3.人员组织目标
  4.财务资源目标
  5.物质资源目标
  6.生产率目标
  7.社会责任目标
  8.利润目标
;
**** 领会
*****_:
战略目标的作用：
1.能够实现企业「外部环境」、「内部条件」和「企业能力」三者动态平衡，使企业获得长期
稳定和协调发展
2.能够使企业使命具体化和数量化，使企业的战略任务得以落实
3.是企业战略实施的指导原则：集中力量、减少冲突、提高效率效益
4.为战略方案的决策和实施提供评价标准和考核依据
;
*****_:
战略目标决策的内容：
1.战略水平的选择：目标定多高提出高中低三个方案，根据企业使命和内外环境(SWOT)做出选择
2.重点战略目标决策：多个战略目标突出重点目标。参考经营领域重点(OT)、市场地位强弱(SW)
;
*****_:
战略目标制定与选择的基本要求：
1.战略目标必须具有科学依据
2.目标必须明确和具体，并规定完成期限
3.目标必须具有挑战性，并切实可行
4.目标应突出重点
5.目标应形成一个完整的体系
;
**** 简单应用
*****_:
对企业战略目标的决策与选择做出分析：
;

@endmindmap