@startmindmap

* 战略环境分析阶段

** 企业经营战略环境分析
*** 企业经营战略环境概述
**** 识记
*****_:
企业经营战略环境的概念：
一切直接和间接影响企业经营活动的条件总和
战略环境分析：通过对企业自身所处内外环境充分认识和评价，
以便发现机会和威胁，确定优势和劣势，从而为制定实施战略
提供指导
;
*****_:
外部环境：
1. 宏观环境
2. 行业环境
3. 微观环境
;
*****_:
宏观环境：
也称一般环境，是指可能对所有企业产生影响的集合，
包括：政治、社会文化、经济、技术环境
;
*****_:
行业环境：
也称中观环境，对行业内企业会产生影响的因素，
包括：供应商、客户、现实竞争者、潜在竞争者、
替代品生产者（五力模型）
;
*****_:
微观环境：
具体环境或特殊环境，直接迅速对某个企业直接影响的力量，
包括：供应商、中介机构、顾客、直接竞争者、公众等 
;
**** 领会
*****_:
企业经营战略环境的重要性：
正确认识和分析经营战略环境是正确制定
经营战略的先决条件
;
*****_:
企业经营战略环境的特点：
1. 客观性
2. 复杂性
3. 关联性
4. 不确定型
5. 层次性
;
*****_:
企业与经营战略环境的关系：
1. 经营战略环境对企业的影响：
1） 经营战略环境是企业赖以生存的土壤
2） 外部环境因素影响着企业内部的各种经营活动
3） 经营战略环境制约企业的经营活动和经营效率
2. 企业对经营战略环境的影响
1） 适应环境
2） 影响环境
3） 选择环境
;
**** 应用
*****[#lightblue]:
结合实例能对企业经营战略环境重要性进行分析：
;
*****[#lightblue]:
结合实例对企业与经营战略环境之间的相互关系进行分析：
;

*** 企业经营战略环境分析的内容
**** 识记
*****_:
PEEST分析法：
宏观环境分析：政治（Politics）、经济（Economic）、自然生态（Environment）、
社会（Society）、技术（Technology）
;
*****_:
政治因素：
指对企业经营活动具有实际或潜在影响的政治力量和有关法律法规
类别；政治与法律；政治环境与企业
;
*****_:
宏观经济与微观经济因素：
;
*****_:
生态资源因素：
;
*****_:
社会文化因素：
;
*****_:
技术因素：
;
*****_:
行业环境分析：
;
*****_:
微观环境分析：
;
*****_:
企业内部环境：
;
**** 领会
*****_:
宏观环境分析的内容：
1. 政治环境
2. 经济环境
3. 社会文化、技术环境
4. 自然生态环境
;
*****_:
行业竞争结构分析：
;
*****_:
内部环境分析的内容：
;
**** 简单应用
*****_:
对企业所处的宏观环境进行分析：
;
*****_:
对企业的行业环境进行分析：
;
*****_:
对企业的内部环境进行分析：
;
**** 综合应用
*****[#lightblue]:
应用所学知识对企业经营战略环境进行综合分析：
;

*** 企业经营环境分析的方法
**** 识记
*****_:
SWOT分析法含义：
;
*****_:
波士顿矩阵分析法概念：
;
*****_:
麦肯锡矩阵分析法的概念：
;
**** 领会
*****_:
SO、WT、WO、ST组合：
;
*****_:
波士顿矩阵分析法：
;
*****_:
麦肯锡矩阵分析法：
;
*****_:
内部价值链分析法：
;
**** 简单应用
*****_:
依据企业产品或业务的市场增长率和市场占有率的不同组合选择不同经营战略：
;
**** 综合应用
*****[#lightblue]:
结合案例，借助SWOT分析法进行企业业务的经营战略选择：
;

** 企业战略经营领域分析

*** 企业战略经营领域概述
**** 识记
*****_:
经营领域：
;
*****_:
战略经营领域：
;
*****_:
战略经营领域结构：
;

*** 确定战略经营领域结构的原则
**** 识记
*****_:
确定战略经营领域结构的一般原则：
;
**** 领会
*****_:
企业的生存与发展平衡的原则：
;
*****_:
企业投入与收入平衡的原则：
;

*** 企业战略经营领域的分析方法
**** 识记
*****_:
战略主体：
;
*****_:
战略关系：
;
**** 领会
*****_:
环境引力与企业实力的对比分析法：
;
*****_:
SBA的运行规则和战略主体、战略关系、战略关键分析：
;
*****_:
环境风险度与管理模式：
;
**** 应用
*****[#lightblue]:
应用环境引力与企业实力的对比分析法对经营战略领域进行分析：
;
*****[#lightblue]:
结合实例对战略经营领域的运行规则和战略主体、战略关系、战略关键进行分析：
;



** 企业使命和战略目标
*** 企业使命决策
**** 识记
*****_:
企业使命的含义：
;
**** 领会
*****_:
确定企业使命的重要性：
;
*****_:
企业使命决策的内容：
;
*****_:
确定企业使命应重视研究的几个问题：
;
**** 简单应用
*****_:
联系实际分析企业使命的决策：
;
*****_:
对现实企业的使命能做出分析：
;

*** 企业战略目标决策
**** 识记
*****_:
战略目标的含义：
;
*****_:
战略目标的构成：
;
**** 领会
*****_:
战略目标的作用：
;
*****_:
战略目标决策的内容：
;
*****_:
战略目标制定与选择的基本要求：
;
**** 简单应用
*****_:
对企业战略目标的决策与选择做出分析：
;

@endmindmap