@startmindmap

* 控制
** 控制

*** 概述
**** 识记
*****_:
概念：
狭义讲：控制就是“纠偏”，即按照计划标准衡量计划的完成情况，
针对出现的偏差情况采取纠正措施，以确保计划得以顺利实现，
“维持现状”
广义讲：控制不仅限于“纠偏”，同时还包含着在必要时修改计划
标准，以使计划更加适合于实际情况，“打破现状”
在管理活动中，完整的控制包括“纠偏”和“调试”两方面含义，控制
的功能是将绩效与预期绩效进行比较，期间如果有差异进行纠正
;
**** 领会
*****_:
必要性：
由于各种原因，人们执行计划的活动中总是会出现
与计划不一致的现象，管理控制成为必然
1. 环境的变化：组织外部环境变化要求对原定计划
相应调整
2. 管理权力分散：组织的分权程度越高，控制就越
有必要
3. 工作能力的差异：导致实际结果可能在质量上与
计划要求不符 
;
*****_:
控制与其他管理职能的关系：
控制工作存在于管理活动的全过程，与其他管理职能紧密结合
在一起，不仅可以维持其他职能的正常活动，而且在必要时，
还可以采取“纠偏”来改变其他管理的职能活动，使管理过程
形成相对封闭的系统
1. 计划和控制是一个问题的两个方面
2. 要进行有效控制，必须有组织保证
3. 领导影响控制工作的质量
;
*****_:
目的：
1. 基本目的，“维持现状”：通过纠正措施，使系统的活动趋于
相对稳定，实现组织的既定目标
2. 某些条件要“打破现状”：应对内外部环境变化改革创新，开
拓新局面
最佳目的是防止问题发生：把控制建立在前馈而不是简单的问题
反馈，能预测并及时采取措施防止
;

*** 类型与过程
**** 领会
*****_:
控制的类型：
1. 前馈、现场、反馈
1）前馈控制：即事先控制，是计划实施前采取预防措施
防止问题发生，而不是在实施中出现问题后的补救，是一
种预防性措施。优点：避免预期问题的出现，防患于未然，
适用于一切领域的工作；工作之前针对某项计划行动所
依赖的条件进行控制，不针对具体人员，不会造成心理
抵触，易于接受实施。
2）现场控制：又称同期控制、过程控制，是指在某项活动
或工作进行过程中，在现场发现存在偏差或潜在的偏差，
及时提供改进措施以纠正偏差。优点：经济高效，纠偏
有利；缺点：受管理者时间、精力、业务水平的制约；应用
范围较窄；易形成控制者与被控制者心理上的对立，影响
积极性和主动精神。
方式：1 主管人员深入现场检查和指导下属，方法过程指导
监督，纠偏；2 基层工作人员的日常自我控制，控制对象
就是自我的操控
3）反馈控制：事后控制或成果控制。活动完成后将结果与
标准对比，发现偏差加以纠正，防止偏差继续发展和再次
发生。优点：根据实际结果进行评价，易于接受，也利于
采取有效和有利的改进措施。增强员工的积极性。通过
获得绩效评价的信息，调整未来行为，提高工作绩效。
缺点：时间滞后性，失误和损失已产生，弥补职能在新工作
产生效果
2. 直接、间接
1）直接控制：控制者与被控制者直接接触，由控制者
直接调节、干预被控制者，凑而纠正偏差。特点：直接
性，通过提高管理人员的素质来进行控制工作
2）间接控制：指控制者与被控制者不直接接触，通过
中间工具作用于被控制对象
间接控制不是普遍有效的控制方法。
直接控制必然，而间接控制不然
;
*****_:
控制的过程：
1. 确立标准：没有控制标准，衡量绩效和纠正偏差将失去
依据。各项规定的指标可作为控制标准。控制标准有：定量
标准、定额标准、质量指标。“定质”指标：数量标准、质量
标准、时间标准、成本和效益标准等
2. 衡量绩效：用确立的标准对实际工作和进度进行检查和
比较，发现问题，分析原因、采取措施
3. 纠正偏差：针对被控制对象出现的偏离程度，及时采取措施
予以纠正，使其恢复到正常状态
;

*** 有效控制的原则
**** 应用
*****[#lightblue]:
有效控制原则在实践工作的应用：
1. 及时性原则：对偏差尽可能早的发现并及时采取措施
加以纠正。
2. 适度性原则：指控制的范围、程度和频率恰到好处，
防止控制过多或不足
3. 重点原则：控制要有重点，抓主要问题，全面控制
不必要且代价高
4. 经济性原则：只有控制带来的效益超出所需成本时，
才是值得的。
5. 客观性原则：运用科学的态度、方法进行控制，不能
凭个人主观和直觉
6. 弹性原则：要允许控制在以计划为中轴的上下之间有
个浮动的幅度，保证控制使用和有效
;


*** 控制的内容和方法
**** 识记
*****_:
预算及种类：
预算是用数字编制未来某一个时期的计划，是计划的数量表现
种类：
1. 内容不同分为：运营预算、投资预算、财务预算
2. 财务角度分为：收入预算、支出预算、现金预算
3. 根据编制基础分为：零基预算、增量预算
;
*****_:
ABC分类法的含义：
根据企业不同库存物资的重要程度，对企业
所有库存物资进行分析、计算（根据数量和
类别）把物资分为A、B、C三类，然后对不
同类别实施不同管理
;
*****_:
经济批量的含义：
企业在保证满足均衡生产需要的条件下，通过费用
计算和确定最低的合理生产批量的数学方法。当总
需求数量一定时，订购费用和存储费用成反比，
经济批量模型是在订购费用和存储费用之间取得
平衡，使总费用最低，算出订购量
;
**** 领会
*****_:
控制的内容：
1. 人员控制：
1）直接：直接巡查、视察、评估、指导
2）间接：合理配置、培训、激励
2. 时间控制：
常用方法：甘特图、滚动计划法、网络计划技术
准时生产制(JIT)就是在必要的时间生产必要
数量的产品
3. 成本控制：
1） 制定控制标准，确定目标成本
2）记录和统计资料，进行成本核算
3）差异分析
4）采取措施，降低成本
4. 质量控制：
产品质量是工作质量的体现，工作质量是产品质量的
保证。控制产品质量是企业生产合格产品和减少无效
劳动的重要保障
5. 库存控制
库存控制是仓储管理的重要内容，满足顾客需求的
前提下，尽可能降低库存水平、提高物流系统效率，
提高企业市场竞争力
6. 审计控制
审计是常用的一种控制方法，根据内容分为财务和
管理审计，根据审计人员来源，分为内部和外部审计
1）财务审计：依法对财务和财政收入等审查
2）管理审计：系统考查、分析和评价管理水平和
成效
3）内部审计和外部审计
;
*****_:
全面质量管理：
保证产品质量和工作质量为中心，企业全体员工参与
的管理体系，它具有多指标、全过程、多环节和综合
性的特征
特点：
1. 管理对象是全面的
2. 质量管理的过程和范围是全面的
3. 参加质量管理的人员是全面的
4. 管理质量的方法是全面的
基本方法：
一个过程：企业管理是一个过程
四个阶段：计划Plan、执行Do、检查Check、
处理Action，PDCA循环
八个步骤：P{分析现状；分析原因；找出影响因素、
提出计划、制定举措} D{执行落实计划} C{检查计划实施} 
A{总结经验；提出尚未解决问题转入下一循环}
;

@endmindmap
