@startmindmap

* 「个人」心理与行为

** 个性与个体行为分析
*** <&star>人性假设
**** “经济人”假设
**** “社会人”假设
**** “自我实现人”假设
**** “复杂人”假设

*** 关于个体行为的解释
**** 华生的行为主义理论
**** 新华生主义
**** 卢因的观点
**** 个体行为规律

*** 影响人的行为的心理因素分析
**** 心理过程
**** 个性心理

** 个体心理与行为

@endmindmap