@startmindmap

* 「个人」心理与行为

** 个性与个体行为分析
*** <&star>人性假设
**** <&star>“经济人”假设
*****_:
「经济人」含义
经济人也叫“唯利人”或“实利人”，这种假设源于“享乐主义”的哲学观点
和亚当斯密关于劳动交换的经济理论
1.「<&people>亚当斯密」提出“经济人”观点
   <&star>认为人的行为在于「追求本身的最大利益」，工作的动机就是「获得
经济报酬」
2.「X理论」：美国工业心理学家道格拉斯麦格雷戈在他的著作《论企业中的人性》
一书提到两种「对立人性假设理论：X理论和Y理论」
    五个观点：1.人天生懒惰；2.胸无大志甘愿被领导；3.个人组织目标矛盾；
              4.目的满足生理安全需要；5.被管理者和管理者

;
*****_:
「经济人」如何管理
1. 采用「任务管理」的方式
2. 管理工作是「少数人」的事情，与工人无关
3. 实施明确的「奖惩」制度
;
*****_:
「经济人」评价
- 不足
  1. 以金钱为主的机械式管理，严密控制员工
  2. 反对工人参与管理，把管理者和被管理者对立，否认工人的地位和作用
- 作用
  改变了「放任自流」的管理作风，强化社会对消除浪费及提高工作效率的
关注，促进「科学管理」体制建立
;
**** <&star>“社会人”假设
*****_:
「社会人」含义
「<&people>梅奥」在长达9年的「霍桑实验」基础上提出了“社会人”假设，
认为人们在工作中得到的物质方面的利益在调动其生产积极性方面只起到次要
作用，人们最重视的是工作中与周围人形成良好的关系，「良好的关系」是
调动人生产积极性的「决定性因素」
1. 人是“社会人”
2. 管理工作要“以人为本”
3. 组织中存在“非正式群体”
4. 建立新型的领导方式
;
*****_:
「社会人」管理
1. 管理人员不应该只关注任务，还应该「关心人、满足人的需要」上
2. 管理人员注重指挥、监督和控制的基础上，还要关注员工的「人际关系」，
努力提高员工对组织的认同感，激起员工的奉献精神，增强凝聚力
3. 在实施奖励措施时，应主张实行集体奖励而不是个人奖励
4. 管理职位要进行轮换，不应只局限计划制定，而应在员工和上下级间
起到「联络人」的作用，负责上下级沟通
5. 主张「参与管理」的管理方式
;
*****_:
「社会人」评价
从“经济人”假设到“社会人”假设是管理思想的一次「巨大飞跃」，标志着
人们对人性认识进一步加深
;
**** “自我实现人”假设
*****_:
「自我实现人」含义
“自我实现人”也叫“自动人”，这种人性假设产生于20世纪50年代，是美国
心理学家「<&people>马斯洛」提出，“自我实现”指个人才能得到充分展示和发展
1.<&people>马斯洛：人都需要发挥自己的潜力，表现自己的才能，只有潜力充分
发挥，才能充分表现，人才会感到最大满足
2.<&people>麦格雷戈的「Y理论」:
  1）厌恶工作不是普通人的本性
  2）外部的控制及惩罚带来的威胁不是促使人们努力达到组织目标的唯一手段
  3）一般人在适当条件下能承担责任，甚至乐于「追求责任」
  4）在人群中广泛存在并分布高度想象力、智谋的「创造性力量」
  5）员工自我实现的需要和主动完成的工作意向，使组织绩效「更富有成果」
  6）在现代工业化社会条件下，普通人的智力只得到了部分发挥
;
*****_:
「自我实现人」管理
1.管理重点；重视人->重视「工作环境」
2.激励方式：最根本且起长远作用的是「内在激励因素」
3.管理制度：主张「管理权限下放」，员工能力充分发挥
4.管理职能：管理者主要任务是为员工发挥才能「创造条件」
;
*****_:
「自我实现人」评价
- 不足：错误的把人性看成是天生的、自然形成和逐渐成熟的
- 贡献：其理论及相应的管理措施在当时社会环境和背景下是相当有说服力和
先进的，许多观点值得借鉴
;
**** “复杂人”假设
*****_:
「复杂人」含义
“复杂人”假设视20世纪60-70年代提出，认为人的需要和潜力会随着「年龄的
增长」、「知识的增加」及「身份、地位的改变」而有所变化，不能统一模式
嵌套
美国行为科学家「<&star><&people>埃德加沙因」于1965年《组织心理学》中对人性
归类假设：
1. 每个人的需要和能力各不相同，工作动机是复杂多变的，难以统一、明确概述
2. 人在组织中的工作和生活条件是不断变化的，因此会「不断产生新的需求
和动机」
3. 人在不同组织和不同部门当中，可能产生的动机模式
4. 一个人是否愿意为组织出力，取决于他本身的「动机构造模式」：同事关系、
工作能力、工作性质
5. 人们可以根据自己的动机、能力及工作性质对不同管理方式做出不同反应
;
*****_:
「复杂人」管理
1.采用不同的组织形式来提高管理效率
2.采用富有弹性、灵活多变的领导方式
3.关注个体之间的差异性
;
*****_:
「复杂人」评价
强调针对不同的情况和不同的人应灵活采取相应的管理措施，这对管理工作有一定
启发意义
;

*** 关于个体行为的解释
**** 华生的行为主义理论
*****_:
「华生行为主义」观点
1.学习是建立条件反射的过程
2.心理学研究是可测量和刺激的反应
3.行为源于后天学习
4.刺激影响行为（S-R模式）
;
*****_:
评价
1.否认遗传的作用
2.片面夸大环境和教育的作用
;
**** 新华生主义
*****_:
「新华生主义」观点：S-O-R模式，增加了「因素」O
;
*****_:
<&star>「新华生」理论内容
1.「<&people>托尔曼」的整体行为主义
2.「<&people>赫尔」的假设-演绎系统
3.「<&people>斯金纳」的操作性条件作用
;
*****_:
「托尔曼」理论
1.目的性的行为主义
2.固有决定因素
;
*****_:
「赫尔」理论
<&star>赫尔是「内驱力理论」的主要代表人物，他认为有机体的需要产生内驱力，
内驱力激发有机体行为，内驱力包括：「原始性内驱力」和「继发性内驱力」
;
*****_:
「斯金纳」理论
1.斯金纳是新华生主义「<&star>最具代表性人物」
2.斯金纳提出了「强化理论」
3.主张不要中间变量，反对任何形式的内因论，认为强化行为、改变行为的主要动力
是有机体“操作”环境的结果
;
**** 卢因的观点
*****_:
<&star>「<&people>库尔特卢因」是著名的「群体动力论」创始人，他认为，人的
行为动向取决于「内部立场」和「情景立场」，也就是情景因素的相互作用。
公式：B = f(P, E)，B=个体行为，P=内部驱动力，E=群体环境
;
*****_:
「群体动力」的内涵
指群体中各种因素“力”的相互作用，并对群体成员在资源利用、任务实施及关系维护
等方面产生的影响力
;
*****_:
「群体动力」的理论启发
群体理论启发人们要学会从「内因的角度」去考察、研究群体行为产生发展的规律，
从群体成员的关系及整个群体分为中把握群体行为的变化过程
;
**** 个体行为规律
*****_:
<&star>「行为」的概念
人的行为是指人的「有目的」的活动，包括人的欲望、动机、情感、态度及意志在
行为上的表现
;
*****_:
<&star>「行为」的特征
1.目的性
2.自主性
3.社会性
4.连续性：思想观念一旦形成，便具有相对稳定性
5.持久性：根据需求层次理论，需要使无止境的
6.可塑性：行为随着思想、时间、地点、条件变化发生变化
;
*****_:
「行为模式」
1.S-R：【刺激】【神经系统】【反应】
2.S-O-R：【刺激】【心理加工】【反应】
3.B=f(P,E)：【行为】=f(【个体】,【环境】)
;
*****_:
「行为的规律」
      ├─客观环境
      │ └─主观需要
      │   └─内在动机
      │     └─具体行为
      └───────└─方向目标
;
*****_:
「个体行为分析」
个体行为
- 个人因素
  * 外在动机
  * 内在动机
    % 积极动机
    % 消极动机
- 环境因素
;

*** 影响人的行为的心理因素分析
**** 心理过程
*****_:
「心理过程」是人心理活动发生、发展的过程，它是指在客观事物的作用下，
在一定的时间内大脑反应客观现实的过程，包括「认识、情感、意志」过程
;
*****_:
「认识过程」是人的「心理过程的初始阶段」，它是通过个体的感觉、知觉、
记忆、想象、思维等活动对事物属性及各方面联系的综合反应过程，认识
过程是个体「心理活动过程的基础」，是个体「行为发生的前提条件」，
包括「认知阶段」和「知识阶段」
「认知形成阶段」包括「感觉」和「知觉」
「认知发展阶段」包括「记忆」、「想象」、「思维」
「知识阶段」是认识的高级阶段，即理性认识阶段
;
*****_:
「情感过程」表现在三个方面「面部表情」、「声调」、「动作表现」
情感与情绪的关系：
1.情绪：短暂、不稳定、冲动、情境性
2.情感：长久、深远
3.情绪变化受已形成情感制约
4.离开具体情绪过程，情感及其特点无从表现和存在
;
*****_:
「意志过程」意志是个体自觉地确定目的，根据目的调节、支配行动，
并努力克服困难，实现预定目标的心理过程
<&star>特点：
1.是「有意识、有目的」的活动
2.是自觉克服困难的活动
3.是由一系列的「随意活动」实现的，对意志调节的作用表现在两个方面
  a)激励；b)克制
<&star>意志（品质）的表现
1.坚毅性
2.果断性
3.自制性
;
**** 个性心理
*****_:
<&star>「个性心理」的含义
又称人格，是个体带有倾向性的、比较稳定的、本质的心理特征的总和，
它是「个体独有的」并与其他个体区别开来的整体特性
;
*****_:
「个性心理」的构成
1.个性倾向性：个体在和客观现实交互作用的过程中，对事物所持有的看法、
态度和倾向
2.个性心理特征：能力、气质、性格等心理机能的特殊结合
;

** 个体心理与行为
*** 需要、动机与行为
**** 需要、动机及行为规律
*****_:
「个体行为规律」
【刺激】-【需要】-【动机】-【行为】-【目标】-【新的需要】
;
**** <&star>需要与动机
*****_:
<&star>「需要」定义
需要就是人对事物的「欲望和要求」
;
*****_:
<&star>「需要」的特点
1.指向性
2.多样性
3.层次性
4.潜在性
5.可变性
6.社会制约性
;
*****_:
<&star>「动机」定义
动机指激励人们去行动，以达到一定目标的「内在动因」
心理学上把引起个体行为、维持该行为并将这一行为导向满足某种需要
的「欲望、愿望、信息」等心理因素叫做动机
;
*****_:
「需要」与「动机」的关系
1.需要使人的积极性的「基础和根源」所在，动机则是推动人类进行
活动的「直接原因」
2.动机是在需要的「基础」上产生的，但是需要并不必然导致动机
产生
3.需要转化为动机必须具备两方面条件：一是「对象的确定」，二是
「需要达到一定强度」
;

**** <&star>动机与行为
*****_:
「动机」与「行为」的关系
1.人的行为是由动机「支配」的，动机是由需要「引起」的
2.动机是满足需要、进行活动的念头或想法
3.动机是行为的「直接原因」，驱动人们从事某种行为并规定「行为
方向」
;
*****[#lightblue]:
<&star>「动机」的三种机能
动机具有「原始性、内隐性及实践活动性」的特征，因此具有
一下三种机能
1.「始发机能」：动机是个体行为发生的直接原因
2.「选择机能」：动机指导人们做出选择
3.「强化机能」：行为结果的好坏，会驱使动机重复出现或
不再出现
;
*****_:
<&star>「动机」与「行为」的关系
1.动机是行为发生的「直接内动力」，行为是动机的「外在表现」
2.人的动机与行为关系是很「复杂」的
  1）同一动机可以引发多种不同行为
  2）同一行为可以源自不同动机
  3）一种行为可能由多种动机所引发
  4）合理的动机可能引起不合理的、错误的行为
  5）错误的动机会被外表积极的行为所掩饰
;
*****_:
<&star>「需要」、「动机」及「行为」之间的关系及发展规律
「需要」-（心理紧张）-「动机」-（目标导向行为）-
（目标行为）-「需要满足」-「新需要」
;

*** 价值观、态度与行为
**** 价值观
*****_:
<&star>「价值观」的含义
价值观是指一个人对周围客观事物的意义、重要性的「总评价」
和「总看法」，是一个人基本的信念和判断
价值观是一套「价值体系」，并且以多元化的价值观为基础
;
*****_:
「价值观」属性
1.「内容属性」：指某种行为模式或存在的状态「是否重要」
2.「强度属性」：界定某种行为模式或存在状态的「重要程度」
;
*****_:
「价值观」形成
价值观随出生，在家庭和社会影响下形成，并稳定下来。
1.所处的社会环境
2.家庭经济条件和社会地位
3.父母职业和价值观
4.早期的学校教育
5.广播、电视、报刊等媒体影响
6.「时代属性」和「社会属性」
;
*****_:
<&star>「价值观」的作用
1.是研究各个成员对组织「认同程度」的核心衡量标注
2.是了解组织成员的「态度」及「动机」基础，管理者可在此
基础上对组织成员进行行为分析
3.价值观会使个体对那些不被其所在群体或组织接受的信仰、
态度及行为进行「合理化」，以解决内心的冲突，进而提高
个体「道德感」和「自我效能感」
4.价值观会影响企业「领导人的决策行为」
;

**** 态度
*****_:
<&star>「态度」的概念
指个体对某一对象所持有的「评价和行为趋向」。或者说，
态度是一种带有评价性与感情倾向性的「主观感受与意识形态」
;
*****_:
<&star>「态度」的心理结构
1.「知觉成分」：指个体对客体的理解和价值评判
2.「情感成分」：指个体对客体的情感体验。包括情绪和情感，
占据「关键性地位」
3.「行为或意向成分」：指个体对客体的行为准备状态及行为
反应倾向
;
*****_:
<&star>「态度」的功能
1.调整功能：能够帮助个体更好的适应环境
2.自我保护功能：使个体在收到挫折时更好地保护自己
3.价值表现功能：用其所持有的态度表现自己所推崇的价值观
4.知识功能：寻求一种稳定的、一致的或可以预测的行为倾向
;
*****_:
「态度」对「行为」的影响
1.态度影响认知和判断
2.态度影响行为效果
3.态度影响忍耐力
4.态度影响相容性
;
**** 工作满意度
*****_:
<&star>「工作满意度」概念
是指人们体验到的一种愉悦或积极的情绪状态，这种情绪
状态是人们通过对自己的「工作或工作经验」进行评价而
产生的
;
*****_:
「工作满意度」的主要影响因素
1.工作的「挑战性」
2.「公平」的报酬
3.支持性的工作环境
4.和睦融洽的同事关系
;

*** 知觉与行为
**** 知觉和社会知觉的内涵与特征
*****_:
<&star>「知觉」的内涵
指「直接作用于」感官的客观事物的「整体属性」在人脑的反应，
它是在感觉的基础上产生的，是对感觉信息的「加工、整合、解释」
的过程
;
*****_:
<&star>「知觉」的种类
根据人脑对事物特性的认识，将知觉分为「空间知觉」、「时间知觉」
「运动知觉」、「错觉」
「空间知觉」包括：形状知觉、大小知觉、方位知觉、距离知觉
「时间知觉」是对事物「延续性及顺序性」方面的信息处理
「运动知觉」是物体在「空间位移」等方面的信息
「错觉」是对客观现实「不正确」的知觉
;
*****_:
 <&star>「知觉」的特征
1.选择性
2.整体性
3.理解性
4.恒常性
;
*****_:
<&star>「社会知觉」的内涵
社会知觉是在知觉过程中出现的一种心理过程，是社会生活中的客观
事物在人们头脑中的反应。总之它是个体在「社会环境中」对某个
具体「个体或群体心理状态、行为动机和意向」做出推测判断的过程
;
*****_:
<&star>「社会知觉」的特征
1.认知对象的「独特性」
2.知觉过程的「双向作用性」
3.信息加工的「特殊性」
;

**** 知觉过程
*****_:
「知觉过程」五个阶段
1.观察：运用感觉器官了解客观事物
2.选择：根据自己需要、动机等对知觉对象的取舍
3.组织：运用思维力量把感知信息与大脑整合
4.解释：运用概念、判断及推理是对象有一定意义
5.反应：个体对知觉对象的解释最终行为表现
;
**** 影响知觉的因素分析
*****_:
「影响因素」
1.主观因素
1）兴趣和爱好
2）需要和动机
3）知识和经验
4）个性特征
2.知觉对象的特征
1）简明性规则：接近律、相似律、闭锁律、连续律
3.知觉环境
1）物理环境
2）社会环境
;
**** <&star>知觉偏差
*****[#lightblue]:
<&star>常见「知觉偏差」
1.「首因效应」：本质上是一种「优先效应」，当不同信息相互结合，
人们倾向关注「最前面」的信息
2.「近因效应」：人们在知觉过程中，「最后」给人留下印象冲淡过去
获得的印象
3.「晕轮效应」：知觉过程中常从或好或坏的「局部」印象出发，进而
扩展到「全部」的或好或坏，具有「以偏概全、以点盖面」特点
4.「投射效应」：也称「假定相似」，通常指人们通过将「自己的品质
投射到他人身上」，从而形成的关于他人的印象
5.「心理定势」：人们在认识特定对象时心理上的「准备状态」
6.「对比效应」：对两个或两个以上对象进行知觉时，人们不自觉将
其放一起「进行比较」，而不考虑客观标准
7.「刻板效应」：指对「某一类」事物或人产生固定的、具有概括性
的、笼统的印象
;
**** 归因理论与倾向
*****_:
「归因」的内涵
指人们利用相关信息资源，对自己或他人的举止进行「分析、判断并
推论其原理」的过程
;
*****_:
「归因理论」的含义
是关于某种「行为及其动机及价值取向」等属性或逻辑结合的理论，
它主要研究人们如何从主观上把某种欣慰表现和与其相应的其他
内外属性或倾向逻辑结合在一起的原理
1.「<&star><&people>海德」的「恒常原因」归因理论
海德是「归因研究的创始人」，把人的行为解释为两种「外部归因」
和「内部归因」
2.「<&people>凯丽」的「三要素」理论
进一步补充海德的理论，总结三个要素：「特殊性」、「共同性」
和「一贯性」
3.「<&people>罗特」的「控制源」理论
他认为，对于积极或消极时间原因的预料是不同的，「内控者」、
「外控者」和「控制源影响」
4.「<&people>韦纳」的「成就归因」理论
人们解释成功与失败往往有四种原因：能力、努力、难度、运气
1）控制点维度（内部、外部）
2）稳定性维度
3）可控性维度
;

*** 个性与行为
**** 个性概述
*****_:
<&star>「个性」的概念
个体拥有的并带有「倾向性的、经常的、本质的、比较稳定的」心理特征和品质的总和
存在于个体的生理素质基础之上，并在一定社会条件下「通过社会实践活动形成和发展」
个性是概括或抽象出一个人通过学习形成的「个人特点」以及「其对世界的知觉和所持
态度」的集合，是对一个人的「整体性描述」
;
*****_:
「个性」内容
1.个性倾向性：兴趣、爱好、需要、动机、态度、信念、理想、价值观
2.个性心理特征：气质、能力、性格
;
*****_:
<&star>「个性」的特征
1.差异性：遗传因素、教育学习、成长经历不同
2.倾向性：对客观事物持有态度和看法不同
3.稳定性：一旦形成便相对稳定
4.整体性：个性是一个统一体，是所有心理特征的结合
5.社会性：受到社会环境影响
;
**** 气质与行为
*****_:
<&star>「气质」的定义
是人们典型、稳定的心理特征，是人「天生的」并表现在心理活动「动力」
方面的个性心理特征，是自然特征和精神风貌的集中体现
1.气质是「先天」的个性心理特征
2.气质是人的心理活动的「动力」特征：心理过程的速度、稳定性、强度、指向性
;
*****_:
<&star>「气质」的类型
1.胆汁质：情感快而强烈，具有外倾性，具有很高的兴奋性和较弱的抑制过程
2.多血质：感情速度快，强度比较温和，善于交往并容易适应环境
3.粘液质：心理和行为迟缓，但想象力丰富，心平气和、沉着冷静、有忍耐力
4.抑郁质：情感活动非常缓慢，具有内向性，多愁善感容易神经过敏
;
**** 能力与行为
*****_:
<&star>「能力」的定义
能力是一个人「顺利完成某种活动」而在主观方面必须具备的心理特征。
能力是影响人们活动效果的基本因素
;
*****_:
<&star>「能力」的分类
1.一般能力：也称智力，是人们完成一切活动所必须的能力集合
2.特殊能力：指在特殊活动领域发生作用的能力
;
*****_:
<&star>「能力」的影响因素
1.自然素质：能力发展的基础和必要前提
2.社会实践：社会实践的广度和深度决定能力的发挥程度
3.个性因素：个人对自己的要求，生活态度
;
**** 性格与行为
*****_:
<&star>「性格」重要性
性格是个性中「最为重要」、「最为显著」的心理特征，在个性中起着
「核心的作用」，是一个人区别其他人的「集中体现」
;
*****_:
<&star>「性格」的定义
性格是一个人「对现实的态度」，以及在习惯化的「行为方式」中
表现出来较为稳定的心理特征
;
*****_:
<&star>「性格」的分类
1.依据心理活动的「优势性」划分：理智型；情绪型；意志型
2.依据个体「对现实的态度」划分：外倾型；内倾型
3.依据个体「独立型」划分：独立型；顺从型
4.「五种性格特征」划分：外向与内向、情绪适应性、易相处性、
谨慎程度、接受新经验的开放度
;
*****_:
「性格」的培养
1.建立正确的个性倾向系统
2.培养坚强的一致
3.形成自我教育能力
;

**** 情绪与行为
*****_:
「情绪」的概念
情绪指个体受到某种刺激后所产生的身心激动的状态
;
*****_:
「情绪」的特征
1.非自发性
2.短暂性
3.是一种主观的意识体验
4.会产生生理唤醒
;
*****_:
「情绪」的维度
1.种类：厌恶、愤怒、悲伤、害怕、惊奇、快乐
2.强度：激烈程度不同
3.频率和持久性：工作岗位性质要求
;
*****_:
「情绪」管理
1.情绪劳动：工作表现「令组织满意」的状态
2.情绪智力：表现在自我意识、自我管理、自我激励、
感同身受、社会技能五个方面
;
*****_:
<&star>「情绪」在组织行为中的应用
1.选聘员工：可以有效识人
2.决策：积极的情绪有利于正确角色
3.创造力：积极的情绪使思维灵活
4.激励：提高积极性
5.领导力：管理者把情绪与一个吸引人的愿景结合有效管理
6.谈判：谈判是一个情绪交互过程
;

*** 组织承诺与组织公民行为
**** 组织承诺
*****_:
<&star>「组织承诺」的内涵
组织承诺也叫「组织认同感」、「组织归属感」，是员工对特定组织
及其目标的认同、情绪依赖及参与程度
;
*****_:
<&star>「组织承诺」三要素
1.感情承诺：员工对组织的感应依赖、认同和投入
2.持续承诺：考虑到跳槽成本而不愿离职的态度和行为
3.规范承诺：因为社会责任而留在组织内的承诺
;
*****_:
建立「组织承诺」
1.建立高情感承诺
2.建立财务类持续承诺
;
**** 组织公民行为
*****_:
<&star>「组织公民行为」的含义
指个体的行为是「自主的」，并非直接由正式的奖惩体系引发的，
一般包括：无私并主动「帮助别人」、主动「参与组织活动」、承担
超过常规的任务要求等
;
*****_:
「组织公民行为」的特点
1.人们会经常主动自发地付出额外的心力，从事利于组织的事情
2.是一种自我裁量的自动「自发行为」
3.它的出现于正式的「报酬」并不直接相关
4.对于组织长期效能及成功运作有「关键作用」
;
*****_:
<&star>「组织公民行为」的作用
1.自觉维护组织运行，「减少矛盾冲突」
2.使组织拥有「资源」摆脱束缚，投入到各种生产活动
3.促进员工及管理人员「生产效率」提高
4.有效「协调」团队成员和工作群体的活动
5.能构建良好的「企业文化」，增强组织的吸引力和优秀人才能力
6.无形影响组织「绩效」
;
*****_:
「组织公民行为」在管理实践的应用
1.组织公民行为的形成依赖工作环境的构建
2.行为科学原理对行为的塑造
1）强化行为的重复发生
2）情境迁移影响行为改变
3）运用角色榜样促进学习
;
*****_:
「组织公民行为」的负面影响
为获取更大利益（表现、晋升、引起重视），忽视自己的工作，
起负面作用，引起其他员工效仿
;

@endmindmap