@startmindmap

* 战略决策阶段（一）

** 企业总体战略
*** 企业发展型战略
**** 识记
*****_:
企业发展型战略的含义：
;
*****_:
企业发展型战略的特点：
;
*****_:
密集型战略：
;
*****_:
市场渗透战略：
;
*****_:
市场开放战略：
;
*****_:
产品开发战略：
;
*****_:
一体化战略：
;
*****_:
多元化战略：
;
*****_:
横向一体化战略：
;
*****_:
纵向一体化战略：
;
*****_:
相关多元化战略：
;
*****_:
非相关多元化战略：
;
**** 领会
*****_:
企业发展型战略各种类型优点、缺点、适用条件：
;
**** 简单应用
*****_:
联系实际对企业各种类型发展战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例对企业发展战略不同选择分析并提出自己的建议：
;

*** 企业稳定型战略
**** 识记
*****_:
企业稳定型战略的含义：
;
*****_:
无变化战略：
;
*****_:
维持利润战略：
;
*****_:
暂停战略：
;
*****_:
谨慎实施战略：
;
**** 领会
*****_:
企业稳定型战略的特点：
;
*****_:
企业稳定型战略的适用条件：
;
**** 简单应用
*****_:
联系实际对企业稳定型战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例资料分析企业不同类型的稳定战略应用和决策：
;

*** 企业收缩型战略
**** 识记
*****_:
企业收缩型战略的含义：
;
*****_:
适应型收缩战略：
;
*****_:
失败型收缩战略：
;
*****_:
调整型收缩战略：
;
*****_:
抽资转向战略：
;
*****_:
放弃战略：
;
*****_:
清算战略：
;
**** 领会
*****_:
企业收缩型战略的特点：
;
*****_:
企业收缩型战略的使用条件：
;
**** 简单应用
*****_:
联系实际对企业收缩型战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例资料分析企业不同类型的收缩战略的应用和决策：
;

** 企业竞争战略
*** 企业竞争战略概述
**** 识记
*****_:
企业竞争战略的概念：
;
*****_:
企业竞争战略要解决的核心问题：
;
**** 领会
*****_:
竞争战略和发展战略的关系：
;
*****_:
企业竞争战略的构成要素：
;

*** 总成本领先战略
**** 识记
*****_:
总成本领先战略的概念：
;
*****_:
总成本领先战略的实质：
;
**** 领会
*****_:
总成本领先战略的优点和缺点：
;
*****_:
总成本领先战略的适用条件：
;
*****_:
总成本领先战略的风险：
;
**** 简单应用
*****_:
能联系实际对总成本领先战略及实现途径分析：
;
**** 综合应用
*****[#lightblue]:
结合案例对企业总成本领先战略综合分析：
;

*** 差异化战略
**** 识记
*****_:
差异化战略的含义：
;
**** 领会
*****_:
差异化战略的优势与风险：
;
*****_:
差异化战略的实现途径：
;
*****_:
差异化战略的使用条件：
;
*****_:
差异化战略的实施：
;
**** 简单应用
*****_:
能联系实际对差异计划战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例材料对企业差异计划战略综合分析：
;

*** 集中化战略
**** 识记
*****_:
集中化战略的含义：
;
*****_:
集中化战略的核心：
;
**** 领会
*****_:
集中化战略的优势与风险：
;
*****_:
集中化战略的使用条件：
;
*****_:
集中化战略的实施方法：
;
**** 简单应用
*****_:
能联系实际对集中化战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例材料对集中化战略综合分析：
;

*** 融合战略
**** 识记
*****_:
融合战略的概念：
;
*****_:
成本导向型融合战略：
;
*****_:
差异化导向型融合战略：
;
*****_:
成本-差异化导向型融合战略：
;
**** 领会
*****_:
融合战略的特点：
;
*****_:
不同类型融合战略的基本内容：
;
*****_:
融合战略的构成要件：
;
**** 简单应用
*****_:
结合实际对融合战略实施影响因素和条件进行分析：
;
*****_:
能联合实际对融合战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例资料对企业融合战略进行综合分析：
;

** 企业国际化经营战略
*** 企业国际化经营战略概述
**** 识记
*****_:
企业国际化经营的概念：
;
*****_:
企业国际化经营战略的概念：
;
*****_:
生产全球化观念：
;
*****_:
产品整体化观念：
;
**** 领会
*****_:
企业国际化经营战略的目标：
;
*****_:
企业国际化经营战略的思想：
;

*** 企业国际化经营战略的类型及其决策
**** 识记
*****_:
反回头战略：
;
*****_:
技术带动出口战略：
;
*****_:
商品出口战略：
;
*****_:
合资经营出口战略：
;
*****_:
加工出口战略：
;
*****_:
境外投资战略：
;
*****_:
跨国公司战略：
;
*****_:
本国中心战略：
;
*****_:
多国中心战略：
;
*****_:
全球中心战略：
;
**** 领会
*****_:
按产品技术来源划分国际化经营战略类型：
;
*****_:
按企业国际化发展不同划分国际化经营战略类型：
;
*****_:
按企业生产经营行为标准不同划分国际化经营战略类型：
;
**** 简单应用
*****_:
对企业国际化经营战略类型选择作出分析：
;
**** 综合应用
*****[#lightblue]:
对现实企业在实施国际化济宁战略的类型选择、关键问题作出分析：
;

*** 企业国际化经营战略的实施措施
**** 领会
*****_:
企业国际化经营战略实施的关键问题：
;
*****_:
企业国际化经营战略的具体措施：
;
**** 简单应用
*****_:
对现实企业在实际国际化经营战略时的具体措施作出分析：
;

** 企业市场营销战略
*** 市场营销战略概述
**** 识记
*****_:
市场营销战略的概念：
;
*****_:
市场营销战略决策的内容：
;
**** 领会
*****_:
市场营销战略的实质：
;
*****_:
市场营销战略的地位：
;

*** 目标市场战略
**** 识记
*****_:
目标市场战略的含义：
;
*****_:
市场细分的概念：
;
*****_:
市场定位的概念：
;
**** 领会
*****_:
市场细分的作用与理论基础：
;
*****_:
市场细分的依据：
;
*****_:
市场细分的方法与有效性：
;
*****_:
评价细分市场：
;
*****_:
选择目标市场：
;
**** 简单应用
*****_:
目标市场营销战略的选择：
;
*****_:
市场定位战略的实际应用：
;


*** 营销组合战略
**** 识记
*****_:
营销组合战略的概念：
;
**** 领会
*****_:
营销组合战略的类型：
;
*****_:
营销组合战略的选择：
;
**** 简单应用
*****_:
营销组合战略实际应用分析：
;

*** 企业品牌战略
**** 识记
*****_:
品牌的概念与品牌价值：
;
*****_:
品牌战略的概念：
;
**** 领会
*****_:
企业品牌战略的内容：
;
*****_:
企业品牌战略的典型类型：
;
*****_:
企业品牌战略的管理方法：
;

*** 市场营销新谋略
**** 领会
*****_:
直复营销：
;
*****_:
顾客满意营销：
;
*****_:
关系营销：
;
*****_:
文化营销：
;
*****_:
绿色营销：
;
*****_:
整合营销：
;
*****_:
网络营销：
;

@endmindmap