@startmindmap

* 战略决策阶段（一）

** 企业总体战略
*** 企业发展型战略
**** 识记
*****_:
「企业发展型战略」的含义：是一种使企业在现有战略基础之上想更高一级目标发展的谋划
和方略，即在一定时期内对企业发展方向、发展速度和质量、发展点及能力的重大选择、
规划和策略
1. 发展为导向
2. 开发新产品
3. 开拓新市场
4. 新的生产方式和管理方式
5. 扩大规模、提高竞争力
;
*****_:
企业发展型战略的特点：
1. 投入大量资源、扩大产销规模，目的是提高市场占有率，增强企业竞争力
2. 强调通过创造新产品和新需求来引导消费、创造消费
3. 用以获得较好的规模经济效益，从而降低生产成本，获取超额利润
;
*****_:
「密集型战略」：也称加强型战略，是指企业在原有业务范围内，集中力量以快于过去过去增长
速度来提高某种产品的销售额或市场占有率以求得成长的战略
优点：经营目标聚集，管理方便，有利于集中使用企业资源，达到规模经济效益
缺点：环境适应能力差，经营风险大
包括：「市场渗透」、「市场开发」、「产品开发」
;
*****_:
市场渗透战略：企业通过更大的市场营销努力，提高现有产品的服务份额
;
*****_:
市场开放战略：由「现有产品」和新市场组合而产生的战略
;
*****_:
产品开发战略：向现有市场提供新产品或改进产品，满足现有市场不同层次需要
;
*****_:
「一体化战略」：指企业充分利用已有产品、技术、市场的优势，沿其经营链条的深度
和广度发展的一种战略。包括「横向」、「纵向」
;
*****_:
「多元化战略」：又称多样化战略，是相对企业专业化经营而言，指一个企业在多个行业中
进行经营，内容包括产品多元化、市场多元化、投资区域多元化、资本多元化。
分类：「相关多元化」、「非相关多元化」
;
*****_:
横向一体化战略：水平一体化，指通过联合、购买、合并、集团化等方式，与处于相同
行业、生产同类产品和工艺相近的企业实现联合，目的扩大规模、降低成本、巩固地位
;
*****_:
纵向一体化战略：垂直一体化，是一种在生产、供销的两种不同方向上扩大企业生产经营规模
的发展战略。包括「前向一体化」战略和「后向一体化」战略
;
*****_:
相关多元化战略：是指企业以现有业务为基础进入相关产业或市场
;
*****_:
非相关多元化战略：是指企业进入与现有产品或服务在技术、市场等方面没有关联的新行业
或新领域战略
;
**** 领会
*****_:
企业发展型战略各种类型优点、缺点、适用条件：
优点：
1.企业通过发展可以扩大自身价值
2.创造更高的经济效率和效益，增强企业活力
3.可以保持竞争实力，实现特定的竞争优势
缺点：
1.盲目发展及为发展而发展，破坏企业资源平衡
2.过快的发展可能降低企业综合素质，易导致内部危机或混乱
3.领导者易忽视产品服务或质量
适用条件：
1.宏观经济和行业发展状况良好
2.市场需求呈增长趋势
3.符合国家产业发展战略要求
4.各种资源保障
5.企业文化的保障
;
**** 简单应用
*****_:
联系实际对企业各种类型发展战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例对企业发展战略不同选择分析并提出自己的建议：
;

*** 企业稳定型战略
**** 识记
*****_:
企业稳定型战略的含义：指限于经营环境和内部条件，企业在战略期所期望达到的经营
状况基本保持在目前状况和水平上的战略
;
*****_:
无变化战略：基本没有变化战略。企业过去经营相当成功或企业并不存在重大经营问题和隐患
;
*****_:
维持利润战略：为了维持利润水平而牺牲企业未来成长的战略。为了暂时渡过难关，在经济
不景气被采用
;
*****_:
暂停战略：在一段较长时间的快速发展后，企业遇到问题使得效率低下，采用暂停战略
;
*****_:
谨慎实施战略：在外部环境的某一重要因素难以预测或变化趋势不明显，企业决策有意识
放慢实施进度，步步为营
;
**** 领会
*****_:
企业稳定型战略的特点：
1.企业对过去经营业绩满意，决定追求既定的经营目标
2.企业在基本维持现有的产销规模、市场占有率和竞争地位，蓄势待发，后续发力
3.继续用基本相同的产品或劳务为原有的顾客服务
4.力争保持现有的市场占有率和产销规模或者略有增长，稳定和巩固企业现有的竞争地位
5.在战略期内，每年所期望取得的成就按大体相同的比率增长，从而实现稳步前进
;
*****_:
企业稳定型战略的适用条件：
1.宏观经济发展状况
2.产业技术创新状况
3.消费需求偏好变动状况
4.产品或行业的寿命周期状况
5.竞争格局
6.企业资源状况
;
**** 简单应用
*****_:
联系实际对企业稳定型战略进行分析：
分类：
(1)按偏离战略起点的程度(无增；微增)；
(2)采取的防御态势(阻击式；反应式)
;
**** 综合应用
*****[#lightblue]:
结合案例资料分析企业不同类型的稳定战略应用和决策：
稳定型战略的优点
(1)维持状态，避免开发的投入，风险较小
(2)不需改变资源的分配模式，大大减少资源重新组合所必然造成的巨大浪 费和时间上的损失
(3)可以保持人员的相对稳定，充分利用人才，减少各种招聘及培训的费 用
(4)比较容易保持企业经营规模和经营资源，能力的平衡协调，有助于防 止过快，过急而导致的重大损失
稳定型战略的弊端
(1)一旦打破需求，竞争的平衡，则容易让企业陷入困境
(2)往往容易使企业的风险意识减弱，甚至形成惧怕风险，回避风险的企业文化
;

*** 企业收缩型战略
**** 识记
*****_:
企业收缩型战略的含义：指企业从目前的战略经营领域和基础水平收缩和撤退，且偏离
战略起点较大的一种经营谋划与方略
;
*****_:
适应型收缩战略：指企业为「适应外部环境」而采取的战略（整个行业-被动）
;
*****_:
失败型收缩战略：企业在「经营失误」造成企业竞争地位下降，用收缩型战略才能减少损失
保存企业实力（自身企业-被动）
;
*****_:
调整型收缩战略：企业为了利用环境中出现的新机会，谋求更好发展，主动做出调整，
而采取长远目标的、「积极」的收缩型战略（主动）
;
*****_:
抽资转向战略：企业对原有业务领域进行压缩投资，控制成本以改善现金流，为其他业务
领域提供资金
;
*****_:
放弃战略：指将企业的一个或几个主要部门转让、出卖或停止经营
;
*****_:
清算战略：指通过卖掉资产或停止整个企业的运行而终止一个企业的存在
;
**** 领会
*****_:
企业收缩型战略的特点：
1.经营规模缩小：对现有产品或市场实行收缩，调整，撤退
2.经营投入压缩：严格控制削减费用支出，投入最低限度经营管理
3.存在短期性：具有过渡的性质
;
*****_:
企业收缩型战略的适用条件：
1.外部环境变化
2.企业经营失误
3.新的发展机会
;
**** 简单应用
*****_:
联系实际对企业收缩型战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例资料分析企业不同类型的收缩战略的应用和决策：
类型：
(1)按促使企业采取紧缩型战略的基本原因划分(适应性; 失败性;调整性;)
(2)按促使企业采取紧缩型战略的基本途径划分(选择性收缩;转向战略; 放弃战略;清算战略)
利弊：
利:
1.可以使企业降低各种费用，及时渡过难关
2.可以使企业更加有效的配置资源，提高经营素质，发挥和增强企业优势
3.可以避免竞争，防止两败俱伤
弊:
1.削弱技术研究和新产品开发能力，影响企业的长远发展
2.会对人员进 行调整，从而导致企业人心涣散，效率降低
3.将导致企业总体的供求关系缩小， 影响经济的回升和行业的衰退
;

** 企业竞争战略
*** 企业竞争战略概述
**** 识记
*****_:
企业竞争战略的概念：又称业务层次战略或SBU战略，在企业总体战略的制约下，
指导和管理具有战略经营单位的计划和行动，中心内容是建立竞争优势
;
*****_:
企业竞争战略要解决的核心问题：「竞争优势」是企业竞争战略的核心
;
**** 领会
*****_:
竞争战略和发展战略的关系：
1.竞争战略着眼竞争，发展战略求发展
2.竞争战略侧重于搞市场及竞争关系分析（<b>外部</b>），而发展战略侧重于搞
发展基础、发展条件机遇分析（<b>内部</b>）
3.竞争战略要素是竞争内容、竞争对手、竞争策略、竞争手段等，发展战略要素
是发展方向、发展步骤，发展重点等
4.两种战略虽然有联系、有共同点，但是两种不同性质的战略
;
*****_:
企业竞争战略的构成要素：
1.经营理念
2.优势资源
3.战略优势
4.资源力量
;

*** 总成本领先战略
**** 识记
*****_:
总成本领先战略的概念：低成本战略，指通过有效途径，使成本降低，建立竞争优势。
要求企业努力取得规模经济，以经验曲线为基础，严格控制生产成本间接费用，降低
成本到最低水平
;
*****_:
总成本领先战略的实质：通过成本优势获得价格部分的优势，进而获得市场优势
;
**** 领会
*****_:
总成本领先战略的优点和缺点：
优点：
1.抵挡现有竞争对手的对抗
2.低于购买商讨价还价的能力
3.更灵活处理供应商的提价行为
4.形成进入障碍
5.树立与替代品的竞争优势
缺点：
1.降价过度引起利润率降低
2.新加入者可能后来居上
3.丧失对市场变化的预见能力
4.技术变化降低企业资源的效用
5.容易受外部环境影响
;
*****_:
总成本领先战略的适用条件：
1.企业外部条件：
  1.市场需求有较大的价格弹性
  2.行业高度标准化
  3.实现产品差异化的途径少，多数消费者以相同的方式使用产品
  4.消费者从一个销售商转换到另一个销售商时，转换成本很小，
因而倾向于购买价格最优的产品，消费者具有较大降价谈判能力
2.企业内部条件
  1.持续的资本投资和获得资本的途径
  2.生产加工工艺技能
  3.认真的劳动监督
  4.设计容易制造的产品
  5.成本的分销系统
  6.培养技术人员
;
*****_:
总成本领先战略的风险：
1.初期投资巨大
2.技术变革滞后
3.忽视客户
4.玉玉被竞争者模仿
5.缺乏创新的激情
6.依赖价格战
;
**** 简单应用
*****_:
能联系实际对总成本领先战略及实现途径分析：
1.实现生产的规模经济
2.做好对供应商的营销
3.采用新的技术和流程来降低成本
4.建立成本为核心的企业文化
;
**** 综合应用
*****[#lightblue]:
结合案例对企业总成本领先战略综合分析：
;

*** 差异化战略
**** 识记
*****_:
差异化战略的含义：指企业凭借自身的技术优势和管理优势，向顾客提供独具特色
的产品服务，为顾客带来额外价值，使顾客满意
;
**** 领会
*****_:
差异化战略的优势与风险：
优势：
1.建立顾客对企业的忠诚度
2.企业提供差异性产品为潜在进入者设置进入壁垒
3.可以缓解公司所面临的竞争压力
4.增强企业对供应商讨价还价的能力
5.削弱购买商讨价还价的能力
6.差异化产品更好满足消费者需求，同时促使企业提高销售量或允许制定更高价格
风险：
1.多变的市场造成的风险
2.高额专属成本造成的风险
3.闭门造车造成的风险
4.丧失市场份额的风险
;
*****_:
差异化战略的实现途径：
1.「产品」差异化
2.「无形」差异化
3.「渠道」差异化
;
*****_:
差异化战略的使用条件：
1.消费者对产品有不同的需求
2.产品或服务差异化具有价值
3.差异化市场规模能够支撑差异化成本
;
*****_:
差异化战略的实施：
1.分析消费者需求
2.分析竞争对手
3.进行技术创新
4.提升服务理念
;
**** 简单应用
*****_:
能联系实际对差异计划战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例材料对企业差异计划战略综合分析：
;

*** 集中化战略
**** 识记
*****_:
「集中化战略」的含义：目标聚集战略，指把经营战略重点放在一个特定目标市场上，为特定的地区
或特定的购买者集团提供特殊的产品或服务
集中化战略包含两种形式：细分市场中寻求成本优势的「成本集中」、在细分市场寻求差异的
「差异集中」
;
*****_:
集中化战略的核心：是取得某种对特定顾有价值的专一性服务
;
**** 领会
*****_:
集中化战略的优势与风险：
优势：
1.集中资源服务于特定市场
2.以特殊的服务范围低于竞争压力
3.将目标集中于特定细分市场，企业更好调查研究(<b>知彼</b>)
风险：
1.产品的销量可能变小，产品要求不断更新，造成成本提高
2.由于企业全部力量资源都投入到一种产品的特定市场，当技术进步、替代品出现、消费偏好变化等，
目标市场与总体市场之间产品或服务需求差别变小，集中化将不复存在
3.以较宽的市场为目标的竞争者采用同样的重点集中化战略在成本上差异日益扩大，或者竞争对手从
企业的目标市场找到再细分市场，使原来使用重点集中化的企业无法生存
4.在较宽范围经营的竞争对手与采取集中化战略的企业在成本上差异日益扩大
;
*****_:
集中化战略的使用条件：
;
*****_:
集中化战略的实施方法：
;
**** 简单应用
*****_:
能联系实际对集中化战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例材料对集中化战略综合分析：
;

*** 融合战略
**** 识记
*****_:
融合战略的概念：
;
*****_:
成本导向型融合战略：
;
*****_:
差异化导向型融合战略：
;
*****_:
成本-差异化导向型融合战略：
;
**** 领会
*****_:
融合战略的特点：
;
*****_:
不同类型融合战略的基本内容：
;
*****_:
融合战略的构成要件：
;
**** 简单应用
*****_:
结合实际对融合战略实施影响因素和条件进行分析：
;
*****_:
能联合实际对融合战略进行分析：
;
**** 综合应用
*****[#lightblue]:
结合案例资料对企业融合战略进行综合分析：
;

** 企业国际化经营战略
*** 企业国际化经营战略概述
**** 识记
*****_:
企业国际化经营的概念：
;
*****_:
企业国际化经营战略的概念：
;
*****_:
生产全球化观念：
;
*****_:
产品整体化观念：
;
**** 领会
*****_:
企业国际化经营战略的目标：
;
*****_:
企业国际化经营战略的思想：
;

*** 企业国际化经营战略的类型及其决策
**** 识记
*****_:
反回头战略：
;
*****_:
技术带动出口战略：
;
*****_:
商品出口战略：
;
*****_:
合资经营出口战略：
;
*****_:
加工出口战略：
;
*****_:
境外投资战略：
;
*****_:
跨国公司战略：
;
*****_:
本国中心战略：
;
*****_:
多国中心战略：
;
*****_:
全球中心战略：
;
**** 领会
*****_:
按产品技术来源划分国际化经营战略类型：
;
*****_:
按企业国际化发展不同划分国际化经营战略类型：
;
*****_:
按企业生产经营行为标准不同划分国际化经营战略类型：
;
**** 简单应用
*****_:
对企业国际化经营战略类型选择作出分析：
;
**** 综合应用
*****[#lightblue]:
对现实企业在实施国际化济宁战略的类型选择、关键问题作出分析：
;

*** 企业国际化经营战略的实施措施
**** 领会
*****_:
企业国际化经营战略实施的关键问题：
;
*****_:
企业国际化经营战略的具体措施：
;
**** 简单应用
*****_:
对现实企业在实际国际化经营战略时的具体措施作出分析：
;

** 企业市场营销战略
*** 市场营销战略概述
**** 识记
*****_:
市场营销战略的概念：
;
*****_:
市场营销战略决策的内容：
;
**** 领会
*****_:
市场营销战略的实质：
;
*****_:
市场营销战略的地位：
;

*** 目标市场战略
**** 识记
*****_:
目标市场战略的含义：
;
*****_:
市场细分的概念：
;
*****_:
市场定位的概念：
;
**** 领会
*****_:
市场细分的作用与理论基础：
;
*****_:
市场细分的依据：
;
*****_:
市场细分的方法与有效性：
;
*****_:
评价细分市场：
;
*****_:
选择目标市场：
;
**** 简单应用
*****_:
目标市场营销战略的选择：
;
*****_:
市场定位战略的实际应用：
;


*** 营销组合战略
**** 识记
*****_:
营销组合战略的概念：
;
**** 领会
*****_:
营销组合战略的类型：
;
*****_:
营销组合战略的选择：
;
**** 简单应用
*****_:
营销组合战略实际应用分析：
;

*** 企业品牌战略
**** 识记
*****_:
品牌的概念与品牌价值：
;
*****_:
品牌战略的概念：
;
**** 领会
*****_:
企业品牌战略的内容：
;
*****_:
企业品牌战略的典型类型：
;
*****_:
企业品牌战略的管理方法：
;

*** 市场营销新谋略
**** 领会
*****_:
直复营销：
;
*****_:
顾客满意营销：
;
*****_:
关系营销：
;
*****_:
文化营销：
;
*****_:
绿色营销：
;
*****_:
整合营销：
;
*****_:
网络营销：
;

@endmindmap
