@startmindmap

* 企业经营战略
** 考试技巧
*** 题型
****_:
「单选」：10 * 1 = 10
「多选」：5 * 2 = 10
「<&pulse>判断」：5 * <b>4</b> = 20
「<&people>名词解释」：5 * 3 = 15
「<&star>简答」：5 * 5 = 25
「<&flag>论述」：2 * 10 = 20
;
*** 注意事项
****_:
判断题：错误的要写明原因
简答题&论述题：答关键点得分，分点描述，不留白
;

** <&star>企业经营管理战略<b>概述</b> 8.1%
*** 简介
****[#lightblue] <&flag>战略的产生和发展背景
*****_:
纵观国内外企业经营战略发展的历程可见，经营战略产生于
发展的背景条件主要是：
1.「需求结构」的重大变化（低层次到中高层次）
2.「市场竞争」日趋激烈（以产定销到用户至上）
3.「科学技术」的不断进步
4.「资源供应」日益紧张
5.「生态环保」要求越来越高
6.「产业结构」的快速调整
;
**** 特点
*****_:
1.「全局性」：总体发展、整体功能、总体效果
2.「长远性」：3-5年、10年、分阶段
3.「竞合性」：竞争与合作
4.「纲领性」：长远目标、发展方向
5.「应变性和相对稳定性」：非朝令夕改
;
****[#lightblue] 作用
*****_:
企业经营战略关系到企业的前途命运，在企业管理中处于
「核心地位」，作用体现在：
1.为企业的长期发展「指明方向」
2.为企业顺利发展「提供保障」
3.为企业管理「增强活力」
4.为提高经营者「管理水平」提供可靠条件
;
*** 理论形成与发展
**** 形成期
*****_:
「安索夫」（美）- “战略管理的「鼻祖」” 观点：
1.战略必须与「环境」相适应：
    稳定的环境   -> 保守稳定型
    活跃的环境   -> 效率反应型
    可预测的环境 -> 营销先导型
    可探索的环境 -> 战略探索型
    极动荡的环境 -> 开拓创造型
2.战略内容「四要素」：
    产品市场范围、成长方向、
    竞争优势、协同作用
3.企业战略计划必须有「资源」、组织保障
;
**** 发展期
*****[#lightblue]:
「迈克尔波特」- “竞争战略理论” 观点：
1.竞争因素「五力模型」：现有竞争者、潜在加入者、替代品生产者、
资源供应者、产品购买者
2.制定竞争「三大战略」：总成本领先战略、差异化战略、集中化战略
3.产品和行业有「寿命周期」，处于不同寿命周期阶段的行业，投资
战略不同
4.企业要形成竞争优势，建立起优于对手的<b>核心能力、成长能力、</b>
<b>快速反应能力、适应变化能力</b>。形成差异优势，<b>以“特”取胜</b>，
分析企业自身「价值链」
;
**** 发展期
*****_:
普拉哈拉德和加里哈默尔(<b>二哈</b>) - “企业「核心」能力理论” 企业核心能力和特点：
企业在长期的经营活动中形成了许多种能力，如战略管理、技术开发、
生产制造、市场营销、组织管理等，但「企业核心能力」是众多能力最
根本的部分，其特征是：
1.「延展性」：延展到新产品开发、创造新市场
2.「增值性」：增加顾客价值
3.「独特性」：与众不同，不被轻易模仿、掌握
;

*** 管理体系
**** 含义
*****_:
「经营战略管理」
1.狭义：企业家从战略的高度对企业的整个生产经营活动所进行的管理，具体地说是指对
<b>企业经营战略的制定过程、实施和控制和修正过程所进行的管理</b>，主要代表<b>斯坦纳</b>
2.广义：是运用战略对整个企业进行管理，<b>安索夫</b>认为：<b>企业经营战略管理是将企业日常</b>
<b>业务决策同长期计划决策相结合而形成的一系列经营管理业务</b>
;
****[#lightblue] <&pulse>构成
*****_:
1.经营战略管理「过程体系」（三阶段）：（经营战略）分析阶段；制定、决策阶段；实施、反馈阶段
2.经营战略「层次体系」（三层次）：总体经营战略（公司层）、经营单位战略（业务层）、职能层战略
3.经营战略方案的「内容体系」：多种、多层次方案的选择，包括：
    1.『经营战略思想』：是企业经营战略制定的「基本思想」
    2.『经营战略目标』：是以经营战略思想为指导，根据主客观分析，在一定时期能达到的「总水平」
    3.「经营战略重点」：指对于实现战略目标有关键作用的方面
    4.「经营战略方针」：指企业为贯彻经营战略思想、经营战略目标和经营战略重点所确定的企业生产
经营活动应遵循的「基本原则、指导规范、行动方略」
    5.「经营战略步骤」：是为实现经营战略目标而采取的有计划的「行动次序」
    6.「经营策略」：是指企业为实现经营战略目标和财务的「重要措施」和「重要手段」，具有「阶段性、
方针性、具体性、多重性」的特点
;

** 企业经营战略<b>环境分析</b> 1.3%
*** 环境概述
**** 概念
*****_:
「经营战略环境」是指影响企业全局的「客观条件」。企业经营战略环境就是影响企业经营活动的各种
力量和因素的集合
;
****[#lightblue] 重要性
*****_:
企业经营战略环境分析是经营战略管理过程的「第一个环节」。正确认识和分析企业经营战略是正确制定
经营战略的「先决条件」。企业经营战略环境的特点制约和影响着企业经营活动的「方向、内容和方式」。
企业经营战略的环境变化要求企业经营战略随之「改变」，以便更好地利用机会，「趋利避害」，开展各项
经营。企业只有不断地与环境进行「能量和信息交换」，把投入转变为产出，才能生存发展，实现企业的
战略目标
;
**** 分类
*****_:
1.宏观环境：一般环境，可能对企业活动产生影响的各种因素所构成的集合。（PEEST）
2.行业环境：中观环境，对同一行业企业都会影响的环境。（五力）
3.微观环境：具体环境，对某个企业经营产生过直接影响的力量。（五力+ 中介、公众）
4.企业环境：内部影响因素总和。（企业资源、企业文化）
;
**** 特点
*****_:
1.客观性
2.复杂性
3.关联性
4.「不确定」性
5.层次性
;
****[#lightblue] 企业与经营战略环境的关系
*****_:
1.环境对企业的影响：环境是企业赖以生存的土壤；外部环境因素影响企业内部经营；
环境制约企业经营活动和经营效率
2.企业对环境的影响：适应环境；影响环境；选择环境
;
*** 环境分析的内容
**** 宏观环境分析
*****[#lightblue]:
PEEST分析法：政治、经济（宏观、微观）、自然生态、社会、技术
;
**** 行业环境分析
*****_:
<s>行业现状及前景分析：</s>
1.行业「寿命周期」分析
2.行业规模分析
3.行业技术情况分析
4.行业内战略集团分析
;
*****_:
行业竞争结构分析（五力模型）：
1.现有竞争者之间抗衡
2.潜在竞争者进入威胁
3.替代品威胁
4.供应商议价能力
5.购买者议价能力
;
**** 微观环境分析
*****_:
概念：指对企业经营活动构成「直接影响」的各种外部力量，包括：
<s>供应者、顾客、竞争者</s>（五力）和各种公众、中介机构
;
**** 内部环境分析
*****_:
1.<b>企业一般环境分析</b>：指企业管理水平、发展情况、技术素质、
生产条件和资源情况分析
2.<b>企业经营实力分析</b>：产品竞争能力、技术开发能力、生产能力、
市场营销能力、产品获利能力
;
*** 环境分析的方法
**** SWOT分析法
*****[#lightblue]:
SWOT分析法是在「外部环境」与「内部环境」分析的基础上，把两种
分析相互结合起来寻求外部环境的「机会与风险」和内部的「优势与
劣势」的一种分析方法
1.SO：增长型战略（生产规模扩大化、市场规模扩大化、多样化经营）
2.WO：扭转型战略（克劣补短、业务转型）
3.ST：扬长避短战略（纵向一体化、横向一体化、复合多样化）
4.WT：防御型战略（市场防御型、业务防御型、业务转型）
;
**** 波士顿矩阵分析法（四象限）
*****[#lightblue]:
外在「市场增长率」和内在「相对市场占有率」
1.明星类：抓住机遇、重点投资
2.现金牛类：严格控制投资，设法获取尽多利润
3.问题类：加以完善和提高，促使成为明星
4.瘦狗类：果断放弃淘汰
;
**** 麦肯锡矩阵分析法（GE矩阵法）
*****[#lightblue]:
外在「战略经营领域吸引力」和内在「企业竞争地位」
「企业竞争地位」因素分析：
1.企业在某一经营领域的投资达到最佳投资水平的程度
2.企业实施的竞争战略当前达到竞争优势程度
3.企业目前能力达到该经营领域一流企业所需能力的程度
;
**** 内部价值链分析法
*****_:
分析强调通过对企业生产经营活动、基本职能活动、人力资源活动
的组织，达到成本最低而价值增加最大的目标
;

** 企业战略经营<b>领域分析</b> 3.7%
*** 企业战略经营领域概述
**** <&people>概念
*****_:
「战略经营领域（SBA）」：是指企业选定的「行业」和
选定的「目标市场」相结合形成的「经营场所」
「战略经营领域结构」：是指企业选择「两个以上SBA」
所构成的微观环境时空格局
;
*** 领域结构的原则
****[#lightblue] <&pulse>确定SBA结构的一般原则
*****_:
「一般原则」是指「环境引力」与「企业实力」「平衡」的原则。
任何一个SBA都是环境引力与企业实力的结合，这种结合有四种形式：
1.环境引力大、企业实力大 - 明星SBA
2.环境引力大、企业实力小 - 问题SBA
3.环境引力小、企业实力大 - 金牛SBA
4.环境引力小、企业实力小 - 瘦狗SBA
“明星SBA”实现了理想的「引力实力平衡」。“瘦狗SBA”的平衡使无前途、
失败的平衡。“问题SBA”不平衡，呈逆差，逆差扩大则消亡，缩小则转换
成“明星”。“金牛SBA”不平衡，呈顺差，可能转换为“瘦狗”
一般来说，企业实力和环境引力之间不平衡是绝对的，平衡是相对的
;
**** <s>确定SBA结构的具体原则</s>
*****_:
1.企业的生存与发展平衡的原则：保证企业健康生存、发展是企业战略
要解决的根本问题
2.企业的投入和收入平衡的原则：明星区SBA投入、收入平衡，问题、
瘦狗区SBA投入、收入成顺差，金牛区SBA投入、收入呈顺差
3.SBA的成功关键因素与企业战略优势平衡的原则：五力模型基本格局
规定了企业在行业中成功的关键因素，企业欲投资某SBA，必须在最重要
的成功关键因素有把握
4.企业内部集中性与外部适应性的统一原则：内部SBA多与少、SBA关联
强弱
;
*** <s>企业战略经营领域的分析方法</s>
**** 环境引力与企业实力对比分析法
*****_:
环境分析：一般与特殊规律、引力（或机会）、压力（或威胁）、
风险度、成功关键因素
企业分析：一般与特殊规律、优势、劣势、适应性、成功关键把握
能力
根据环境引力和企业实力形成SBA战略
;
**** SBA运行规则和战略主体、战略关系、战略关键分析
*****_:
1.运行规则：
  ①运行规则分客观规律和主观规定两种；
  ②运行规则多层多元
2.战略主体：“五力”+政策制定者、企业自身
3.战略关系：直接关系和间接关系
4.战略关键分析：影响企业生存发展的规则、
主体和关系
;
**** SBA的三类态势
*****_:
1.「发展型」态势：环境机会与企业优势结合
2.「紧缩型」态势：环境威胁与企业劣势结合
3.「稳定型」态势：环境风险度与企业适应度相适应
;

**[#lightblue] <&star>企业<b>使命</b>和战略目标 14.2%
*** 企业使命决策
****[#lightblue] 应考虑的重要因素
*****_:
口诀：<b>国企需竞争</b>
1.国家长远发展规划和产业政策
2.市场需求
3.竞争态势
4.企业实力
;
**** 使命决策内容
*****_:
1.企业性质的确定
2.企业成长方向的选择
3.经营目的的确定
4.经营哲学的选择。「经营哲学」是指企业在经营活动中对发生各种关系的认知态度总和
5.经营方针的选择。「经营方针」是企业为贯彻战略思想、实现战略目标、突出战略重点
所确定的基本原则、指导方略和行动方针
6.企业社会责任的确定
;
**** 使命应研究的问题
*****_:
1.要以「顾客的基本需求」为中心确定企业使命
2.正确的企业使命必须具有「约束力」
3.企业使命要具有「鼓动性」
;
*** 企业战略目标决策
****[#lightblue] 战略目标的作用
*****_:
1.战略目标能够实现企业外部环境、内部环境和企业能力三者之间的
「动态平衡」，使企业获得长期稳定和协调的发展
2.战略目标明确了企业的「努力方向」，使企业使命具体化和数量化，
使企业战略任务得以落实，避免落空
3.战略目标是企业战略实施的「指导原则」，能使企业中的各项资源
和力量集中起来，减少企业内部冲突，提高管理效率和经济效益
4.战略目标为战略方案的决策和实施提供了「评价标准」和考核的依据
;
****[#lightblue] 制定和选择基本要求
*****_:
1.战略目标必须有「科学依据」
2.目标必须「明确和具体」，并规定完成期限
3.目标必须具有「挑战性」，并切实可行
4.目标应突出「重点」
5.目标应形成一个「完整体系」
;
**** 决策的内容
*****_:
1.战略目标水平的选择
2.重点战略目标的决策
;
** <&star>企业总体战略 8.5%
*** 分类
**** 公司层战略
*****_:
按经营状态不同：「发展型」战略、「稳定型」战略、「紧缩型」战略
按企业经营领域不同：「专业化」经营战略、「多元化」经营战略
按主客观条件不同：「保守型」战略、「可靠型」战略、「风险型」战略
;
**** 经营单位层战略
*****_:
「产品定位」战略、「投资」战略、『竞争』战略、「合作」战略
;
**** 职能层战略
*****_:
口诀：「<b>产销人发财文</b>」
<b>产</b>品战略、市场营<b>销</b>战略、<b>人</b>力资源战略、
技术创新（研<b>发</b>）战略、<b>财</b>务战略、企业<b>文</b>化战略
;
*** 企业发展型战略
****[#lightblue] 特点
*****_:
1.资源投入量大，产销规模扩大，目的是提高产品「市场占有率」，
增强企业竞争实力
2.发展型战略要求企业不仅主动适应外部环境，而且更要通过
产品创新和市场创新「引导创造消费」
3.容易获得较好的规模经济效益，从而降低生产成本，获得
「超额利润」
;
**** 类型
*****[#lightblue]:
1.「密集型战略」：也称加强型成长战略，指企业在原有业务范围内，
集中力量以快于过去的增长速度来提高某种产品的销售额或市场占有
率以求得成长的战略。
    优点：经营目标聚集，管理简单方便，有利于集中使用企业的资源，
实现生产的专业化，达到规模经济的效益
    缺点：对环境适应能力差，经营的风险大。因为采取这种战略的惬意
生产的产品过于单一，如果长期维持这种战略，可能冒市场衰退风险
    包括：「市场渗透战略」、「市场开发战略」、「产品开发战略」
2.「一体化战略」：指企业充分利用已有的产品、技术、市场优势，
沿其经营链条向经营深度和广度发展的一种战略。
    包括：
    1.「横向一体化战略」
    2.「纵向一体化战略」
3.「多元化战略」：又称多样化战略，是相对企业专业化经营而言的，
指一个企业同时在两个或两个以上行业中进行经营，其内容包括：
产品的多元化、市场的多元化、投资区域的多元化、资本的多元化。
    缺点：1.对管理的要求更高；2.多元化战略的实施可能导致企业资金
短缺；3.由于资金分散，可能引发企业的新业务上不去，老业务元气大伤
    包括：
    1.「相关多元化战略」
    2.「非相关多元化战略」
;
*** 企业稳定型战略
****[#lightblue] 类型
*****_:
1.「无变化战略」
2.「维持利润战略」
3.「暂停战略」
4.「谨慎实施战略」
;
**** 特点
*****_:
1.企业对过去的经营业绩表示满意，决定追求现在或与过去相似的
经营目标
2.企业在基本维持现有产销规模、市场占有率和竞争地位的情况下，
调整生产经营秩序，提高管理，为将来发展做准备
3.继续用基本相同的产品或劳务为原有顾客服务
4.力争保持现有市场占有率和产销规模或略有增长，巩固企业地位
5.战略期内，每年所期望取得的成就按大体相同比率增长，稳步前进
;
**** 适用条件
*****_:
1.宏观经济发展：保持或低速
2.产业技术创新：相对成熟
3.消费需求偏好变动：变动稳定
4.产品或行业寿命周期：成熟期
5.竞争格局：竞争壁垒高，竞争对手地位稳定
6.企业资源状况：资金不足，研发力量差
;
*** 企业收缩型战略
**** 特点
*****_:
1.经营规模缩小
2.经营投入压缩
3.存在短期性
;
****[#lightblue] 类型
*****_:
1.按实施收缩型战略原因划分
1）「适应型收缩战略」
2）「失败型收缩战略」
3）「调整型收缩战略」
2.按实施收缩型战略基本途径划分
1）「抽资转向战略」
2）「放弃战略」
3）「清算战略」
;

** 企业竞争战略 1.5%
*** 企业竞争战略概述
**** 解决的核心问题
*****_:
如何通过确定顾客需求、竞争者产品及本企业产品三者之间的关系，奠定
本企业产品在市场上的特定地位并维持这一地位
;
****[#lightblue] 企业竞争战略和发展战略的关系
*****_:
1.竞争战略着眼于怎样竞争，发展战略着眼于发展
2.竞争战略与发展战略的根据不一样。竞争战略侧重于市场及竞争关系
分析，发展战略侧重于搞发展基础、发展矛盾，发展条件和发展机遇分析
3.竞争战略与发展战略要素不一样。竞争战略要素是竞争对手、竞争内容、
竞争策略、竞争手段等，而发展战略要素是发展方向、发展步骤、发展
重点、发展措施等
;
**** 构成要素（优势创建）
*****_:
1.经营理念
2.优势资源
3.战略优势
4.资源质量
;
*** 总成本领先战略
**** 实质
*****_:
通过成本优势获得价格部分的优势，进而获得市场优势。因为顾客感知的
是价格而不是企业成本，他们比较的是不同企业的价格
;
****[#lightblue] 优点与缺点
*****_:
优点：
1.抵挡住现有竞争对手的对抗
2.抵御购买商讨价还价的能力
3.更灵活地处理供应商的提价行为
4.形成进入障碍
5.梳理与替代品的竞争优势
缺点：
1.降价过度引起利润率降低
2.新加入者可能后来居上
3.丧失对市场变化的预见能力
4.技术变化降低企业资源的效用
5.容易受外部环境的影响
;
****[#lightblue] 适用条件
*****_:
1.企业外部条件：
1）市场需求具有较大的价格弹性
2）行业高度标准化
3）实现产品差异化的途径很少
4）消费者从一个销售商转换到另一个销售商成本很小
2.企业内部条件：
1）持续的资本投资和获得资本的途径
2）生产加工工艺技能
3）认真的劳动监督
4）设计容易制造的产品
5）成本的分销系统
6）培养技术人员
;
**** 风险
*****_:
1.初期投资巨大
2.技术变革滞后
3.忽视客户
4.易于被竞争者模仿
5.缺乏创新的激情
6.依赖价格战
;
*** 差异化战略
**** 概念
*****_:
又称标新立异战略，是指企业凭借自身的技术优势和管理优势，向顾客
提供的产品和服务在行业范围内独具特色，这种特色可以给顾客带来
额外的价值，在消费者心目中树立起非同一般的良好体验
;
****[#lightblue] 优势与风险
*****_:
优势：
1.建立起顾客对企业的忠诚
2.企业提供差异性产品无形为潜在进入者设置了一道进入壁垒
3.可以缓解公司所面临的竞争压力
4.增强企业对供应商讨价还价的能力
5.削弱购买商讨价还价的能力
6.差异化产品可以更好满足消费者需求，促使企业提高销售量或
允许制定更高的价格
风险：
1.多变的市场造成的风险
2.高额专属成本造成的风险
3.闭门造车造成的风险
4.丧失市场份额的风险
;
**** 实现途径
*****_:
1.「产品差异化」
2.「无形差异化」
3.「渠道差异化」
;
**** 适用条件
*****_:
1.消费者对产品有不同需求
2.产品或服务差异化具有价值
3.差异化的市场规模能够支撑差异化成本
;
**** 实施
*****_:
1.分析消费需求
2.分析竞争对手
3.进行技术创新
4.提升服务理念
;

*** 集中化战略
**** 概念
*****_:
指把经营战略重点放在一个特定的目标市场上，为特定地区或特定
的购买者提供特殊的产品或服务
;
**** 核心
*****_:
取得某种对特定顾客有价值的专一性服务，侧重于从企业内部建立
竞争优势
;
**** 实施方法
*****_:
单纯集中化；成本集中化；
差别集中化；业务集中化。
;
*** 融合战略
**** 概念
*****_:
融合战略是指以成本领先战略和差异化战略为基础而建立的一种能够为
顾客创造较高货币价值和较低货币成本的战略
;
**** 分类
*****_:
1.成本导向型融合战略
2.差异化导向型融合战略
3.成本-差异化导向型融合战略
;
**** 构成要件
*****_:
1.经营领域：在一定时期内，企业根据自己的技术特点、人才优势和
资金实力等所确定的从事生产产品的种类或服务的领域
2.资源配置：任何一个战略实施必须有充分的经营资源作支撑，实施
企业融合战略需要对企业各种资源有效配置，把有限资源集中在关键
领域，形成竞争优势，保证企业战略目标的实现
3.竞争优势：一个企业在一定竞争范围内超越其竞争对手的某种长处
4.协同作用：一种联合作用的效果，往往会产生1+1>2的整体效果
;
****[#lightblue] 实施融合战略的影响因素
*****_:
1.主导产业的定位
2.资源富余能力
3.战略切入时机的选择
;
****[#lightblue] 实施条件
*****_:
1.企业在成本或差异化一端要拥有优势
2.低成本优势和差异化优势要有共同基础，即有共同市场或共同技术
3.实施融合战略过程中，企业原有优势产品要处于成熟阶段，或至少
迈过或接近成熟阶段
4.构成融合战略的原因有一定的时间性，过了这段时间，企业所面临
的市场和环境都会发生变化
5.成本控制部门和差异化优势创造部门要做好内部协调防止混乱
6.购买群体在需求上存在差异
7.在企业目标上，没有其他竞争对手试图采用融合战略
8.企业的目标市场在市场容量、成长速度、获利能力、竞争强度方面
具有相对的吸引力
;

** 企业国际化经营战略 5.1%
*** 概述
****[#lightblue] 目标
*****_:
1.增强产品的竞争能力，提高国际市场占有率
2.发展成为知名度高、影响力大的跨国公司
3.以境外投资和技术出口为主，提高跨国投资回报率
;
**** 思想
*****[#lightblue]:
1.经营国际化观念
2.生产全球化观念：即在全球范围内进行专业化协作生产，
参与国际生产的分工与协作过程
3.国际市场营销观念：把国际市场看做一个有机整体，
以此作为企业经营活动的舞台和发展空间
4.产品整体化观念：把产品生产和产品消费看做一个整体，
把产品设计、生产和售后看做一个整体过程
5.联合参与国际竞争观念
;
*** 类型及其决策
**** 类型
*****_:
1.按照产品技术的来源划分
1）反回头战略：当国内某产品市场需求大，但技术落后时，企业引进
国外先进技术，改造落后扩大规模，降低成本，打回国际市场
2）技术带动出口战略：企业开发具有特色的国际领先技术，带动产品
出口
2.按照企业国际化发展的不同阶段划分
1）商品出口战略：生产在国内，商品交换在国际市场，产品满足于
国外顾客需求
2）合资经营战略
3）加工出口战略
4）境外投资战略
5）跨国公司战略
3.按企业生产经营行为标准不同划分
1）本国中心战略
2）多国中心战略
3）全球中心战略
;
****[#lightblue] 类型决策
*****_:
1.国内外市场需求现状及其发展趋势
2.国际市场竞争状况及其竞争发展趋势
3.目标市场所在国的外贸政策和产业政策
4.国内外市场的价格水平和其他市场因素
5.企业本身的出口能力和条件
;
*** 实施措施
**** 关键问题
*****_:
1.战略伙伴的选择
2.组织结构的设计
3.文化价值观与管理
4.外汇风险管理
;
**** 具体措施
*****_:
1.培训国际化经营人才
2.建立有效的国际市场信息网络系统
3.适时调整产品结构
4.提高技术和产品开发能力
5.加强管理控制能力
;

** 企业市场营销战略 5.4%
*** 概述
**** 内容
*****_:
1.目标市场战略
2.市场营销组合战略
3.品牌战略：品牌经营，创优名牌
4.市场营销新谋略：适应高新技术时代，开拓市场过程中出现
直复营销、关系营销、文化营销、绿色营销、网络营销等
;
*** 目标市场战略
**** 作用
*****_:
1.有利于企业分析和发掘新的市场机会
2.有利于企业有针对性地制定市场营销组合策略
3.有利于企业发挥竞争优势
;
**** 方法
*****_:
1.单一变量因素法
2.多变量因素组合法
3.系列变量因素法
;
****[#lightblue] 战略选择
*****_:
1.目标市场营销战略的类型
1）无差异性营销战略：企业忽略细分市场的差别不考虑，针对
市场共性，获取尽多市场份额。优点：成本低、经济性好。
缺点：只适用少数有共同需要、差异不大的商品
2）差异性营销战略：分别在每一细分市场制定不同营销组合。
优点：提高企业竞争能力。缺点：成本高，经营管理难度较大，
对经营管理人员有较强实力和素质要求
3）集中性营销战略：选择一个或少数几个细分市场目标市场，
专业化生产营销。优点：对消费者了解深入，提供最佳产品服务；
降低成本，增加盈利。缺点：目标市场范围小，市场变化带来
风险较大
2.影响战略的因素
1）企业资源
2）产品的同质性
3）市场的同质性
4）产品所处的寿命周期阶段
5）视竞争者战略而定
;
**** 市场定位战略的类型
*****_:
1.避强定位战略
2.仰头定位战略
3.创新定位战略
4.重新定位战略
;
*** 营销组合战略
**** 类型
*****_:
1.产品开到战略
2.价格引路战略
3.渠道开通战略
4.促销开路战略
;
**** 选择或考虑因素
*****_:
1.目标市场的特点
2.企业营销战略的任务
3.企业营销环境
4.企业资源状况
5.营销预算
;
*** 企业品牌战略
**** 内容
*****_:
1.品牌化决策
2.品牌使用者的选择
3.品牌名称决策
4.品牌发展模式的选择
5.品牌重新定位决策
;
**** 类型
*****_:
1.以需求为中心（宝洁）
2.以产品为中心（苹果）
3.以品类为中心（加多宝）
4.以市场为中心（娃哈哈）
;
**** 管理方法
*****_:
1.企业创业期：树立品牌意识
2.企业成长期：提高品牌认知度、强化顾客对品牌核心价值理解
3.企业成熟期：培育「品牌忠诚度」
;

*** 市场营销新谋略
**** 新谋略内容
*****_:
1.「直复营销」：指企业为了在任何地方产生可度量的反应或
达成交易，使用一种或多种广告媒体扩大市场
2.顾客满意营销：以顾客为中心，达到顾客满意为目标开展的
长远性谋略
3.关系营销：指企业把顾客看做有多重利益关系、多层需要，
存在潜在价值的对象
4.文化营销：以提高顾客满意为追求，员工共事的价值观基础
5.绿色营销：确立环保意识，强调环保理念和可持续发展
6.整合营销：兼顾企业、顾客和社会三方面共同利益
7.网络营销：以因特网为核心
;

**[#lightblue] <&star>企业<b>产品</b>战略 21.7%
*** 产品寿命周期与产品战略
**** 不同寿命周期阶段的战略
*****[#lightblue]:
1.投入期：“以新领先”、“新品形象”、新品完善
2.成长期：生产扩大化、新品名牌
3.成熟期：改进或改革产品、优质低价、差异化
4.衰退期：集中、收缩、减产淘汰
;
*** 产品优化战略
****[#lightblue] 方法
*****_:
产品项目平衡管理技术(PPM)，步骤：
1.确定产品市场份额和企业实力因素评分标准
2.对每一个产品进行评分
3.依据产品的市场新引力总分和企业实力总分，划分大中小三等
4.按照每种产品大中小，填入产品系列分布象限
5.根据产品所在的象限，采取不同的战略
;
**** 产品结构优化战略类型
*****_:
1.产品「方向」结构：按产品为不同对象、不同领域所占比重不同
2.产品「用途」结构
3.产品「技术」结构
4.产品「档次」结构：多种质量水平、价格水平
5.产品「材质」结构
6.产品「序列」结构：初级产品、中间产品、最终产品（上中下游）
;
*** 产品开发战略
**** 类型
*****_:
1.按新颖程度：全新型、换代型、改进型
2.按范围和水平：地区级、国家级、国际级、世界级
3.按产品开发方向：产品功能化、产品规格化、产品精密度、
产品节能化、产品特色化
4.按产品开发主体主动性：领先型、追随型
;
*** 产品质量战略
**** 作用
*****_:
1.是企业产品结构优化战略的重要内容
2.是推动企业进步战略的重要方面
3.推动着企业智力开发战略
4.带动着企业生产战略
5.有利于推动企业营销战略
;
**** 类型
*****_:
1.产品质量特性组合战略：
①内在质量为主
②外部质量为主
③内外质量并重
2.产品性能战略：
①高性能
②适中性能
③合格性能
3.产品质量标准战略：
①国家质量标准
②国际质量标准
③国外先进质量标准
④目标市场所在国质量标准
⑤竞争质量标准
⑥用户满意质量标准
4.市场动态质量战略：
①符合性质量战略
②竞争性质量战略
③适用性质量战略
;

** 企业<b>技术</b>创新战略 2.7%
*** 概述
**** 目标与任务
*****_:
1.企业技术创新战略的目标
1）确定企业希望的市场态势：开拓型态势、发展型态势、
创新产品替代、放弃部分已有巩固其余市场
2）其他目标：改善工艺、提高生产率、降低成本等
2.企业技术创新战略的任务
1.审查和评价企业的技术资源和技术能力
2.解读企业外部的技术环境
3.选择和制定企业技术创新战略目标
4.有效地实施和调整技术创新战略
;
**** 构成要素
*****_:
1.<b>基础</b>：企业现有技术和技术能力
2.<b>目标</b>：企业具体要如何实施 5W1H
3.<b>方案</b>：对具体详细规划
4.<b>行动</b>：具体实施活动，严格按照方案执行
;
*** 类型
**** 按技术来源
*****_:
1.自主创新战略
2.合作创新战略
3.引进消化吸收再创新战略
;
**** 按竞争态势
*****_:
1.领先型技术创新战略
2.追随型技术创新战略
3.模仿型技术创新战略
;
****[#lightblue] 基本模式
*****_:
1.市场导向战略模式：企业的技术创新以市场为导向，围绕市场机会进行技术创新。
1）对新产品、行业非常敏感，并且反应强烈
2）注重应用开发，注重模仿
3）注重引进，不注重企业核心能力培养
2.资源导向战略模式：企业为了追求获得高于平均水平的投资收益率而进行技术
创新，技术创新在很大程度上取决于企业的内部特点，具有实力或者竞争优势
比发现机会更重要
;
** <&star>企业<b>人力</b>资源战略 7.5%
*** 人力资源概述
**** 特点
*****_:
生物性、「能动性」、时效性、智力性、再生性、社会性、个体差异性
;
**** 地位
*****_:
人是企业生产要素系统中的一个重要组成部分，是最重要、最活跃
的一种要素，因而处于主体地位和支配地位
;
**** 企业所需的人才类型
*****_:
1.科学技术型人才
2.经营管理型人才
3.政工、企业文化工作型人才
4.行政管理型人才
;
*** 战略及类型
****[#lightblue] 战略概念
*****_:
「人力资源战略」指根据企业总体战略要求，为适应企业生存发展
需要，对企业人力资源进行管理，提高素质，发现培养优秀人才的
长远谋划方略。具体指「雇佣关系」、「甄选」、「录用」、
「培训」、「绩效」、「薪酬」、「激励」、「职业生涯」总称
;
**** 特点
*****_:
战略性、系统性、契合性、目标导向
;
****[#lightblue] 人力资源战略分类
*****_:
1.累积型：终身雇佣，晋升速度慢（人性）
2.效用型：短期，个人，晋升速度快（工作）
3.协助型：累积型和效用型之间
;
**** 人才结构优化战略
*****_:
1.企业人才「层次」结构优化战略：管理层次包括高、中、低层
2.企业人才「能级」结构优化战略：职称包括高、中、低级职称
3.「学科」、「职能」、「智能」、「年龄」
;
**** 使用人才
*****_:
1.任人唯贤战略
2.岗位轮换战略
3.台阶提升使用战略
4.职务、资格双轨使用战略
5.权力委让使用战略
6.破格提拔战略
;
*** 战略实施
****[#lightblue] 人才激励
*****_:
1.物质利益激励
2.目标激励
3.任务激励
4.榜样激励
5.培训激励
6.荣誉激励
7.企业激励
8.制度激励
9.环境激励
10.危机激励
11.信息激励
;
**** 人才发现
*****_:
1.树立爱才之心
2.提高识才之能
3.具备护才之胆
4.掌握选才之法
;
** 企业<b>财务</b>战略 6.6%
*** 概述
**** 含义
*****_:
企业对维持和扩大生产经营活动所需「资金」进行「筹集」、
「分配」、「使用」，为实现企业总体战略目标所作出
的长远谋划与方略
;
**** 特点
*****_:
1.从属性
2.系统性
3.指导性
4.复杂性
;
**** 内容与任务
*****_:
1.内容：融资战略、投资战略、资本运营战略
2.目标：确保企业资金均衡有效流动，最终实现总体战略
3.任务：
1）正确选择「筹集」资金渠道，保证生产经营活动对资金的需求
2）正确选择「资本投向」，合理安排使用
3）正确「运营」资本，重组资本，优化资本结构，提高经济收益
;
**** 作用
*****_:
1.「平衡决策」：对各项经营决策起着综合平衡作用
2.「选择战略」：对各种经营战略方案起着评价选择作用
3.「指导资源」：对经营资源分配起着指导作用
;
*** 企业融资战略
**** 类型
*****_:
1.按融资方式不同
1）资本积聚战略
2）负债经营战略
3）合资或合作经营战略
4）股份经营战略
5）“三来一补”战略
2.按融资渠道不同
1）内源型融资渠道战略
2）外源型融资渠道战略
3.按权益划分
1）股权融资战略
2）债券融资战略
;
**** 融资原则
*****_:
1.以「内源型融资渠道战略」为主
2.努力开通「外源型融资渠道战略」
3.促进优化企业「资本结构」
4.营造良好的「投资环境」
;
*** 企业投资战略
**** 特点
*****_:
1.导向性
2.超前性
3.风险性
;
**** 目标
*****_:
1.收益性目标
2.发展性目标
3.公益性目标
;
**** 原则
*****_:
1.集中性原则：首要原则
2.准确性原则：适时适量
3.权变性原则：灵活投资
4.协同性原则：按比例投资
;
**** 类型选择
*****_:
1.按投资方向：
1）外延型投资战略：增加产量，扩建厂房设备
2）内涵型投资战略：提高质量，提高技术性能
3）兼顾型投资战略：两者兼顾
2.按投资项目：
1）产品投资战略
2）工艺投资战略
3）设备投资战略
4）节能降耗投资战略
5）生产环境改造投资战略
;
**** 考虑因素
*****_:
口诀：「<b>国企需竞争</b>」
1.国家发展战略和产业政策要求
2.企业所属行业的特点
3.市场需求趋势及企业的市场开发能力
4.企业外部资源环境和竞争态势
5.企业自身积累和投资能力
6.企业成长阶段
7.企业当前和今后一定时期的主要矛盾
;
*** 资本运营战略
**** 考虑因素
*****_:
1.国家发展战略和产业政策要求
2.市场需求趋势
3.企业的资源条件
4.企业成长阶段
5.资本市场发育状况
;
**** 风险及应对方案
*****_:
风险：
1.外部环境复杂性变动性
2.企业对环境认知能力有限性
应对：
1.培养资本运营的综合人才
2.建立生产经营与资本运营良性互动机制
3.建立健全的财务制度
4.不断进行创新，形成技术优势
5.强化风险防范意识
;
** <&star>企业文化战略 8.8%
*** 企业文化概述
**** 概念
*****_:
广义：企业生产经营活动中创造的「物质文化」和「精神文化」总和；
狭义：主要指「精神文化」，指支配企业及其职工在从事经营活动时，
共同持有的「理想」、「信念」、「价值观念」、「行为准则」和
「道德规范」的总和
;
**** 结构
*****_:
1.物质层文化（表层）
2.制度行为层文化（幔层）
3.精神层文化（理念层）
;
**** 特征
*****_:
客观性、独特性、相对稳定性、继承融合性、发展性
;
****[#lightblue] 基本内容
*****_:
1.共同的价值观
2.企业使命
3.企业精神
4.企业道德
5.团体意识
6.企业制度
7.行为规范
8.企业形象
;
****[#lightblue] 企业文化与企业经营战略
*****_:
1.企业文化在企业经营战略的作用：①导向作用；②凝聚作用；③规范作用
2.二者联系：二者相互约束、相互影响、相互促进，①企业文化是企业
经营战略的基石；②企业文化是企业经营战略实施的重要手段；③企业文化
与企业经营战略必须相互适应和协调，也是战略成功实施的关键
;
*** 战略及类型
**** 类型
*****_:
1.企业物质文化战略：①企业产品形象战略；②企业职工形象战略；③企业家形象战略
2.企业行为与制度文化战略：①职工榜样战略；②文明生产战略
3.企业精神文明战略：①企业员工共同信念战略；②企业凝聚力战略
4.企业总体形象战略
;
****[#lightblue] 类型的选择
*****_:
1.生产力发展水平和企业技术进步状况
2.企业职工行为规范和职业道德状况
3.企业生产经营水平和市场竞争的地位
4.企业家和员工队伍的素质状况
5.企业总体经营战略及其战略目标的要求
;
*** 制定与实施
**** 制定
*****_:
1.树立正确的企业文化战略思想
2.明确企业文化战略的重点
3.确定企业文化战略的模式：①先导型；②探索型；③稳定型；④追随型；⑤惰性型；
⑥多元型
4.划分企业文化战略阶段
5.制定企业文化战略方案
6.选择卓有成效的企业文化战略
;
****[#lightblue] 实施
*****_:
1.建立企业文化战略实施的计划体系
2.通过一定的组织机构实施
3.提供必要的物质条件、硬件设施和财务支持
4.努力创造有利于实施企业文化战略的文化氛围和环境
;
** 企业经营战略的<b>实施与控制</b> 5%
*** 实施
**** 原则
*****_:
1.目标分解、任务合理原则
2.统一领导、组织协调原则
3.突出重点、兼顾全局原则
4.适应变化、灵活机动原则
;
**** 方式
*****_:
1.指令型方式
2.变革型方式
3.合作型方式
4.文化型方式
5.增长型方式
;
*** 控制
****[#lightblue] 必要性
*****_:
1.企业经营战略实施的环境和条件发生重大变化
2.企业经营战略规划本身存在某种缺陷
3.企业整体目标与局部目标、个人目标之间存在矛盾
4.解决集权与分权的矛盾必须加强企业的经营战略控制
;
**** 原则
*****_:
1.预测未来原则
2.重点控制原则
3.经济合理原则
4.奖惩结合原则
;
**** 重点工作
*****_:
1.设计和选择实施经营战略所需的组织结构
2.将企业经营战略方案具体化：①时间分解、滚动计划法；②空间分解
3.合理配置企业资源，支持经营战略方案的实现
4.组件强有力的战略领导群体：原则 ①选择主要领导原则；②精干
高效原则；③合作和谐原则；④优化组合原则
;
**** 分类
*****_:
1.按照控制发生环节：前馈控制、现场控制、反馈控制
2.按照控制手段：直接控制、间接控制
;

@endmindmap
